### ISSUE TITLE
lazily/manually register the QEMU interpreters

### ISSUE THREAD

**Issue by japaric** [cross-rs/cross#10]
this would save us a docker call

the downside is that this requires `sudo` / root privilege

**Comment by Alexhuszagh** [comment]
If by save a docker call, you mean use qemu outside the container... I'm not sure this is a great idea for a few reasons:

1. Issues with any shared libraries (C or C++ runtimes) required to run the image present only in the image.
2. Cannot run custom operating systems without having a linux image installed.
3. Would require installing qemu on the host, which would require substantial setup.

**Comment by Alexhuszagh** [comment]
This probably isn't worth it anymore, since Rust 1.19 is effectively no longer used, so I think we can safely assume this isn't relevant for nearly all dev environments anymore.
