### ISSUE TITLE
warn / suggest when persistent `CROSS_REMOTE` volume exists for toolchain, but not same version

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#1001]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

say my current toolchain is `stable-x86_64-unknown-linux-gnu` with version 1.63. Rustup reports this toolchain as `stable-*`

```
cross-util volumes create --toolchain x86_64-unknown-linux-gnu
```

will create a volume with the toolchains name and a fingerprint, say `cross-stable-x86_64-unknown-linux-gnu-1750d-a8314ef7d`

if I `rustup update` this toolchain, the name will be the same, but the fingerprint will be different, meaning my persistent volume won't be used anymore.

cross should warn or suggest something about this

**Comment by Emilgardis** [comment]
a side note, `cross-util volumes create --toolchain <target>` should probably actually take a toolchain and not just a target triple

**Comment by Alexhuszagh** [comment]
> a side note, `cross-util volumes create --toolchain <target>` should probably actually take a toolchain and not just a target triple

This definitely should be done, but will be a breaking change. Not sure how this got through.

**Comment by Emilgardis** [comment]
I'm thinking this should only hit on `stable-<triple>`, `beta-<triple>` and `nightly-<triple>`, so should not hit on `nightly-2022-08-30-<triple>`, `1.63.0-<triple>`. ie. what rustup says the toolchain is (`rustup show`), not what `cargo -V` reports.

So differentiation would be

Generate the fingerprint for the toolchain in use, i.e `cross-stable-x86_64-unknown-linux-gnu-1750d-a8314ef7d`.

1. There is no exact match
2. Does the first part of this toolchains fingerprint match `[stable|beta|nightly]-` and does not follow with a number.
3. Are there any existing volumes with the same prefix? i.e `cross-stable-x86_64-unknown-linux-gnu`

warn / suggest to generate a new persistent volume

**Comment by Emilgardis** [comment]
> This definitely should be done, but will be a breaking change. Not sure how this got through.

Not necessarily, as a toolchain can be infered from a target triple, I think it's fine to assume same channel and date if only a target triple is picked
