### ISSUE TITLE
Image Build Fails on Podman

### ISSUE THREAD

**Issue by Alexhuszagh** [cross-rs/cross#1031]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Currently, attempting to build an image for Podman fails, producing the following error:

```bash
$ cargo build-docker-image $target --engine podman                                                                                                                                                  
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/xtask build-docker-image aarch64-linux-android --engine podman`
[cross] note: Build aarch64-linux-android for x86_64-unknown-linux-gnu
Error: unable to parse value provided `` to --cache-from: invalid repo "type=registry,ref=ghcr.io/cross-rs/aarch64-linux-android:main": must contain registry and repository: invalid reference format
Error: 
   0: `podman buildx build --platform linux/amd64 --load --pull --cache-from 'type=registry,ref=ghcr.io/cross-rs/aarch64-linux-android:main' --tag ghcr.io/cross-rs/aarch64-linux-android:local --label 'org.cross-rs.for-cross-target=aarch64-linux-android' --label 'org.cross-rs.runs-with=x86_64-unknown-linux-gnu' -f /home/ahuszagh/git/cross/docker/Dockerfile.aarch64-linux-android --progress auto .` failed with exit status: 125

Location:
   /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/convert/mod.rs:55
```

### What target(s) are you cross-compiling for?

aarch64-linux-android

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [X] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4 (d92e563cdded42aa5468746fc821f9b795880ce2)

### Additional information / notes

Removing the `--cache-from` step fixes the issue. We should probably also add a build image step for `podman`, using the fast image build (`x86_64-unknown-linux-gnu`) to avoid this issue in the future. The podman version is `4.2.0`.

**Comment by Alexhuszagh** [comment]
It seems `--cache-from` only supports a repository using [podman](https://docs.podman.io/en/latest/markdown/podman-build.1.html#cache-from), and this might be true for other container engines. `type=registry` might be implicit. `type=registry` is the default for [docker](https://docs.docker.com/engine/reference/commandline/buildx_build/#cache-from), so we should be able to omit it.

**Comment by Emilgardis** [comment]
I don't think there is a situation where not being explicit about it is bad. Removing the explicitness sounds good 👍🏼
