### ISSUE TITLE
CI With Empty Matrix Caused Failed Conclusion

### ISSUE THREAD

**Issue by Alexhuszagh** [cross-rs/cross#1043]
Running a build with an empty matrix, such as [bors try --none](https://github.com/cross-rs/cross/pull/1042#issuecomment-1264681923) causes the conclusion to fail, even if all other steps pass. Since we can always inspect manually the failure, there's little reason to prioritize this.

**Comment by Alexhuszagh** [comment]
Another thing we should probably do: echo the matrix via `jq` so we can see the colorized output. We lost this when we moved to generate the matrix in Rust, rather than via a shell script.

**Comment by Emilgardis** [comment]
The matrix is emitted in `conclusion` https://github.com/cross-rs/cross/actions/runs/3193205555/jobs/5211551151#step:2:87
