### ISSUE TITLE
PathBuf from a string ending with a backslash and containing a space has escaped double quote added to the end on windows

### ISSUE THREAD

**Issue by drmason13** [cross-rs/cross#1061]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

```rust
use std::{env::args, path::PathBuf};

fn main() {
    let pathbuf: PathBuf = args().nth(1).unwrap().into();
    dbg!(pathbuf);
}
```
Running this on a Linux host and a windows host should return the same results (let me know if that assumption is wrong!)

Instead, this happened:

On Linux (Windows WSL2) it behaves as expected
`cargo build`
```
$ ./target/debug/windows-pathbuf-example '\foo\'
[src/main.rs:5] pathbuf = "\\foo\\"
$ ./target/debug/windows-pathbuf-example '\foo \'
[src/main.rs:5] pathbuf = "\\foo \\"
$ ./target/debug/windows-pathbuf-example 'foo '
[src/main.rs:5] pathbuf = "foo "
$ ./target/debug/windows-pathbuf-example 'foo \'
[src/main.rs:5] pathbuf = "foo \\"
$ ./target/debug/windows-pathbuf-example 'foo\'
[src/main.rs:5] pathbuf = "foo\\"
$ ./windows-pathbuf-example 'foo bar\'
[src/main.rs:5] pathbuf = "foo bar\""
```

When cross compiled (using cross) and run on Windows, I get different behaviour:
`cross build --target x86_64-pc-windows-gnu`
```
PS > .\windows-pathbuf-example.exe '\foo\'
[src/main.rs:5] pathbuf = "\\foo\\"
PS > .\windows-pathbuf-example.exe '\foo \'
[src/main.rs:5] pathbuf = "\\foo \""
PS > .\windows-pathbuf-example.exe 'foo '
[src/main.rs:5] pathbuf = "foo "
PS > .\windows-pathbuf-example.exe 'foo \'
[src/main.rs:5] pathbuf = "foo \""
PS > .\windows-pathbuf-example.exe 'foo\'
[src/main.rs:5] pathbuf = "foo\\"
PS > .\windows-pathbuf-example.exe 'foo bar\'
[src/main.rs:5] pathbuf = "foo bar\""
```

The paths ending with a backslash and contain a space have a double quote inserted into them at the end.

This became a problem in my actual program that took a path from a command line argument and converted to a PathBuf. The converted path didn't work, and confusingly wasn't what the user entered.

### What target(s) are you cross-compiling for?

x86_64-pc-windows-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [X] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4 (da60329 2022-10-02)

### Example

```rust
use std::{env::args, path::PathBuf};

fn main() {
    let pathbuf: PathBuf = args().nth(1).unwrap().into();
    dbg!(pathbuf);
}
```

### Additional information / notes

`rustc --version --verbose`:
```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: x86_64-unknown-linux-gnu
release: 1.63.0
LLVM version: 14.0.5
```

`cross --version --verbose`
```
cross 0.2.4 (da60329 2022-10-02)
+ cargo metadata --format-version 1
+ rustc --print sysroot
+ /usr/bin/podman
+ /usr/bin/podman version -f '{{ .Server.Os }},,,{{ .Server.Arch }}'
+ /usr/bin/podman info -f '{{ .Version.OsArch }}'
+ rustup toolchain list
+ rustup target list --toolchain stable-x86_64-unknown-linux-gnu
+ rustup component list --toolchain stable-x86_64-unknown-linux-gnu
[cross] note: Falling back to `cargo` on the host.
+ cargo --version --verbose
cargo 1.63.0 (fd9c4297c 2022-07-01)
release: 1.63.0
commit-hash: fd9c4297ccbee36d39e9a79067edab0b614edb5a
commit-date: 2022-07-01
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1n)
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by Alexhuszagh** [comment]
I don't think this is a cross issue, since using `cargo run $PATH` itself produces the same behavior on Powershell and Bash (Git Bash for Windows and Powershell on Windows 10):

**Bash**

```bash
$ cargo run 'foo \'
[src/main.rs:5] pathbuf = "foo \\"
$ target/debug/issue_1061.exe 'foo \'
[src\main.rs:5] pathbuf = "foo \\"
```

**Powershell**

```powershell
> cargo run 'foo \'
[src\main.rs:5] pathbuf = "foo \""
> .\target\debug\issue_1061  'foo \'
[src\main.rs:5] pathbuf = "foo \""
```

Notice how both using `cargo run` and invoking the binary itself both produce the exact same behavior as above, without any use of `cross` itself.

**Comment by Alexhuszagh** [comment]
This isn't a cross or Rust issue: we get the exact same behavior with Python:

**main.py**

```python
import sys
print(sys.argv[1])
```

**Bash** 

```bash
$ py -3.9 main.py 'foo \'
foo \
```

**Powershell**

```powershell
> py -3.9 main.py 'foo \'
foo "
```

Oddly, the same doesn't reproduce with ` Write-Output 'foo \'` and `echo 'foo \'` (both on Powershell and Bash they produce `foo \`), so I wonder if how programs parse arguments on Powershell pass the arguments to the program. It's also an issue with C:

**main.c**

```
#include <stdio.h>

int main(int argc, char* argv[]) {
    printf("%s\n", argv[1]);
}
```

**Bash**

```bash
$ g++ main.c
$ ./a.exe 'foo \'
foo \
```

**Powershell**

```powershell
> g++ main.c
> .\a.exe 'foo \'
foo "
```

Even using MSVC we get the same thing

```powershell
> cl main.c
> .\main.exe 'foo \'
foo "
```

**Comment by drmason13** [comment]
Ah fair enough! Thank you so much for such a quick response. I almost posted the issue straight to Rust but was paranoid they'd blame cross for this. Glad it isn't an issue with cross :)

I'm surprised not to have ever come across this before.

I wonder why this happens this way, but agreed, nothing to do with cross or rust. You've been more than helpful enough.

Just ran a couple of times on cmd, just to see what happened:

```
>windows-pathbuf-example.exe 'foo \'
[src/main.rs:5] pathbuf = "'foo"

>windows-pathbuf-example.exe "foo \"
[src/main.rs:5] pathbuf = "foo \""
```
The quotes seem to matter, but basically the same behaviour.

I was able to work around this by just trimming `"` from the resulting string just in case - bit of a hack job but seems like this whole situation is a bit of a hack so 🙃 

Thanks again!
