### ISSUE TITLE
warn when env.volumes is probably a path and not a `var = path`

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#1069]
Related to #1068

https://github.com/cross-rs/cross/blob/683f1dbb23607e273e303840e74bd955cf12af37/src/docker/shared.rs#L571-L584

should warn when the env var is not defined/looks like a path

**Comment by Alexhuszagh** [comment]
I think these are the conditions to warn on:
1. There is no `=` (`value == None`).
2. The key is not a valid Unix shell identifier (`[A-Za-z_]`).

If it is a valid Unix shell identifier, even if the path exists, I don't think we should warn.

**Comment by Emilgardis** [comment]
I think the easiest way to implement this is to check if the var starts with `.` or a `/`, and if not, then check for that if it contains a `/`, that it also contains a `=`

```rs
fn validate_env_var(var: &str) -> Result<(&str, Option<&str>)> {
	if var.starts_with(&['.', '/']) || var.contains('/') && !var.contains('=') {
		eyre::bail!( 
	       "`env.volumes` takes a environment variable (`ENV_VAR`)or `ENV_VAR=../path/to`" 
	   ); 
	};
	let (key, value) = match var.split_once('=') { 
	   Some((key, value)) => (key, Some(value)), 
	   _ => (var, None), 
	}; 
	
	if key == "CROSS_RUNNER" { 
	   eyre::bail!( 
	       "CROSS_RUNNER environment variable name is reserved and cannot be pass through" 
	   ); 
	} 
	
	Ok((key, value)) 
}
```

**Comment by Emilgardis** [comment]
this is because the only relevant use cases for `env.volumes` is when the directory is not in scope of cwd

**Comment by Alexhuszagh** [comment]
> I think the easiest way to implement this is to check if the var starts with `.` or a `/`, and if not, then check for that if it contains a `/`, that it also contains a `=`
> 
> ```rust
> fn validate_env_var(var: &str) -> Result<(&str, Option<&str>)> {
> 	if var.starts_with(&['.', '/']) || (var.contains('/') && !var.contains('=')) {
> 		eyre::bail!( 
> 	       "`env.volumes` takes a environment variable (`ENV_VAR`) or `ENV_VAR=../path/to`" 
> 	   ); 
> 	};
> 	let (key, value) = match var.split_once('=') { 
> 	   Some((key, value)) => (key, Some(value)), 
> 	   _ => (var, None), 
> 	}; 
> 	
> 	if key == "CROSS_RUNNER" { 
> 	   eyre::bail!( 
> 	       "CROSS_RUNNER environment variable name is reserved and cannot be pass through" 
> 	   ); 
> 	} 
> 	
> 	Ok((key, value)) 
> }
> ```

I think we can just split and then check if `value.is_none() && !key.chars().all(|c| matches!(c, 'a'..='z' | 'A'..='Z' | '_' )`.

**Comment by Emilgardis** [comment]
> those without leading `..` but contain them afterwards

ugh, forgot about this case :D
