### ISSUE TITLE
Output when QEMU/docker is actually used

### ISSUE THREAD

**Issue by Susurrus** [cross-rs/cross#107]
We've been trying to debug some `musl` test issues, but we aren't certain if they're QEMU bugs or not since `musl` should be compileable on x86_64-linux for i686 and x86_64 architectures. `cross` doesn't output anything specific specifying when QEMU or Docker is being used, though Docker can be inferred from stdout. Having both of those output during a run would be quite useful.

**Comment by Alexhuszagh** [comment]
Maybe [linux-runner](https://github.com/cross-rs/cross/blob/main/docker/linux-runner) (and also android-runner if #720 merges) should output diagnostic information if cross is run with the `--verbose` flag? We could probably export an envvar like `CROSS_VERBOSE=1` and then if so, `/linux-runner` and `/android-runner` will echo the command they're running.

If we run an Android image with verbose output, it will currently report that we are using Qemu.

```bash
   Finished dev [unoptimized + debuginfo] target(s) in 0.94s
     Running `qemu-i386 -cpu n270 /target/i686-linux-android/debug/hellopp
```

But using a Linux runner will not:

```bash
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `/linux-runner powerpc64le /target/powerpc64le-unknown-linux-gnu/debug/hellopp`
```

**Comment by Alexhuszagh** [comment]
We now have verbose diagnostic information with `QEMU_STRACE`, `CROSS_DEBUG` (specifies every command run in the runner), and you can override `CROSS_TARGET_X86_64_UNKNOWN_LINUX_MUSK_RUNNER=qemu-user` or `CROSS_TARGET_X86_64_UNKNOWN_LINUX_MUSK_RUNNER=native` or do so for any other target (or using Cross.toml below), so you can control if Qemu is used or not, and get verbose diagnostic info on Qemu's output or the scripts used in the Linux/Android runners.

```toml
[target.x86_64-unknown-linux-musl]
runner = "native"
```
