### ISSUE TITLE
Migrate CI to use env files for save state

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#1074]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by Alexhuszagh** [comment]
I'm not sure if we need to do anything about it (or if it will auto-upgrade when required), but [Swatinem/rust-cache](https://github.com/marketplace/actions/rust-cache) is also pulling up Node 12 errors, and there's a newer version that we might be able to upgrade to (1.3.0 -> 2.1.0).

**Comment by Emilgardis** [comment]
We also need to do the changes in our ci scripts
