### ISSUE TITLE
add a `.editorconfig`

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#1089]
maybe we should add a [`.editorconfig`](https://editorconfig.org/) too while I'm at it and lint on it? Unsure how to lint a `.editorconfig` in a simple way though

_Originally posted by @Emilgardis in https://github.com/cross-rs/cross/pull/1015#discussion_r967640904_

**Comment by Alexhuszagh** [comment]
It looks like we can lint pretty effectively with [eclint](https://www.npmjs.com/package/eclint). We'd add the following to our CI

```bash
$ npm install -g eclint
$ eclint *
```
