### ISSUE TITLE
binaries are not copied back to host with `CROSS_REMOTE`

### ISSUE THREAD

**Issue by citizen-stig** [cross-rs/cross#1103]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

After revision 3a897ba34f7142050303f12009af29b73893929a with using `CROSS_REMOTE` produced binaries are not copied to host. 

I believe that PR https://github.com/cross-rs/cross/pull/1072 might cause this issue

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4 (a8082de 2022-10-26)

**Comment by Alexhuszagh** [comment]
It's checking the wrong directory when attempting to copy back:

```bash
/usr/bin/docker exec cross-stable-x86_64-unknown-linux-gnu-16b8c-a8314ef7d-aarch64-unknown-linux-gnu-9076c-1667357458637 bash -c '[[ -d '\''/cross/target'\'' ]]'
```

This is because the target directory here isn't being mounted at `/cross/target`. This hopefully should be an easy fix.

**Comment by hulucc** [comment]
> It's checking the wrong directory when attempting to copy back:
> 
> ```shell
> /usr/bin/docker exec cross-stable-x86_64-unknown-linux-gnu-16b8c-a8314ef7d-aarch64-unknown-linux-gnu-9076c-1667357458637 bash -c '[[ -d '\''/cross/target'\'' ]]'
> ```
> 
> This is because the target directory here isn't being mounted at `/cross/target`. This hopefully should be an easy fix.
> 
> And this is because we're using a relative target directory in the build:
> 
> ```shell
> /usr/bin/docker exec --user 1000:1000 -e 'PKG_CONFIG_ALLOW_CROSS=1' -e 'XARGO_HOME=/home/ahuszagh/.xargo' -e 'CARGO_HOME=/home/ahuszagh/.cargo' -e 'CARGO_TARGET_DIR=/target' -e 'CROSS_RUNNER=' -e CROSS_REMOTE -e TERM -e 'USER=ahuszagh' -e 'CROSS_RUSTC_MAJOR_VERSION=1' -e 'CROSS_RUSTC_MINOR_VERSION=62' -e 'CROSS_RUSTC_PATCH_VERSION=0' -w /home/ahuszagh/Desktop/cross/rust-c-hello-world cross-stable-x86_64-unknown-linux-gnu-16b8c-a8314ef7d-aarch64-unknown-linux-gnu-9076c-1667357458637 sh -c 'PATH="$PATH":"/home/ahuszagh/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin" cargo build --target aarch64-unknown-linux-gnu --verbose --target-dir target
> ```
> 
> So, we need the `--target-dir` probably be an absolute path if not provided.

It works when replace `target_dir` by `format!("{}/{}", package_dirs.mount_root(), target_dir)`

**Comment by Emilgardis** [comment]
Do you want to create a pr to solve this issue @hulucc ? That seems like the way to solve it.
