### ISSUE TITLE
Update Zig to 0.10.0

### ISSUE THREAD

**Issue by Alexhuszagh** [cross-rs/cross#1109]
Currently, cross uses zig `0.9.1`, however, `0.10.0` was recently [released](https://ziglang.org/download/#release-0.10.0). We should upgrade the images to the latest version.

**Comment by Emilgardis** [comment]
https://ziglang.org/download/0.10.0/release-notes.html#zig-c 👀

**Comment by Alexhuszagh** [comment]
All those changes to `zig cc` in terms of bug fixes is just incredible though.
