### ISSUE TITLE
CMake cannot find NDK or toolchain file for Android

### ISSUE THREAD

**Issue by RW-sec** [cross-rs/cross#1110]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I want to compile a dependency which is written in C and build it with CMake. The target is Android aarch64.
In order to do that, I specify in the build.rs file the Android (ANDROID_PLATFORM) and ABI (ANDROID_ABI) version, as requested from the official documentation: https://developer.android.com/ndk/guides/cmake#file
The CMAKE_TOOLCHAIN_FILE variable is not needed anymore, as CMake > 3.21 is used.
When I try to compile it with `cross build --target aarch64-linux-android` CMake cannot find the NDK or a standalone toolchain.

> --- stderr
> CMake Error at /usr/local/share/cmake-3.23/Modules/Platform/Android-Determine.cmake:209 (message):
>   Android: Neither the NDK or a standalone toolchain was found.

Looking at the environment variables I see that the needed variables for CMake are not set as requested here: https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-android

My question is now, what is the best approach in order to built C/C++ dependencies with CMake for Android?

### What target(s) are you cross-compiling for?

aarch64-linux-android

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4 (a8082de 2022-10-26)

**Comment by Alexhuszagh** [comment]
This is CMake specific but should probably also be done for other targets as well, and shouldn't be too difficult since we already provide `CROSS_SYSROOT`. Since CMake and Meson are important enough build tools, we should probably ensure both are adequately supported. Especially because we ship with CMake.

**Comment by Alexhuszagh** [comment]
Setting `CMAKE_SYSROOT` and similar might affect supporting parallel, multi-target builds with a single, all-encompassing image however in #1062.

**Comment by Alexhuszagh** [comment]
We have 2 options here: wrap `cmake` to add the following variables `-DCMAKE_ANDROID_STANDALONE_TOOLCHAIN=/android-ndk -DCMAKE_ANDROID_API=28` on the command-line when using a compatible version, which would require only running this on CMake commands that support this. I think this is the best option, because providing a toolchain file seems to fail on the first run every time, of the following:

```CMake
set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER /android-ndk/bin/aarch64-linux-android-gcc)
set(CMAKE_CXX_COMPILER /android-ndk/bin/aarch64-linux-android-g++)
set(CMAKE_ASM_COMPILER /android-ndk/bin/aarch64-linux-android-gcc)
set(CMAKE_ANDROID_STANDALONE_TOOLCHAIN /android-ndk)
set(CMAKE_ANDROID_API 28)
```

Ideally though, we'd want a toolchain file and do:

```Dockerfile
env CMAKE_TOOLCHAIN_FILE=/opt/cross.cmake
```

I'll play around with this: I can get it to work if I provide both `CMAKE_ANDROID_STANDALONE_TOOLCHAIN` and `CMAKE_ANDROID_API` in the build process.

Unrelated, but we also need to fix the newlib targets with CMake since they have no standard library.

**Comment by RW-sec** [comment]
I tested these two environment variables (`CMAKE_ANDROID_STANDALONE_TOOLCHAIN` and `CMAKE_ANDROID_API`) with a simple test program and can confirm that this works.
Unfortunately when I want to compile the bigger dependency there are some interesting observations.
The **first** run ends with:

```
 --- stderr
  CMake Warning at /usr/local/share/cmake-3.23/Modules/Platform/Android-Determine.cmake:199 (message):
  Android: Did not detect API level from

      /android-ndk/bin/clang

   or

      /android-ndk/sysroot/usr/include/android/api-level.h
```

and also stating that no simple test program could be compiled.
The **second** attempt results in:
```
  -- The C compiler identification is Clang 14.0.6
  -- The ASM compiler identification is Clang with GNU-like command-line
  -- Found assembler: /android-ndk/bin/aarch64-linux-android-gcc
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /android-ndk/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Performing Test CC_SUPPORTS_WA_NOEXECSTACK
  -- Performing Test CC_SUPPORTS_WA_NOEXECSTACK - Success
  -- Performing Test LD_SUPPORTS_WL_Z_NOEXECSTACK
  -- Performing Test LD_SUPPORTS_WL_Z_NOEXECSTACK - Success
  -- Detecting language features in cross-compiling mode impossible. Setting all CPU features OFF.
  -- Looking for getentropy
  -- Looking for getentropy - found
  -- Looking for aligned_alloc
  -- Looking for aligned_alloc - found
  -- Looking for posix_memalign
  -- Looking for posix_memalign - found
  -- Looking for memalign
  -- Looking for memalign - found
  -- Looking for explicit_bzero
  -- Looking for explicit_bzero - not found
  -- Looking for memset_s
  -- Looking for memset_s - not found
  -- Configuring incomplete, errors occurred!
  See also "/target/aarch64-linux-android/debug/build/oqs-sys-bdca09bf7c3fd2c5/out/build/CMakeFiles/CMakeOutput.log".
  See also "/target/aarch64-linux-android/debug/build/oqs-sys-bdca09bf7c3fd2c5/out/build/CMakeFiles/CMakeError.log".

  --- stderr
  CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
     RUN_RESULT (advanced)
     RUN_RESULT__TRYRUN_OUTPUT (advanced)
```
And the **third** run results in:
```
  -- Detecting language features in cross-compiling mode impossible. Setting all CPU features OFF.
  -- Configuring done
  -- The C compiler identification is Clang 14.0.6
  -- The ASM compiler identification is Clang with GNU-like command-line
  -- Found assembler: /android-ndk/bin/aarch64-linux-android-gcc
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /android-ndk/bin/aarch64-linux-android-gcc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Performing Test CC_SUPPORTS_WA_NOEXECSTACK
  -- Performing Test CC_SUPPORTS_WA_NOEXECSTACK - Success
  -- Performing Test LD_SUPPORTS_WL_Z_NOEXECSTACK
  -- Performing Test LD_SUPPORTS_WL_Z_NOEXECSTACK - Success
  -- Configuring incomplete, errors occurred!
  See also "/target/aarch64-linux-android/debug/build/oqs-sys-bdca09bf7c3fd2c5/out/build/CMakeFiles/CMakeOutput.log".
  See also "/target/aarch64-linux-android/debug/build/oqs-sys-bdca09bf7c3fd2c5/out/build/CMakeFiles/CMakeError.log".

  --- stderr
  You have changed variables that require your cache to be deleted.
  Configure will be re-run and you may have to reset some variables.
  The following variables have changed:
  CMAKE_C_COMPILER= /android-ndk/bin/aarch64-linux-android-gcc

  CMake Error at .CMake/gcc_clang_intrinsics.cmake:9 (message):
    Could not compile .CMake/detect_gcc_clang_intrinsics.cChange Dir:
    /target/aarch64-linux-android/debug/build/oqs-sys-bdca09bf7c3fd2c5/out/build/CMakeFiles/CMakeTmp
```

I am not sure why this behavior between these different attempts occur and I will look into it.
Perhaps it would be good to provide the Android toolchain file as CMake can then figure the paths etc. out.

**Comment by Alexhuszagh** [comment]
`CMAKE_ANDROID_API` doesn't work as an environment variable in my tests, so I think that's the issue. We can create a custom toolchain but it's currently failing in my tests as well on the first pass (runs fine on the second attempt, sigh), but hijacking `cmake` and prioritizing it on the path is quite easy to add those two variables in the script, since you just need to check the argument type and if it's a script one, inject it:

https://github.com/Alexhuszagh/xcross/blob/main/cmake/cmake.in

That script's mine (public domain) for a C++ fork of `cross` I authored, but it's a way to inject the arguments during configuration and not other cases (or for unsupported commands). We'd just need to make the build arg `ANDROID_SDK` an environment variable  `CROSS_ANDROID_SDK` probably and use that with the injection.

Install it to `/opt/bin` and have it at the very start of the path (above any other arguments).

**Comment by Alexhuszagh** [comment]
@RW-sec Can you check if #1112 fixes this? You will have to build the images to test:

```bash
git clone https://github.com/Alexhuszagh/cross/tree/cmake
cd cross
cargo build-docker-image aarch64-linux-android
```

Then, once that's done, go to your project and do:

```bash
CROSS_TARGET_AARCH64_LINUX_ANDROID_IMAGE=ghcr.io/cross-rs/aarch64-linux-android:local cross ... --target aarch64-linux-android
```

And test to see if it works.

**Comment by Alexhuszagh** [comment]
Hmmm there's issues here: with `re2` I'm able to get it work on configuration **only** with the second pass, however, on the first it fails. There's something a lot more complicated going on here.

**Comment by Alexhuszagh** [comment]
@RW-sec Can you test the latest version? It should use your cached build for most of it so the image build should be quite simple. This simplifies the toolchain a lot to ensure `CMAKE_C_COMPILER` doesn't change, and also ensures we have the appropriate linking directories found (through symlinks sadly, but there should be no issues. Sigh).

**Comment by RW-sec** [comment]
It works! Thank you very much. It is great to start the new week with this result.
Unfortunately it needs two runs in order to compile successfully.
After the first run CMake still complains about not able to detect the API:

```
  -- Android: Targeting API '28' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
  -- The C compiler identification is Clang 14.0.6
  -- The ASM compiler identification is Clang with GNU-like command-line
  -- Found assembler: /android-ndk/bin/clang
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /android-ndk/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Performing Test CC_SUPPORTS_WA_NOEXECSTACK
  -- Performing Test CC_SUPPORTS_WA_NOEXECSTACK - Success
  -- Performing Test LD_SUPPORTS_WL_Z_NOEXECSTACK
  -- Performing Test LD_SUPPORTS_WL_Z_NOEXECSTACK - Success
  -- Detecting language features in cross-compiling mode impossible. Setting all CPU features OFF.
  -- Looking for getentropy
  -- Looking for getentropy - found
  -- Looking for aligned_alloc
  -- Looking for aligned_alloc - found
  -- Looking for posix_memalign
  -- Looking for posix_memalign - found
  -- Looking for memalign
  -- Looking for memalign - found
  -- Looking for explicit_bzero
  -- Looking for explicit_bzero - not found
  -- Looking for memset_s
  -- Looking for memset_s - not found
  -- Configuring incomplete, errors occurred!

  --- stderr
  CMake Warning at /usr/local/share/cmake-3.23/Modules/Platform/Android-Determine.cmake:199 (message):
    Android: Did not detect API level from

      /android-ndk/bin/clang

    or

      /android-ndk/sysroot/usr/include/android/api-level.h

  Call Stack (most recent call first):
    /usr/local/share/cmake-3.23/Modules/CMakeDetermineSystem.cmake:160 (include)
    CMakeLists.txt:22 (project)


  CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
     RUN_RESULT (advanced)
     RUN_RESULT__TRYRUN_OUTPUT (advanced)
```
This could be problematic for CI/CD such that they can get stuck, but at the moment I am happy that it is compiling.

**Comment by Alexhuszagh** [comment]
Interesting, I'm glad it's working much better. I've spent a lot of time trying to avoid requiring the 2nd pass: that warning shouldn't be the actual issue (there's no real way to turn that off and it's expected). The error seems to be from it trying to compile a test binary to see if it works, and it's failing because it's in cross-compilation mode, but it doesn't have an adequate runner. I believe this is fixed if the `binfmt` interpreters are installed on the host, or if we set `CMAKE_CROSSCOMPILING_EMULATOR`. This should probably done for **every** target tbh.

IE, the error is from [try_run](https://cmake.org/cmake/help/latest/command/try_run.html), which successfully compiles but can't run the resulting binary, and so it reports it failed the test.

```
  CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
     RUN_RESULT (advanced)
     RUN_RESULT__TRYRUN_OUTPUT (advanced)
```

This could be internal to your build system, or a third-party library, however, this is also something we should fix on our end. `CMAKE_CROSSCOMPILING_EMULATOR` should probably be set for every target.

As CMake recommends:

> In order to make cross compiling your project easier, use try_run only if really required. If you use try_run, use the RUN_OUTPUT_STDOUT_VARIABLE, RUN_OUTPUT_STDERR_VARIABLE, RUN_OUTPUT_VARIABLE or OUTPUT_VARIABLE options only if really required.

**Verbose Log from a Sample Project:**

```
[rust-cmake-hello-world 0.1.0] running: "cmake" "/home/ahuszagh/git/rust-cmake-hello-world/libsum" "-DCMAKE_TOOLCHAIN_FILE=/opt/android.cmake" "-DCMAKE_INSTALL_PREFIX=/target/aarch64-linux-android
/debug/build/rust-cmake-hello-world-fdece5eb2e292905/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_ASM_F
LAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_BUILD_TYPE=Debug"                                                                                                                         
[rust-cmake-hello-world 0.1.0] CMake Warning at /usr/local/share/cmake-3.23/Modules/Platform/Android-Determine.cmake:199 (message):                                                                 
[rust-cmake-hello-world 0.1.0]   Android: Did not detect API level from                                                                                                                             
[rust-cmake-hello-world 0.1.0]                                                                                                                                                                      
[rust-cmake-hello-world 0.1.0]     /android-ndk/bin/clang                                                                                                                                           
[rust-cmake-hello-world 0.1.0]                                                                                                                                                                      
[rust-cmake-hello-world 0.1.0]   or                                                                                                                                                                 
[rust-cmake-hello-world 0.1.0]                                                                                                                                                                      
[rust-cmake-hello-world 0.1.0]     /android-ndk/sysroot/usr/include/android/api-level.h                                                                                                             
[rust-cmake-hello-world 0.1.0]                                                                                                                                                                      
[rust-cmake-hello-world 0.1.0] Call Stack (most recent call first):                                                                                                                                 
[rust-cmake-hello-world 0.1.0]   /usr/local/share/cmake-3.23/Modules/CMakeDetermineSystem.cmake:160 (include)                                                                                       
[rust-cmake-hello-world 0.1.0]   CMakeLists.txt:2 (project)                                                                                                                                         
[rust-cmake-hello-world 0.1.0]                                                                                                                                                                      
[rust-cmake-hello-world 0.1.0]                                                                                                                                                                      
[rust-cmake-hello-world 0.1.0] -- Android: Targeting API '28' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'                                                                   
[rust-cmake-hello-world 0.1.0] -- The C compiler identification is Clang 14.0.6                                                                                                                     
[rust-cmake-hello-world 0.1.0] -- The CXX compiler identification is Clang 14.0.6                                                                                                                   
[rust-cmake-hello-world 0.1.0] -- Detecting C compiler ABI info                                                                                                                                     
[rust-cmake-hello-world 0.1.0] -- Detecting C compiler ABI info - done                                                                                                                              
[rust-cmake-hello-world 0.1.0] -- Check for working C compiler: /android-ndk/bin/clang - skipped                                                                                                    
[rust-cmake-hello-world 0.1.0] -- Detecting C compile features                                                                                                                                      
[rust-cmake-hello-world 0.1.0] -- Detecting C compile features - done                                                                                                                               
[rust-cmake-hello-world 0.1.0] -- Detecting CXX compiler ABI info                                                                                                                                   
[rust-cmake-hello-world 0.1.0] -- Detecting CXX compiler ABI info - done                                                                                                                            
[rust-cmake-hello-world 0.1.0] -- Check for working CXX compiler: /android-ndk/bin/clang++ - skipped                                                                                                
[rust-cmake-hello-world 0.1.0] -- Detecting CXX compile features                                                                                                                                    
[rust-cmake-hello-world 0.1.0] -- Detecting CXX compile features - done                                                                                                                             
[rust-cmake-hello-world 0.1.0] -- Configuring done
[rust-cmake-hello-world 0.1.0] -- Generating done 
[rust-cmake-hello-world 0.1.0] CMake Warning:
[rust-cmake-hello-world 0.1.0]   Manually-specified variables were not used by the project:
[rust-cmake-hello-world 0.1.0] 
[rust-cmake-hello-world 0.1.0]     CMAKE_ASM_FLAGS
[rust-cmake-hello-world 0.1.0] 
[rust-cmake-hello-world 0.1.0] 
[rust-cmake-hello-world 0.1.0] -- Build files have been written to: /target/aarch64-linux-android/debug/build/rust-cmake-hello-world-fdece5eb2e292905/out/build
```

**Comment by RW-sec** [comment]
Perfect! When setting the `CMAKE_CROSSCOMPILING_EMULATOR` variable it compiles at the first try.
Good to know that CMake actually tries to run the test program it compiles. It is then clear that it will fail, if it cannot run it for the target architecture. From this observation it is indeed necessary to specify for each target a runner s.t. CMake can execute its test program.
When I compile the dependency with verbose logging, I also see the warning about the failed detection of the API, but it still compiles.
The last question is now: What was happening in the previous second runs? Did CMake gave up and did not try to execute the test program or did CMake found the runner?

**Comment by Alexhuszagh** [comment]
This isn't complete until #1112 is merged, but I'm, glad everything works.

> The last question is now: What was happening in the previous second runs? Did CMake gave up and did not try to execute the test program or did CMake found the runner?
I think it skipped the check, yeah. It sometimes does this.
