### ISSUE TITLE
update env docs

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#1117]
https://github.com/cross-rs/cross/tree/108daab1a71c617cc0b57db96ee1a69c04608c55#passing-environment-variables-into-the-build-environment

should be updated to take into account the changes done in https://github.com/cross-rs/cross/pull/921 and https://github.com/cross-rs/cross/pull/869

**Comment by Alexhuszagh** [comment]
This should also be done on the [wiki](https://github.com/cross-rs/cross/wiki/Configuration).
