### ISSUE TITLE
ubuntu DevMapper failed to register

### ISSUE THREAD

**Issue by syncharny** [cross-rs/cross#114]
Anyone know how to get around this error?

> cross build --target=armv7-unknown-linux-gnueabihf
> Unable to find image 'japaric/armv7-unknown-linux-gnueabihf:v0.1.11' locally
> 
> v0.1.11: Pulling from japaric/armv7-unknown-linux-gnueabihf
> d8868e50ac4c: Extracting [==================================================>]   39.1MB/39.1MB
> 83251ac64627: Download complete
> 589bba2f1b36: Download complete
> d62ecaceda39: Download complete
> 6d93b41cfc6b: Download complete
> 74a9cf4bb9b4: Download complete
> 69a17e69e4eb: Download complete
> d796a0cc8ecc: Download complete
> 40189f5b4974: Download complete
> 497a8fe6ae16: Download complete
> 8f904dc90df6: Download complete
> 4064baee5519: Download complete
> docker: failed to register layer: devmapper: Error mounting '/dev/mapper/docker-252:0-261821-61fdf1ed13c8edda179ee324d92d675bbfc209b3cecdd7abcde0030748c44fde' on '/var/lib/docker/devicemapper/mnt/61fdf1ed13c8edda179ee324d92d675bbfc209b3cecdd7abcde0030748c44fde': input/output error.

> uname -a
Linux blyncsyvm 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jamesmunns** [comment]
@syncharny were you able to work around this?

**Comment by Alexhuszagh** [comment]
This is unlikely to be an issue anymore since Docker uses overlay2 as the default storage driver, but workarounds are documented [here[(https://github.com/moby/moby/issues/29798). This is a docker issue and not specific to cross.
