### ISSUE TITLE
Config in Cargo.toml: invalid type: map, expected a string for key `target.x86_64-unknown-freebsd.image`

### ISSUE THREAD

**Issue by n8henrie** [cross-rs/cross#1182]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Related: https://github.com/cross-rs/cross/issues/657

### What target(s) are you cross-compiling for?

x86_64-unknown-freebsd

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [X] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4

### Example

```console
$ cargo new foo && cd $_
$ cat <<'EOF' >> Cargo.toml
﻿﻿﻿[package.metadata.cross.target.x86_64-unknown-freebsd]
image.name = "ghcr.io/cross-rs/x86_64-unknown-freebsd:local"
image.toolchain = ["linux/arm64/v8=aarch64-unknown-linux-gnu"]
EOF
$ cross build --target x86_64-unknown-freebsd --release
```

Using cross 0.2.4 from nixpkgs or crates.io, I get:

```
Error:
   0: invalid type: map, expected a string for key `target.x86_64-unknown-freebsd.image`
```

Using cross from `main`, I get a different error:

```console
$ cargo install cross --git https://github.com/cross-rs/cross
$ cross --version
cross 0.2.4 (1d9d310 2023-01-05)
$ cross build --target x86_64-unknown-freebsd --release
Error:
   0: invalid type: string "linux/arm64/v8=aarch64-unknown-linux-gnu", expected a borrowed string for key `target.x86_64-unknown-freebsd.image.toolchain`

Location:
   src/cross_toml.rs:181
```

If I instead put (what I believe to be) the analogous table into `Cross.toml`, I get the same error with nixpkgs and crates.io but it works fine from `main`:

```console
$ cat <<'EOF' > Cross.toml
[target.x86_64-unknown-freebsd]
image.name = "ghcr.io/cross-rs/x86_64-unknown-freebsd:local"
image.toolchain = ["linux/arm64/v8=aarch64-unknown-linux-gnu"]
EOF
$ cross --version
cross 0.2.4 (1d9d310 2023-01-05)
[cross] warning: `cross` does not provide a Docker image for target aarch64-apple-darwin, specify a custom image in `Cross.toml`.
[cross] note: Falling back to `cargo` on the host.
cargo 1.66.0 (d65d197ad 2022-11-15)
$ cross build --target x86_64-unknown-freebsd --release
   Compiling foo v0.1.0 (/private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.ililnMNd9D/foo)
    Finished release [optimized] target(s) in 8.52s
```

Using the current `main`, as recommended in the README, is it expected that this table works from `Cross.toml` but not from `Cargo.toml`?

Thanks for your work on a cool project!

**Comment by Emilgardis** [comment]
This should work in `Cargo.toml`, the issue is how we're doing the deserialization

https://github.com/cross-rs/cross/blob/main/src/cross_toml.rs#LL177C17-L177C17

and https://github.com/cross-rs/cross/blob/1d9d31080c641d37d5213992f12a557d8e47664e/src/docker/image.rs#LL108C11-L108C11

**Comment by Emilgardis** [comment]
Alright, that was wrong, it's a bit more "wierd".

When merging, we create a `CrossToml` from the metadata here: 
https://github.com/cross-rs/cross/blob/1d9d31080c641d37d5213992f12a557d8e47664e/src/cross_toml.rs#L213-L213

this works fine in most cases, however, when the serialization does not match the deserialization, this fails do not match (i.e it can be either a toml string or array).

Solution is to serialize https://github.com/cross-rs/cross/blob/1d9d31080c641d37d5213992f12a557d8e47664e/src/docker/image.rs#L109-L117 as a string

**Comment by n8henrie** [comment]
Wow, super fast fix. Thank you!

After putting the config back in `Cargo.toml` it builds

```console
$ cargo install cross --git https://github.com/Emilgardis/cross --branch fix-1182
$ cross --version
cross 0.2.4 (6a57d01 2023-01-06)
[cross] warning: `cross` does not provide a Docker image for target aarch64-apple-darwin, specify a custom image in `Cross.toml`.
[cross] note: Falling back to `cargo` on the host.
cargo 1.66.0 (d65d197ad 2022-11-15)
$ cross build --target x86_64-unknown-freebsd --release
    Finished release [optimized] target(s) in 1.41s
$ file target/x86_64-unknown-freebsd/release/hello-world-pfsense
target/x86_64-unknown-freebsd/release/hello-world-pfsense: ELF 64-bit LSB pie executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 12.4, FreeBSD-style, stripped
$ scp target/x86_64-unknown-freebsd/release/hello-world-pfsense router:/tmp
hello-world-pfsense                                                                                                                                                                                         100%  275KB   1.4MB/s   00:00
$ ssh router /tmp/hello-world-pfsense
Hello, world!
```

I'm not sure about the warning, but it seems to work!

**Comment by n8henrie** [comment]
This error is back.

```console
$ tail -n 3 Cargo.toml 
[package.metadata.cross.target.x86_64-unknown-freebsd]
image.name = "ghcr.io/cross-rs/x86_64-unknown-freebsd:local"
image.toolchain = ["linux/arm64/v8=aarch64-unknown-linux-gnu"]
$ cross --version
cross 0.2.5
Error: 
   0: invalid type: map, expected a string for key `target.x86_64-unknown-freebsd.image`
```

Based on [the docs](https://github.com/cross-rs/cross/blob/main/docs/config_file.md#targettargetimage) it looks like `image.name` and `image.toolchain` are still supported configuration values.

**Comment by guapodero** [comment]
> This error is back.
> 
> ```
> $ tail -n 3 Cargo.toml 
> [package.metadata.cross.target.x86_64-unknown-freebsd]
> image.name = "ghcr.io/cross-rs/x86_64-unknown-freebsd:local"
> image.toolchain = ["linux/arm64/v8=aarch64-unknown-linux-gnu"]
> $ cross --version
> cross 0.2.5
> Error: 
>    0: invalid type: map, expected a string for key `target.x86_64-unknown-freebsd.image`
> ```
> 
> Based on [the docs](https://github.com/cross-rs/cross/blob/main/docs/config_file.md#targettargetimage) it looks like `image.name` and `image.toolchain` are still supported configuration values.
> 
> EDIT: Only getting this from crates.io, installing from git seems to work.

+1
