### ISSUE TITLE
leptos, cross warning: unable to get metadata for package

### ISSUE THREAD

**Issue by beeb** [cross-rs/cross#1190]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

See https://github.com/beeb/remote-wol-rs/actions/runs/3969612747/jobs/6804578757

I added the vendored version of openssl into my Cargo.toml file, which normally works to build in CI.

For this project however, it complains about `/bin/sh: 1: aarch64-linux-gnu-gcc: not found`

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross v0.2.4 (https://github.com/cross-rs/cross#8c86a98d)

### Example

See https://github.com/beeb/remote-wol-rs/actions/runs/3969612747/jobs/6804578757

**Comment by Emilgardis** [comment]
Please note the warning

```
[cross] warning: unable to get metadata for package
[cross] note: Falling back to `cargo` on the host.
```
https://github.com/beeb/remote-wol-rs/actions/runs/3969612747/jobs/6804578757#step:6:10

can you reproduce the issue locally?

**Comment by beeb** [comment]
I can't reproduce locally because I'm facing https://github.com/cross-rs/cross/issues/1189 on my machine and can't even go that far.

Maybe I'm just misunderstanding how I can cross-compile the server part of my leptos application. Normally I would use `cargo leptos` locally but it doesn't support cross-compile. `cargo leptos` invokes this command to build the server so I thought that should work:

```
cargo build --package=remote_wol --bin=remote_wol --target-dir=target/server --no-default-features --features=ssr --release
```

**Comment by beeb** [comment]
I'll be damned... https://github.com/beeb/remote-wol-rs/actions/runs/3970758818/jobs/6807044897

This time around it went though, with the same command (except for the added `-v`)

**Comment by Emilgardis** [comment]
interesting! I guess it was a cosmic ray or something

**Comment by beeb** [comment]
Can't be reproduced anymore
