### ISSUE TITLE
nixos armv7 musl docker images are not working using different version of building image than other distro

### ISSUE THREAD

**Issue by takov751** [cross-rs/cross#1196]
Done everything according documentation there is no issue when built with `armv7-unknown-linux-gnueabihf` it's fine. However when `armv7-unknown-linux-musleabihf` runs the output is 

```
cross build --target armv7-unknown-linux-musleabihf --release
sh: 1: cargo: not found

```
both t armv7-unknown-linux-musleabih and hf version has the same issue.

**Comment by Emilgardis** [comment]
Hi!

What system are you on? What version of cross are you using? 

Can you add `-v` to the arguments to get verbose output

**Comment by takov751** [comment]
```
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 22.11 (Raccoon)"
SUPPORT_END="2023-06-30"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="22.11 (Raccoon)"
VERSION_CODENAME=raccoon
VERSION_ID="22.11"

```
```
cross 0.2.4
[cross] warning: unable to get metadata for package
[cross] note: Falling back to `cargo` on the host.
cargo 1.66.1 (ad779e08b 2023-01-10)

[nix-she
```

**Comment by takov751** [comment]
Further testing shows it's indeed an issue with my nixos config. on ubuntu it does seems to build. on nixos the docker image `0.2.4` used on ubuntu docker image `main` called

**Comment by Emilgardis** [comment]
for nix, make sure `NIX_STORE` points correctly. https://github.com/cross-rs/cross/wiki/Configuration#environment-variables

**Comment by takov751** [comment]
Thank you for your help as I have went trough the list the only thing i had to change was 0
`CROSS_COMPATIBILITY_VERSION=main`
and it started working. weird

**Comment by Emilgardis** [comment]
Interesting, that does nothing.

https://github.com/cross-rs/cross/blob/80c9f9109a719ffb0f694060ddc6e371d5b3a540/src/lib.rs#L173

only `CROSS_COMPATIBILITY_VERSION=0.2.1` is supported

**Comment by takov751** [comment]
That is interesting I will look into it what changed. Thanks for help
