### ISSUE TITLE
Publish API documentation

### ISSUE THREAD

**Issue by mcandre** [cross-rs/cross#1235]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

Can we get static API docs published for cross as a library?

### Describe why this would be a good inclusion for `cross`

So that it's easier to enjoy cross capabilities via downstream Rust libraries and tools.

For example, safely looping over targets the Cross.toml file without having to assume a particular or permanent schema.

**Comment by Emilgardis** [comment]
The library api is available, but contain a warning.

<img width="974" alt="image" src="https://user-images.githubusercontent.com/1502855/227854416-8e4d8ac9-3e7d-48f2-9c1c-14fccc42028a.png">


https://docs.rs/cross/latest/cross/
