### ISSUE TITLE
General question: How well is FFI supported?

### ISSUE THREAD

**Issue by mcandre** [cross-rs/cross#1242]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

Let's say a Rust project depends on a C/C++ library.

Assume that the library is written in extremely portable C/C++ code.

Assume that any other C/C++ library sub-dependencies (e.g. `RUN apt-get install libcurl`, or whatever, on top of a cross base image), are installed in some custom cross Docker images, and Cross.toml is configured to reference the images.

Does cross work well for projects like that?

I am more familiar with FFI in terms of Cgo, where `go mod` epic fails to even download the C/C++ source code. Do rustc, cargo, and cross have better support for FFI?

Anyone already using cross to generate ports for Rust FFI projects?

Naturally, we want to promote any C/C++ dependencies to pure Rust long term. But as a stopgap measure, it is useful to support FFI when needed.

### Describe why this would be a good inclusion for `cross`

General question about how cross, cargo, and rustc integrate with FFI for cross-compilation purposes.

**Comment by Emilgardis** [comment]
Yes, this is one of the core features of rust. We actually even have special configuration to install dependencies with cross, see [the cross wiki](https://github.com/cross-rs/cross/wiki/Recipes#openssl) for how to install openssl, which is used by the [`openssl-sys` crate](https://crates.io/crates/openssl-sys/0.9.84) for example.

I'd recommend you check out [Ryust by Example: FFI](https://doc.rust-lang.org/rust-by-example/std_misc/ffi.html), [Nomicon: FFI](https://doc.rust-lang.org/nomicon/ffi.html), [A guide for doing FFI using Rust](https://michael-f-bryan.github.io/rust-ffi-guide/), [Youtube: Crust of Rust - Build scripts and FFI](https://www.youtube.com/watch?v=pePqWoTnSmQ) and finally [The Big Book of Rust Interop](https://nrc.github.io/big-book-ffi/)

I'd highly suggest you post questions like these on any of the forums available [here](https://www.rust-lang.org/community), [the rust community discord](https://discord.com/invite/rust-lang-community) or [the rust reddit](https://old.reddit.com/r/rust/) instead 😄
