### ISSUE TITLE
Cannot find `Cargo.toml` while running `cross test --target x86_64-unknown-linux-gnu`

### ISSUE THREAD

**Issue by setoelkahfi** [cross-rs/cross#1250]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I have a custom build.rs script that scans a `Cargo.toml` file. It couldn't find such a file on target `x86_64-unknown-linux-gnu`, but it works fine on my host machine architecture (`aarch64-apple-darwin`).

### What target(s) are you cross-compiling for?

x86_64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [X] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5

### Example

```sh
git clone https://github.com/setoelkahfi/pre-commit-hooks
cd pre-commit-hooks
cross test --target x86_64-unknown-linux-gnu 
```

Gives:
```sh
error: failed to run custom build command for `pre-commit-hooks v0.2.0 (/project)`

Caused by:
  process didn't exit successfully: `/target/debug/build/pre-commit-hooks-89f088d63e356bbd/build-script-build` (exit status: 1)
  --- stdout
  Looking for root in "/target/x86_64-unknown-linux-gnu/debug/build/pre-commit-hooks-7148d8836120c98e/out".
  Looking for root in "/target/x86_64-unknown-linux-gnu/debug/build/pre-commit-hooks-7148d8836120c98e".
  Looking for root in "/target/x86_64-unknown-linux-gnu/debug/build".
  Looking for root in "/target/x86_64-unknown-linux-gnu/debug".
  Looking for root in "/target/x86_64-unknown-linux-gnu".
  Looking for root in "/target".
  Looking for root in "/".
  Error: Crate root not found.
```

**Comment by Emilgardis** [comment]
You should not be assuming that the Cargo.toml lives in the same sub-directory as the `OUTDIR`, the target directory and out directory is [fully customizable](https://doc.rust-lang.org/cargo/commands/cargo-build.html#output-options). Instead, you should use `cargo metadata`.

This should work for you :)

```rs
fn find_crate_root() -> io::Result<path::PathBuf> {
    let meta = std::process::Command::new("cargo")
        .args(["metadata", "--format-version=1", "--no-deps"])
        .output()?;
    'workspace: {
        if meta.status.success() {
            let output = String::from_utf8_lossy(&meta.stdout);
            let Some(path) =output
                .split(r#"workspace_root":""#)
                .nth(1) else {
                break 'workspace;
            };
            let Some(path) = path.split('"').next() else {
                break 'workspace;
            };
            return Ok(path::PathBuf::from(path));
        }
    }
    Err(io::Error::new(
        io::ErrorKind::Other,
        "couldn't find crate root",
    ))
}
```

**Comment by setoelkahfi** [comment]
@Emilgardis can you explain the `'workspace` part? I'm still new to Rust.

**Comment by Emilgardis** [comment]
Sorry, that might've been a bit esoteric!

`'workspace` is a feature called [labelled block expressions](https://doc.rust-lang.org/reference/expressions/loop-expr.html#labelled-block-expressions), it basically allows you do to what a [label on a loop](https://doc.rust-lang.org/reference/expressions/loop-expr.html#loop-labels) does, but on a block. See the [book](https://doc.rust-lang.org/book/ch03-05-control-flow.html#loop-labels-to-disambiguate-between-multiple-loops)

the code can be rewritten as:

```rs
fn find_crate_root() -> io::Result<path::PathBuf> {
    let meta = std::process::Command::new("cargo")
        .args(["metadata", "--format-version=1", "--no-deps"])
        .output()?;

    if meta.status.success() {
        let output = String::from_utf8_lossy(&meta.stdout);
        let path = if let Some(path) = output.split(r#"workspace_root":""#).nth(1) {
            path
        } else {
            return Err(io::Error::new(
                io::ErrorKind::Other,
                "couldn't find crate root",
            ));
        };
        let path = if let Some(path) = path.split('"').next() {
            path
        } else {
            return Err(io::Error::new(
                io::ErrorKind::Other,
                "couldn't find crate root",
            ));
        };
        return Ok(path::PathBuf::from(path));
    }
    Err(io::Error::new(
        io::ErrorKind::Other,
        "couldn't find crate root",
    ));
}
```

**Comment by Emilgardis** [comment]
Oh yeah, I should mention, there's also the env var `CARGO_MANIFEST_DIR`set for buildscripts, see https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts

so you could just replace `OUTDIR` with `CARGO_MANIFEST_DIR`

**Comment by setoelkahfi** [comment]
> Sorry, that might've been a bit esoteric!
> 
> `'workspace` is a feature called [labelled block expressions](https://doc.rust-lang.org/reference/expressions/loop-expr.html#labelled-block-expressions), it basically allows you do to what a [label on a loop](https://doc.rust-lang.org/reference/expressions/loop-expr.html#loop-labels) does, but on a block. See the [book](https://doc.rust-lang.org/book/ch03-05-control-flow.html#loop-labels-to-disambiguate-between-multiple-loops)
> 
> the code can be rewritten as:
> 
> ```rust
> fn find_crate_root() -> io::Result<path::PathBuf> {
>     let meta = std::process::Command::new("cargo")
>         .args(["metadata", "--format-version=1", "--no-deps"])
>         .output()?;
> 
>     if meta.status.success() {
>         let output = String::from_utf8_lossy(&meta.stdout);
>         let path = if let Some(path) = output.split(r#"workspace_root":""#).nth(1) {
>             path
>         } else {
>             return Err(io::Error::new(
>                 io::ErrorKind::Other,
>                 "couldn't find crate root",
>             ));
>         };
>         let path = if let Some(path) = path.split('"').next() {
>             path
>         } else {
>             return Err(io::Error::new(
>                 io::ErrorKind::Other,
>                 "couldn't find crate root",
>             ));
>         };
>         Ok(path::PathBuf::from(path))
>     } else {
> 		Err(io::Error::new(
>         	io::ErrorKind::Other,
>         	"couldn't find crate root",
>     	))
> 	} 
> }
> ```

Ok, this one is easier to follow. I'll go back to the 'workspace syntax later. 

It can't be compiled though, it says `cannot return value referencing local variable `output``, right when it wraps the path in `Ok`.
```
        let path = path::Path::new(path);
        Ok(path)
```
The `meta.stdout` and `output` are borrowed.

**Comment by Emilgardis** [comment]
You need to return/use a `PathBuf`, not a `Path`. The difference is the same as between `String` and `str`
