### ISSUE TITLE
protobuf-compiler not found even when it is installed

### ISSUE THREAD

**Issue by Asone** [cross-rs/cross#1257]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Hi, 

I'm facing a hard time using cross with protobuf compiling. 

The project consists of two binaries projects with another workspace member embedding the protobuf : 
- Global repo [Cargo.toml](https://github.com/Asone/nostrss/blob/main/Cargo.toml)
- [nostrss-core](https://github.com/Asone/nostrss/blob/main/nostrss-core/Cargo.toml)
- [nostrss-cli](https://github.com/Asone/nostrss/blob/main/nostrss-cli/Cargo.toml)
- [grpc part](https://github.com/Asone/nostrss/blob/main/nostrss-grpc/Cargo.toml)

This is what i come through anytime i try to compile : 

````
Error: failed to run custom build command for `nostrss_grpc v0.1.0 (/project/nostrss-grpc)`
Caused by:
  process didn't exit successfully: `/target/release/build/nostrss_grpc-b025e56850f8952d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=protos/nostrss.proto
  cargo:rerun-if-changed=proto

  --- stderr
  thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.If you're on debian, try `apt-get install protobuf-compiler` or download it from https://github.com/protocolbuffers/protobuf/releases

  For more information: https://docs.rs/prost-build/#sourcing-protoc
  ', /cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.11.9/src/lib.rs:1457:10
````
You'll find more context [here](https://github.com/Asone/nostrss/actions/runs/4941459680/jobs/8834377746#step:9:486)

This happens no matter what i do, and even when i ensure that protoc is installed. 
If you look at the steps of the CI linked a bit above you'll see that the protobuf-compiler is installed ( many times ) : 
- [here](https://github.com/Asone/nostrss/blob/main/.github/workflows/release.yml#L104) ([result](https://github.com/Asone/nostrss/actions/runs/4941459680/jobs/8834377746#step:7:9))
- or [here](https://github.com/Asone/nostrss/blob/main/.github/workflows/release.yml#L120) ([result](https://github.com/Asone/nostrss/actions/runs/4941459680/jobs/8834377746#step:6:1))

I even tried to declare `PROTOC` before calling `cross` using `which protoc` (see [here](https://github.com/Asone/nostrss/blob/main/.github/workflows/release.yml#L127)). No luck. 

Yet, when using `cargo` i have no problem compiling. See [here](https://github.com/Asone/nostrss/actions/runs/4944454224)

I tried then to cross compile on my local machine (an intel i7 macbook pro from 2018) and it appears i do have the same problem. compiling with `cargo` even the release works like a charm, but `cross` fails with the exact same problem. 

I don't know if i am missing something regarding the configuration or if this is a bug/blind spot of cross. 

Many thanks for your help/feedback 🙏 

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross v0.2.5

**Comment by Emilgardis** [comment]
You need to install the dependency in the container, see https://github.com/cross-rs/cross/wiki/Recipes#pre-build for an example on how to install openssl development libraries.

Your cross builds don't use anything from the outside environment except for the code you're compiling and the rust cross-compiler. So installing protobuf on the host wouldn't automatically make it available inside the cross build.


So for protoc, targetting x86_64, it'd be

```toml
#Cross.toml
[target.x86_64-unknown-linux-gnu]
pre-build = ["apt update && apt upgrade && apt install -y protobuf-compiler"]
```

I don't know how protobuf works, but if it's a build-time dependency it should be fine to use the same line for the other targets too, see [wiki/Configuration](https://github.com/cross-rs/cross/wiki/Configuration)
