### ISSUE TITLE
pkgconfig search path not defined for arm-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by kingosticks** [cross-rs/cross#1316]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports
- [X] This could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your issue

I'm trying to cross-compile with arm-unknown-linux-gnueabihf and hitting a pkgconfig search path issue. 

```
error: failed to run custom build command for `glib-sys v0.19.0 (https://github.com/gtk-rs/gtk-rs-core#8986eb97)`

Caused by:
  process didn't exit successfully: `/target/debug/build/glib-sys-9eb477152870afcb/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GLIB_2.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_arm-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_arm_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_arm-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_arm_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_arm-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_arm_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_arm-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_arm_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_arm-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_arm_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=`PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.56"` did not exit successfully: exit status: 1
  error: could not find system library 'glib-2.0' required by the 'glib-sys' crate

  --- stderr
  Package glib-2.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `glib-2.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'glib-2.0' found
  Package glib-2.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `glib-2.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'glib-2.0' found

```

If I login to the container I can see the .pc files exist but `PKG_CONFIG_PATH` isn't set. If I manually set it to "/usr/lib/arm-linux-gnueabihf/pkgconfig", my `cargo build` completes successfully. Looking at the docker images at [cross/docker](https://github.com/cross-rs/cross/tree/main/docker), everything except Dockerfile.arm-unknown-linux-gnueabihf
 is setting `PKG_CONFIG_PATH`. It was [briefly added](https://github.com/cross-rs/cross/commit/6d3eb7748d33153ba31c8c3b1161ef414259da4f) (strangely to to path /usr/lib/usr/arm-linux-gnueabihf/pkgconfig), only to be [removed shortly afterwards](https://github.com/cross-rs/cross/commit/5b9a77c2aa9f209fc9cd587ff89ba7318b87756b).
 
Was setting `PKG_CONFIG_PATH` supposed to be reverted like this? If so, how is `pkg-config` supposed to work in arm-unknown-linux-gnueabihf ?

### What target(s) are you cross-compiling for?

arm-unknown-linux-gnueabihf

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [X] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5 (37c681a 2023-07-17)

### Example

Cross.toml
```
[build]
pre-build = [
    "rm /etc/apt/preferences.d/all-packages",
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes libglib2.0-dev:$CROSS_DEB_ARCH libgstreamer1.0-dev:$CROSS_DEB_ARCH libgstreamer-plugins-base1.0-dev:$CROSS_DEB_ARCH"
]
```
1. `git clone --depth 1 -b main https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs.git`
2. `cd gst-plugins-rs`
3. `CROSS_CONFIG=/path/to/Cross.toml cross build --target arm-unknown-linux-gnueabihf --package gst-plugin-spotify`

### Additional information / notes

It builds with the other arm targets, for example `armv7-unknown-linux-gnueabihf`.

**Comment by Emilgardis** [comment]
I dont see any harm adding it back in. The reasoning was that it wouldnt be needed anymore, but I suppose that is not true if you're certain the library you retrieved with apt is armv6.

**Comment by kingosticks** [comment]
Ahh right yes of course, that does make sense. I forgot entirely that most don't install new packages on this platform. Would a PR be welcome for this? Otherwise I'm happy enough setting this in my own extra dockerfile.

**Comment by kingosticks** [comment]
Thanks! To now make use of this, is there a nightly image tag, or something ?

**Comment by Emilgardis** [comment]
Ideally you'd be able to use it straight away, but thanks to https://github.com/cross-rs/cross/pull/1208 I'm not able to merge prs where they build new main/edge images as they'd fail. But, we have a weekly CI job that does it, I've trigger it now https://github.com/cross-rs/cross/actions/runs/5954326633

**Comment by Emilgardis** [comment]
And done!
https://github.com/cross-rs/cross/pkgs/container/arm-unknown-linux-gnueabihf/121385772?tag=main

**Comment by kingosticks** [comment]
Thanks so much. Will take it for a spin.

**Comment by edgarriba** [comment]
hi, I'm having the same issue using the latest `aarch64`unknown-linux-gnu`. Is there any other solution for it ?

** https://github.com/cross-rs/cross/pkgs/container/aarch64-unknown-linux-gnu
