### ISSUE TITLE
Issue when building with `cross rustdoc`

### ISSUE THREAD

**Issue by makspll** [cross-rs/cross#1341]
Maintainers note: The issue was filed wrongly initially, the real issue is using `cross rustdoc`

### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When running 
```bash
cross +nightly-2023-07-16-aarch64-unknown-linux-gnu rustdoc --target=aarch64-unknown-linux-gnu -p bevy_asset@0.11.2  --  -Zunstable-options --output-format json
````
I get the following error:
```
[cross] warning: unable to get metadata for package
[cross] note: Falling back to `cargo` on the host.
qemu-aarch64: Could not open '/lib/ld-linux-aarch64.so.1': No such file or directory
```

If I use `+nightly-2023-07-16` by itself, it runs successfully but it fallbacks to cargo on host and the build clearly isn't being done on arm64.

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

0.2.5

**Comment by Emilgardis** [comment]
This is a current limitation with our images, all our current images run with platform = `linux/amd64`, not `linux/arm64`. If you need arm64 host support you need to make the image yourself, see [`target.TARGET.image.toolchain`](https://github.com/cross-rs/cross/wiki/Configuration#targettargetimage)

The tracking issue for overall aarch64 host support is https://github.com/cross-rs/cross/issues/751

In there there's also an example of how to use the feature

**Comment by makspll** [comment]
Hi I am not trying to run on an Arm64 host but to cross compile to Arm64 from x86

**Comment by Emilgardis** [comment]
Aha, I see!

The toolchain you picked is not valid, it should be `cross +nightly-2023-07-16-x86_64-unknown-linux-gnu ...`

in never versions of cross you'll get an error message

```
Note:
   Overriding the toolchain in cross is only possible in CLI by specifying a channel and optional date: `+channel[-YYYY-MM-DD]`.
   To override the toolchain mounted in the image, set `target.aarch64-unknown-linux-gnu.image.toolchain = "aarch64-unknown-linux-gnu"`

Suggestion: try `cross +1.65` instead
```

however, I just noticed that you're trying to use rustdoc! We don't support rustdoc as a command, not sure why though.

For now, use `cross doc` and set [env var `RUSTDOCFLAGS`](https://doc.rust-lang.org/rustdoc/unstable-features.html?highlight=environ#unstable-command-line-arguments)

**Comment by Emilgardis** [comment]
I think I'll explain a bit more so that it's totally clear what happened here initially!

cross uses a rust toolchain, like `nightly-x86_64-unknown-linux-gnu`, inside a docker container by mounting that toolchain from the system hosting the container engine. To compile for a specific target like `aarch64-unknown-linux-gnu`, rust specifies targets (see `rustup target list`). These targets are used to compile, with any "host" toolchain, for a specific target triplet. All cross does is setup a cross-compilation friendly environment so that tools needed to compile for that target is available.

**Comment by Emilgardis** [comment]
I've fixed the issue with rustdoc now hopefully, can you try it out with #1342

`cargo install cross --git https://github.com/cross-rs/cross --branch explain-fallback-fix-rustdoc`

**Comment by makspll** [comment]
Hey, thanks so much! Will try now

**Comment by Emilgardis** [comment]
hmm, i feel like there's some information missing here, can you post the full log? I'll try this myself later this weekend, is the project you're compiling from available? I guess maybe I can reproduce it with just a cargo.toml using bevy_asset@0.11.2

**Comment by Emilgardis** [comment]
oh also, please try a `cargo clean --target aarch64-unknown-linux-gnu` then run the command again, the fact that this produces a ice is interesting though

**Comment by Emilgardis** [comment]
oh and also! Generally, `cross` or really any cross compilation tool, isn't really needed when targeting another target, are you sure it doesn't just work with `cargo +nightly-2023-07-16 rustdoc --target=aarch64-unknown-linux-gnu -p bevy_asset@0.11.2 --  -Zunstable-options --output-format json`?

**Comment by makspll** [comment]
> hmm, i feel like there's some information missing here, can you post the full log? I'll try this myself later this weekend, is the 
 project you're compiling from public? I guess maybe I can reproduce it with just a cargo.toml using bevy_asset@0.11.2
Here is the full log: https://gist.github.com/makspll/c3058a54896dd3a8f78b6b654308e9bf

Yes the project is public, the issue and context I am needing this for can be found here: https://github.com/makspll/bevy_mod_scripting/pull/77

> oh and also! Generally, cross or really any cross compilation tool, isn't really needed when targeting another target, are you sure it doesn't just work with cargo +nightly-2023-07-16 rustdoc --target=aarch64-unknown-linux-gnu -p bevy_asset@0.11.2 --  -Zunstable-options --output-format json?
The reason I was using cross was because I was getting unexpected output from cargo. Turns out I didn't realise cargo would generate under a new directory in target, specifically `target/aarch64-unknown-linux-gnu` which caused me to use the old rustdoc json files and hence wrong output! I just assumed I needed some sort of emulation for this to work. But also I do think I need cross for running anything with a bevy dependency as it has some dependencies:
```rust
[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64 && apt-get -y update; apt-get -y install libasound2-dev:arm64 libudev-dev:arm64",
]
```

> oh also, please try a cargo clean --target aarch64-unknown-linux-gnu then run the command again, the fact that this produces a ice is interesting though

This solved it! it run the command successfully, and after correcting for the target directory everything worked as expected!
Thanks alot!

**Comment by Emilgardis** [comment]
awesome, then this is the good old issue #724 but rustdoc throwing an ICE, very nice

**Comment by makspll** [comment]
Ah I see, strange!
