### ISSUE TITLE
cross builds successfully but there are no target files

### ISSUE THREAD

**Issue by fr-an-k** [cross-rs/cross#1364]
The build succeeds but no target directory is created.
```
cross build --release --target aarch64-linux-android --verbose
```

"zero-configuration" means it creates and uses the target folder, correct?

I can see that the correct volumes are bound but no files are written even if I manually create the target directory; what's going on?

```
docker.exe run --userns host -e 'PKG_CONFIG_ALLOW_CROSS=1' -e 'XARGO_HOME=/xargo' -e 'CARGO_HOME=/cargo' -e 'CARGO_TARGET_DIR=/target' -e 'CROSS_RUNNER=' -e 'USER=frank' --rm --user 1000:1000 -v 'C:\Users\frank\.xargo:/xargo:z' -v 'C:\Users\frank\.cargo:/cargo:z' -v /cargo/bin -v 'C:\Users\frank\repos\rust-android-examples\na-mainloop:/project:z' -v 'C:\Users\frank\.rustup\toolchains\1.67.0-x86_64-unknown-linux-gnu:/rust:z,ro' -v 'C:\Users\frank\repos\rust-android-examples\na-mainloop\target:/target:z' -w /project -i -t ghcr.io/cross-rs/aarch64-linux-android:0.2.5 sh -c 'PATH=$PATH:/rust/bin cargo build --release --target aarch64-linux-android --verbose
```

It's run on Windows 11 with all the latest versions (except rust 1.67 instead of 1.68 because of #1222 ).

**Comment by Emilgardis** [comment]
this is most likely a docker problem

if you run 

```
docker run --rm -v 'C:\Users\frank\repos\rust-android-examples\na-mainloop\target:/target:z' ubuntu:20.04 mkdir /target/itworks
```

the container should create a folder `C:\Users\frank\repos\rust-android-examples\na-mainloop\target\itworks`

**Comment by fr-an-k** [comment]
Sorry I was accidentally looking in the wrong location.

**Comment by Emilgardis** [comment]
Awesome, feel free to reach out here or on our [matrix channel](https://matrix.to/#/#cross-rs:matrix.org) if you need any help :)
