### ISSUE TITLE
Any plan to support higher Ubuntu base image? say, Ubuntu 22.04 LTS?

### ISSUE THREAD

**Issue by leiless** [cross-rs/cross#1370]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I'm using Linux x86_64 host system with podman 3.4.4 to cross-compiling Windows x86_64 GNU exe binary.

But I've checked the `ghcr.io/cross-rs/x86_64-pc-windows-gnu:0.2.5` image, its base image is Ubuntu 18.04 LTS.
My Dockerfile is based on this one, some of the apt package version is outdated, if I wanna use more recent version, I have to upgrade the base image.

```bash
$ docker run -it --rm ghcr.io/cross-rs/x86_64-pc-windows-gnu:0.2.5 bash
root@1b78ce2842ed:/# cat /etc/os-release | grep VERSION
VERSION="18.04.6 LTS (Bionic Beaver)"
VERSION_ID="18.04"
VERSION_CODENAME=bionic

```

So, any plan to support higher version base image?

### What target(s) are you cross-compiling for?

x86_64-pc-windows-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [X] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5

**Comment by Emilgardis** [comment]
On the main branch, the images tagged `main`, use 20.04

We also have #973 to update to 22.04

To use these images you can install cross from the main branch `cargo install cross --git https://github.com/cross-rs/cross` or specify [`target.TARGET.image`](https://github.com/cross-rs/cross/wiki/Configuration#targettargetimage)
