### ISSUE TITLE
 cross build --target armv7-unknown-linux-gnueabihf   

### ISSUE THREAD

**Issue by yz-yz-yz** [cross-rs/cross#1388]
我想编译到这个ARMv7 平台 但是 它 报错？？？error: failed to run custom build command for `openssl-sys v0.9.96`

Caused by:
  process didn't exit successfully: `/target/debug/build/openssl-sys-15106401038d6091/build-script-main` (exit status: 101)
  --- stdout

**Comment by NobodyXu** [comment]
You need to either enable openssl-sys/vendored, or install openssl within the container cross is using.

**Comment by Emilgardis** [comment]
See https://github.com/cross-rs/cross/wiki/Recipes#openssl for more information
