### ISSUE TITLE
Investigate bindgen woes - "file not found"

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#1389]
Some (if not most?) `*-dev` packages on ubuntu dist only include headers in `/usr/include`, this means that the `BINDGEN_EXTRA_CLANG_ARGS_<target>=--sysroot=$CROSS_SYSROOT` that we set in our images means `bindgen` can't properly find these headers if the `*-sys`-crate doesn't use `pkg-config` probing.

`bindgen` errors with: `Unable to generate bindings: ClangDiagnostic("wrapper.h:1:10: fatal error: 'mylib.h' file not found\n")`

To solve this problem, there's two options, nr.1 requires a change in the `sys`-crate

## 1. Modify the `sys`-crate

Crates using bindgen for API generation can do the following

```rs
std::env::set_var("PKG_CONFIG_ALLOW_SYSTEM_CFLAGS", "1");
let library = pkg_config::probe_library("mylib").expect("Unable to probe `mylib`");
let bindings = bindgen::Builder::default()
    .clang_args(library.include_paths.iter().map(|path| format!("-I{}", path.to_string_lossy())))
    .header("wrapper.h")
    .parse_callbacks(Box::new(bindgen::CargoCallbacks))
    .generate()
    .expect("Unable to generate bindings");
```
## 2. modify `BINDGEN_EXTRA_CLANG_ARGS_<target>` to include `/usr/include`

(make sure to get the correct sysroot path and use the correct target names, `<target>` is lowercase snake_case target triple, `<TARGET>` is uppercase kebab-case target triple.)

```toml
# Cross.toml
[target.<TARGET>.env]
passthrough = ["BINDGEN_EXTRA_CLANG_ARGS_<target>=--sysroot=<path_to_target_sysroot> -idirafter/usr/include"]
```

## Going forward

I've filed https://github.com/rust-lang/rust-bindgen/issues/2701 to potentially make option 2 easier, as we then could just set `BINDGEN_EXTRA_CLANG_ARGS=-idirafter/usr/include` for all targets and all is well.

Can we solve this problem in our images? 

Related: https://github.com/rust-lang/rust-bindgen/issues/1247 for pkg-config with bindgen.

**Comment by Emilgardis** [comment]
> Can we solve this problem in our images?

Should we add `-I/usr/include` in all our `BINDGEN_EXTRA_CLANG_ARGS_<target>`s maybe? One risk I see with this is that we introduce contamination, where the header files could potentially be different for the host architecture and the target architecture.

**Comment by Emilgardis** [comment]
`BINDGEN_EXTRA_CLANG_ARGS_aarch64_unknown_linux_gnu=--sysroot=/usr/aarch64-linux-gnu -I/usr/include -v`

gives

```text
#include <...> search starts here:
 /usr/include
 /usr/include/clang/10.0.0/include
 $CROSS_SYSROOT/include
```

[clang says](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-I-dir)

> For C++ inputs, if there are multiple -I options, these directories are searched in the order they are given before the standard system directories are searched.


`BINDGEN_EXTRA_CLANG_ARGS_aarch64_unknown_linux_gnu=--sysroot=$CROSS_SYSROOT -nostdinc -I$CROSS_SYSROOT/include -I/usr/include` works, but disables the std, there's no way to reenable it... we need [`-ibuiltininc` (available on clang-11 and up](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-ibuiltininc) I think but that also doesn't to enable the clang includes

```text
#include <...> search starts here:
 $CROSS_SYSROOT/include
 /usr/include
```

**Comment by Emilgardis** [comment]
> Should we add `-I/usr/include` in all our `BINDGEN_EXTRA_CLANG_ARGS_<target>`s maybe? One risk I see with this is that we introduce contamination, where the header files could potentially be different for the host architecture and the target architecture. How does clang prioritize the include dirs, right to left?

I think `-idirafter/usr/include` is the way to do this, I don't see much hindering us from adding this to our images

**Comment by Emilgardis** [comment]
Some more investigating, pkg-config strips `-I/usr/include` as it's a system include path, setting `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1` resolves this, I've modified the code to reflect this. I think this is wanted behaviour for the `pkg_config` crate

**Comment by Emilgardis** [comment]
Another issue, should we really use `PKG_CONFIG_PATH`? From what I can gather, the expected thing to do is to use `aarch64-linux-gnu-pkg-config`

**Comment by ydirson** [comment]
> Some (if not most?) `*-dev` packages on ubuntu dist only include headers in `/usr/include`, this means that the `BINDGEN_EXTRA_CLANG_ARGS_<target>=--sysroot=$CROSS_SYSROOT`

I'm not entirely sure of the problem this issue is about, since not all containers use the same approach.  Since you mention using Ubuntu's `-dev` packages, I assume you're talking about containers for targets using `dpkg`'s foreign-architecture support, but then it seems to be the sysroot is just `/` so there should be no problem to start with.  So I'm basically confused :)

**Comment by Emilgardis** [comment]
Maybe I'm the one that is confused, we set the env var in https://github.com/cross-rs/cross/pull/707

I was under the impression that it was needed, but maybe it wasn't needed for every target, and only needed for android

**Comment by tniessen** [comment]
> `bindgen` can't properly find these headers if the `*-sys`-crate doesn't use `pkg-config` probing

@Emilgardis In my case, I'm using `bindgen` with some C header files that do not belong to any pre-installed library, so as far as I know, I cannot reasonably use `pkg-config`. However, with default configuration only, this results in errors such as `fatal error: 'stddef.h' file not found`. (The reason is that the Rust crate needs to be aware of the memory layout of some C data structures, but it does not actually link against any C library.)

This works just fine with the default toolchain/target, but cross-compiling without `cross` requires manual modifications of the include path. Is there a more elegant solution now that I'm trying to use `cross`?

**Comment by Emilgardis** [comment]
@tniessen short answer is no, cross wouldnt help with a more elegant solution, the solution would be equally applicable with or without cross. I dont think your specific example here is related to what this issue is about, but feel free to open a new issue with more information and maybe we can work something out

**Comment by Emilgardis** [comment]
I'll close this issue with #13671391
