### ISSUE TITLE
Some tests fails on i686-linux-android

### ISSUE THREAD

**Issue by malbarbo** [cross-rs/cross#140]
Test support for i686-linux-android was added in https://github.com/japaric/cross/pull/132. When the tests are run without qemu if fails with:

```
thread '<unnamed>' panicked at 'assertion failed: signal(libc::SIGPIPE, libc::SIG_IGN) != libc::SIG_ERR', /checkout/src/libstd/sys/unix/mod.rs:81:8
```

Running the tests with qemu allows the cross tests to pass, for this reason qemu is used. But the error still happens some times, we need to investigate why this happen.

**Comment by jamesmunns** [comment]
Hey @malbarbo, What would your suggested fix for this be? I'm not sure I fully grok the issue.

**Comment by malbarbo** [comment]
The target  i686-linux-android produces binaries that can be directly executed in an amd64 processor, but doing so fails with the reported message. I don't known why. Executing the binaries with qemu, works, but it sometimes fails with other errors.
