### ISSUE TITLE
Set `PKG_CONFIG_ALLOW_CROSS=1` inside our dockerfiles instead of on invocation of docker

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#1413]
We currently set `PKG_CONFIG_ALLOW_CROSS=1` here 

https://github.com/cross-rs/cross/blob/3fc18388a8f159a01bd592adcc523c1c6a163790/src/docker/shared.rs#L1038

This should be done inside the image, since some images may not have pkg-config properly setup.

**Comment by Emilgardis** [comment]
To fix this, above line should be removed and instead `PKG_CONFIG_ALLOW_CROSS=1` should be added to all [dockerfiles](https://github.com/cross-rs/cross/tree/main/docker) that include `PKG_CONFIG_PATH`

Those files can be found with 

`rg -l 'PKG_CONFIG_PATH=' -g 'Dockerfile.*'`

**Comment by Swiimmingly** [comment]
Hi, everything was provided pretty much but I fixed it I believe.
First time contributing so please let me know if something is wrong

**Comment by Emilgardis** [comment]
Fixed by #1415
