### ISSUE TITLE
Fix `*-solaris`

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#1424]
CI fails for the solaris targets:

[sparcv9-sun-solaris](https://github.com/cross-rs/cross/actions/runs/7703230077/job/20993307574) - ❌
[x86_64-sun-solaris](https://github.com/cross-rs/cross/actions/runs/7703230077/job/20993310725) - ❌

strangly, I've never been able to catch the error this throws, I think the log is too large and GHA fails. We should maybe check that everything is correctly downloading, as I've seen logs just mentioning syncing of a particular ubuntu/debian repo

**Comment by thirteenowls** [comment]
I was curious about this, so I ran the two CI jobs on a private fork, and they both failed by running out of disk space.
However, GitHub only shows those errors on the summary page, and the job pages only show logs that suddenly stop, making it easy to miss.
The logs for the last `*-solaris` CI runs in this repo have expired so I can't check, but could this be the issue?

Looking at [`solaris.sh`](https://github.com/cross-rs/cross/blob/main/docker/solaris.sh#L63-L80), it seems to try to install *all* packages that depend on `libc` (and more), which seems excessive.
