### ISSUE TITLE
Upgrade from ubuntu 20.04 to 22.04

### ISSUE THREAD

**Issue by 0xfourzerofour** [cross-rs/cross#1450]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

Any updates on when the cross base docker images are going to move from 20.04 to 22.04? I have some pretty annoying glibc errors downloading dependencies

e.g

```
bun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by bun)
```

I posted in the matrix channel but just doubling up here.

**Comment by Emilgardis** [comment]
There's an open pr to do this, and this comment still applies https://github.com/cross-rs/cross/pull/973#issuecomment-1452557539

The remaining tasks for 0.3.0 are found [here](https://github.com/cross-rs/cross/milestone/2)

Any and all help is appreciated

**Comment by 0xfourzerofour** [comment]
I will see if I can tackle some of these features, our cross platform builds at Alchemy are giving us some grief so it would be nice to get this going. Ill let you know how I go
