### ISSUE TITLE
Could we add gfortran support to our images?

### ISSUE THREAD

**Issue by Dirreke** [cross-rs/cross#1457]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [X] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

I'm working for a application with many math libs. And gfortran is always required.

It's not difficult to add it. For gnu, Add gfortran-${ARCH}-${SYSTEM}-gnu${ABI} is enough. And for musl, we can add `GCC_CONFIG += --enable-languages=c,c++,fortran` to `musl.sh` .

### Describe why this would be a good inclusion for `cross`

It's true that it will increase the size of the docker. But there's always gfortran in the cross-toolchain published by musl.cc or linaro. So I just think if we can add it to our image too. It will make cross docker more complete.

**Comment by Emilgardis** [comment]
for gnu, is it just a system package? Then couldn't it be done with [`pre-build`](https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#adding-dependencies-to-existing-images)?

For musl, I think I'd be fine with just enabling it.

**Comment by Emilgardis** [comment]
I'm fine with adding this to the images, it's n a way a very common compiler, and it's not too large or problematic. Feel free to open a PR making the changes neccessary!
