### ISSUE TITLE
Ability to override base image?

### ISSUE THREAD

**Issue by fuzzypixelz** [cross-rs/cross#1471]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

Is it reasonable to make the Docker images accept a `$BASE_IMAGE` argument that a user can override to something like ubuntu-16.04 (e.g. for compatibility with systems that require older versions of glibc).

**Comment by Emilgardis** [comment]
How would you use this? E.g what is the mechanism that switches base image? Does this only apply to our `build-docker-image`

We already have https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#custom-image

**Comment by Emilgardis** [comment]
I see, I don't think we'd be able to support this without many small fixes in many places, and 16.04 is not really maintained anymore. We will (eventually, far future) be merging all the pre-setup stuff into one base image, which would maybe help with your effort. See https://github.com/cross-rs/cross/pull/953

I'll close this issue as it's not something we want to do, if you want to have older glibc I'd recommend you to look into crosstool-ng, which we can use to support older libraries. There's no documentation about how to do it but see `cargo xtask configure-crosstool` and [one of the targets](https://github.com/cross-rs/cross/blob/35be2a968f43be945bc9ced4af41ec534c359b9e/docker/Dockerfile.arm-unknown-linux-gnueabihf#L15-L20) which uses that

**Comment by fuzzypixelz** [comment]
> I see, I don't think we'd be able to support this without many small fixes in many places, and 16.04 is not really maintained anymore. We will (eventually, far future) be merging all the pre-setup stuff into one base image, which would maybe help with your effort. See #953
> 
> I'll close this issue as it's not something we want to do, if you want to have older glibc I'd recommend you to look into crosstool-ng, which we can use to support older libraries. There's no documentation about how to do it but see `cargo xtask configure-crosstool` and [one of the targets](https://github.com/cross-rs/cross/blob/35be2a968f43be945bc9ced4af41ec534c359b9e/docker/Dockerfile.arm-unknown-linux-gnueabihf#L15-L20) which uses that

Thanks a lot! I'll look into the crosstool-ng option once I have the time and report my findings.

**Comment by Emilgardis** [comment]
Oh yeah! I forgot about zig also which is the obvious way to do it :)

https://github.com/cross-rs/cross/blob/main/docs/config_file.md#targettargetzig
