### ISSUE TITLE
Publish a new release 

### ISSUE THREAD

**Issue by demurgos** [cross-rs/cross#1475]
As of today, the latest release is [v0.2.5](https://github.com/cross-rs/cross/releases/tag/v0.2.5) from 2023-02-03, over a year ago. Since then there were many changes that are only available on `master`. Would it be possible to create a new release and publish precompiled binaries to GitHub please?

The current status requires building from source which adds some extra delay when preparing a build environment.

**Comment by Emilgardis** [comment]
please see https://github.com/cross-rs/cross/discussions/1290 and https://github.com/cross-rs/cross/issues/1356

the status is still the same but slowly getting there
