### ISSUE TITLE
Cross does not have an ARM64 platform docker image for v0.2.5 and main

### ISSUE THREAD

**Issue by metaclips** [cross-rs/cross#1487]
There's no docker image build for aarch64-linux since Cross v0.2.5 https://github.com/cross-rs/cross/pkgs/container/aarch64-unknown-linux-gnu/68145119?tag=0.2.5 as the only supported arch are `linux/amd64` and `unknown/unknown` which makes building on MacOS m1 slow or having to pull back to v0.2.4.

**Comment by Emilgardis** [comment]
This is a known issue, see https://github.com/cross-rs/cross/issues/1214#issuecomment-1452732222

We've never had images for native arm64, see https://github.com/cross-rs/cross/issues/751

**Comment by xpe** [comment]
From https://github.com/cross-rs/cross/issues/1214#issuecomment-1514493622 :

> For anybody else, to save you spending days looking for a solution here is how I solved it: `cargo install cross --git https://github.com/cross-rs/cross` Yep, update and it worked fine for me.

My understanding is that https://github.com/cross-rs/cross/issues/1214#issuecomment-1452732222 (linked above) will make cross-compilation on a macOS work even with a `cargo install cross` installation.
