### ISSUE TITLE
binary size 3x larger

### ISSUE THREAD

**Issue by Sibz** [cross-rs/cross#1504]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When building using cross, my binary size is significantly larger than when not.

cmd:
`cross build -r --target x86_64-pc-windows-gnu`
Run using docker in docker, my devcontainer using wsl on windows.

### What target(s) are you cross-compiling for?

x86_64-pc-windows-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [ ] Linux / BSD
- [X] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5

### Example

`cross build -r --target x86_64-pc-windows-gnu`
My binary built natively on a windows machine is 8mb
using cross its 23mb.

### Additional information / notes

Probably the difference between x86_64-pc-windows-msvc and x86_64-pc-windows-gnu targets

**Comment by Emilgardis** [comment]
Comparing binary sizes for -gnu and -msvc doesnt really make sense, msvc has a lot of dynamic linking, it also bundles debuginfo in a .pdb file.

See https://doc.rust-lang.org/cargo/reference/profiles.html for tuning artifacts, and https://github.com/johnthagen/min-sized-rust for more tips
