### ISSUE TITLE
Unable to pull docker images

### ISSUE THREAD

**Issue by fosskers** [cross-rs/cross#1508]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Myself and a colleague on another machine are unable to pull `cross`'s images from GHCR. Both a `cross build` and a manual `docker pull` result in errors like:

```
Unable to find image 'ghcr.io/cross-rs/x86_64-unknown-linux-musl:main' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/cross-rs/x86_64-unknown-linux-musl/manifests/main": denied: denied.
```

This happens on both our work network and on my home network. Has something recently changed regarding permissions necessary to pull images?

### What target(s) are you cross-compiling for?

x86_64-unknown-linux-musl

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5 (19be834 2024-05-17)

### Example

```
> cross build --package hello-world --release --target x86_64-unknown-linux-musl
```
`hello-world` is a local test project of ours. The error given is as shown above.

**Comment by fosskers** [comment]
As a workaround, another colleague who still had the image on his machine pushed it to a public location under a different name, which I proceeded to `docker pull` and retag as what cross was expecting:
```
> docker tag foo/the-image:main ghcr.io/cross-rs/x86_64-unknown-linux-musl:main
```

**Comment by Emilgardis** [comment]
have you logged in to ghcr previously and that token has recently expired? Try reauthing to ghcr.

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry

**Comment by fosskers** [comment]
That did it, thank you.
