### ISSUE TITLE
Basic command is not running from Readme

### ISSUE THREAD

**Issue by krishnaTORQUE** [cross-rs/cross#1515]
Basic command is not running from Readme. Even when docker is running.
I am on m2 macos (14.5)  & trying to cross compile for raspberry pi 4.

Command
```
cross build --target arm-unknown-linux-gnueabihf
```

Error
```
Unable to find image 'ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:0.2.5' locally
0.2.5: Pulling from cross-rs/arm-unknown-linux-gnueabihf
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
```

**Comment by Emilgardis** [comment]
See https://github.com/cross-rs/cross/issues/1214#issuecomment-1452732222

either pull the image with the platform specified: `CROSS_CONTAINER_OPTS="--platform linux/amd64"`
or use cross from the main branch: `cargo install cross --git https://github.com/cross-rs/cross`

duplicate #1214
