### ISSUE TITLE
Can you please bump version?

### ISSUE THREAD

**Issue by Kixunil** [cross-rs/cross#1522]
We have an issue testing with wine which is supposed to be fix by wine 9.0+ From my understanding, your scripts install the latest versions but since there wasn't a release for a while the published docker image has an old one, so just rebuilding should help.

Or if anyone can advise me if there's a super quick and easy way to publish my own image using this repository that could work too.

See https://groups.google.com/g/golang-nuts/c/Msg1USaNaqM for some details.

**Comment by Emilgardis** [comment]
See https://github.com/cross-rs/cross/blob/main/docs/config_file.md#targettargetimage

You can with that use the new images available under the `:main` tag.

So 
```toml
[target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:main"
```
should do the trick

Or, you could just install cross from the main branch

```
cargo install cross --git https://github.com/cross-rs/cross
```

**Comment by Kixunil** [comment]
Thanks a lot! I've studied the doc and all but didn't notice that `main` exists (I'm not familiar with docker anyway). Our CI works now. :)
