### ISSUE TITLE
Error Building with x86_64-pc-solaris

### ISSUE THREAD

**Issue by theory** [cross-rs/cross#1536]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I tried building a crate [on x86_64-pc-solaris](https://github.com/pgxn/meta/actions/runs/10290361270/job/28480170809), but it fails with:

```
  = note: /usr/bin/ld: warning: -z ignore ignored
          /usr/bin/ld: cannot find -lsendfile
          /usr/bin/ld: cannot find -llgrp
          /usr/bin/ld: cannot find -lsocket
          /usr/bin/ld: cannot find -lposix4
          collect2: error: ld returned 1 exit status
```

Not sure if there's something that needs updating in the switch from `x86_64-pc-solaris` or if there's something more I can install.

### What target(s) are you cross-compiling for?

x86_64-pc-solaris

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

0.2.5

### Example

* Fork https://github.com/pgxn/meta
* Uncomment these lines in `.github/workflows/build-and-release.yml`:

    ```yml
              # - os_name: solaris-amd64
              #   os: ubuntu-20.04
              #   target: x86_64-pc-solaris
              #   bin: pgxn_meta
              #   emoji: ☀️
    ```

* Push to trigger the workflow and examine the results

### Additional information / notes

It worked fine with 0.2.5 on my Mac; might it be something up with the configuration on the GitHub Ubuntu worker?

**Comment by Emilgardis** [comment]
Please see the warning in the build log

https://github.com/pgxn/meta/actions/runs/10290361270/job/28480170809#step:5:715

You're not using cross here. You're probably uding cross from the main branch locally

**Comment by theory** [comment]
Oh, I see. I presume this would start working with the next release then?
