### ISSUE TITLE
Upgrade the crosstool for the `loongarch64-unknown-linux-gnu` target

### ISSUE THREAD

**Issue by heiher** [cross-rs/cross#1538]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

In this example, the LoongArch compiler generates an `R_LARCH_64_PCREL` relocation for `1b - .`. Unfortunately, older binutils linker does not support `R_LARCH_64_PCREL` and merely issue a warning instead of failing, leading to incorrect values in the linked executable.

```rust
fn main() {
    unsafe {
        core::arch::asm!(
            r#"
            1:
            nop
            .pushsection jump_table,  "awR"
            .balign 8
            .quad 1b - .
            .popsection
            "#
        );
    }
}
```

### What target(s) are you cross-compiling for?

loongarch64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5 (7b79041 2024-07-11)

### Example

```sh
cross build --target=loongarch64-unknown-linux-gnu
```

**Comment by mcandre** [comment]
Rust 1.81.0 promotes loongarch (musl) to tier 2.

https://github.com/rust-lang/rust/releases/tag/1.81.0

**Comment by heiher** [comment]
> Rust 1.81.0 promotes loongarch (musl) to tier 2.
> 
> https://github.com/rust-lang/rust/releases/tag/1.81.0

I'll add support for the `loongarch64-unknown-linux-musl`.
