### ISSUE TITLE
Add to README that nightly is requeried to run xargo

### ISSUE THREAD

**Issue by malbarbo** [cross-rs/cross#154]
See https://github.com/japaric/cross/issues/152#issuecomment-343986389

**Comment by Dylan-DPC** [comment]
@malbarbo do you mind submitting a PR for this? sounds trivial :grinning:

**Comment by Alexhuszagh** [comment]
This is now [documented](https://github.com/cross-rs/cross#minimum-supported-rust-version-msrv).
