### ISSUE TITLE
mount docker socket during tests

### ISSUE THREAD

**Issue by ilteoood** [cross-rs/cross#1548]
Hi,
In my project I need the docker socket to be mounted in order to perform some tests.

Using cross from the CLI, how can I do that? I don't find any option to specify custom mounts to cross.

**Comment by Emilgardis** [comment]
you can add custom flags to the docker invocation with `CROSS_CONTAINER_OPTS="--mount=blabla"`
see https://github.com/cross-rs/cross/blob/main/docs/environment_variables.md for additional env vars
