### ISSUE TITLE
Exec format error when running tests

### ISSUE THREAD

**Issue by rnza0u** [cross-rs/cross#1550]
I get `Exec format error` when running tests for different targets:

- aarch64-apple-darwin
- x86_64-apple-darwin
- x86_64-windows-gnu

Compilation works.

The images i am using have the same architecture as the host (amd64). I installed the binfmt support anyway as described in the Wiki but of course it didn't change anything.

I checked the compiled files and they looked good. For example, when running with `aarch64-apple-darwin`, the executable file is indeed an arm64 executable :

```
me@computer:~/my-project$ file tests/target/aarch64-apple-darwin/release/deps/test-name-9ad0ee87c379002d
tests/target/aarch64-apple-darwin/release/deps/test-name-9ad0ee87c379002d: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
```

I don't understand why i get this error. I am not using any specific configuration.

What other issue could cause that ? maybe QEMU is not even used ?

**Comment by Emilgardis** [comment]
our darwin images don't support emulation, that's why it not working. for windows it should work because we spin up wine

**Comment by rnza0u** [comment]
@Emilgardis ok, thank you for the explanation.

my bad about Windows. it was another type of error, which is fixed now.
