### ISSUE TITLE
Target image tag error

### ISSUE THREAD

**Issue by my4ng** [cross-rs/cross#1551]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When following the documentation on cross config, the standalone tag name as the image value (as described [here](https://github.com/cross-rs/cross/blob/main/docs/config_file.md#targettargetimage) fails with error.

### What target(s) are you cross-compiling for?

x86_64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [X] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5

### Example

The `cross.toml` file is simply:

```
[target.x86_64-unknown-linux-gnu]
image = ":edge"
```

Command:

```
$ cross build --target x86_64-unknown-linux-gnu --release
Error: parsing reference ":edge": invalid reference format
```

**Comment by Emilgardis** [comment]
this syntax only works on newer releases, you'll need to install from the main branch.

`cargo install cross --git https://github.com/cross-rs/cross`
