### ISSUE TITLE
apt-get not work in dockerfile 

### ISSUE THREAD

**Issue by h3zh1** [cross-rs/cross#1552]
### Checklist

- [ ] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I tried to build the docker image locally, I used apt to download `g++-x86-64-linux-gnu` and `protobuf-compiler` etc. But these don't seem to take effect. Can I only define them in pre-build or .sh?
cargo build image:
![image](https://github.com/user-attachments/assets/be543d45-2617-400a-a6d9-5b11deb6736c)
the content in Dockerfile
![image](https://github.com/user-attachments/assets/13b14e43-4853-4e31-940e-e6086263c940)
But apt cannot find it
![image](https://github.com/user-attachments/assets/c36dfff6-4d13-4786-9b99-2c9330944afa)

### What target(s) are you cross-compiling for?

x86_64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [X] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5 (d8631fe 2024-08-17)

**Comment by Emilgardis** [comment]
I'm not sure what these screenshots are supposed to show. Where is the installation logs? Why is `RUN /xargo.sh` underlined?

**Comment by h3zh1** [comment]
Sorry, my picture is not particularly accurate. The underline is to show that `RUN apt...` is not executed under cargo. 
pic1:  I pulled the image from ghcr.io and ran apt list to find it. I couldn't find the corresponding package https://github.com/cross-rs/cross/blob/main/docker/Dockerfile.x86_64-unknown-linux- gnu#15
![image](https://github.com/user-attachments/assets/edc62d8a-669b-40b1-9350-37090e7cfea0)
pic2: I re-run `cargo build-docker-image x86_64-unknown-linux-gnu --tag latest --no -cache`, the new screenshot is as follows
![image](https://github.com/user-attachments/assets/f33b2289-8885-4355-88ca-22caa7033689)

**Comment by Emilgardis** [comment]
the image built with `cargo build-docker-image` is tagged with `:local`, not `:main`
There's also some confusion here about what Dockerfile `cargo build-docker-image x86-64-unknown-gnu` uses, it actually uses `Dockerfile.native` when target=host

**Comment by h3zh1** [comment]
I hope you read my narrative carefully, the first picture is me pulling the latest image on a Linux instead of my local build

**Comment by h3zh1** [comment]
When the target is "x86_64-unknown-linux-gnu", Dockerfile.native is loaded. 
But when the target is "i686-unknown-linux-gnu", `Dockerfile.i686-unknown-linux-gnu` is loaded correctly.
![image](https://github.com/user-attachments/assets/13f142a6-6f4f-4a6c-a6dc-f1ecb426352f)

**Comment by Emilgardis** [comment]
Yes, that is not a problem, it's supposed to be that way.

I'm not sure what this issue is about anymore, can we close it?

**Comment by h3zh1** [comment]
Now I understand the usage, but loading Dockerfile.native is a little uncomfortable when I build image for "x86_64-unknown-linux-gnu" locally. Thanks, we can close.

**Comment by Emilgardis** [comment]
To explain a bit, the reason .native is used is because we want to support using the images for other platforms. On x86_64-unknown-linux-gnu we cant install `libc6-dev-amd64-cross`, we just install `libc6`, so to make it easy, when image platform=target, we switch to .native
