### ISSUE TITLE
CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS is unused key(s)

### ISSUE THREAD

**Issue by xdestiny110** [cross-rs/cross#1558]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Cross.toml
```
[target.x86_64-unknown-linux-musl]
image = "musl-openssl:1.0"
CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS = ["-C target-feature=-crt-static"]
```
When I use `cross build --target x86_64-unknown-linux-musl --release`, it says
```
[cross] warning: found unused key(s) in Cross configuration
 > target.x86_64-unknown-linux-musl.cargo_target_x86_64_unknown_linux_musl_rustflags
```
How can I setup rustflags in order to compile cdylib in musl?

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [X] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5 (d8631fe 2024-08-17)

**Comment by Emilgardis** [comment]
Just set the environment variable `RUSTFLAGS` like normal!
