### ISSUE TITLE
Support for more emerging target platforms

### ISSUE THREAD

**Issue by mcandre** [cross-rs/cross#1575]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom image](https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#custom-images) (optional)

### Describe your request

Rust 1.28.0 promotes even more target platforms up the tier ladder.

https://github.com/rust-lang/rust/releases/tag/1.82.0

### Describe why this would be a good inclusion for `cross`

Assist Rust developers with making it super easy to support a wide range of different runtime platforms.

Steal thunder from Go's builtin cross compilation.

**Comment by Emilgardis** [comment]
Going to close this issue if thats ok with you. This will always be a goal of cross. I'd prefer one issue per new target. Also, only the tier 2 targets should be added here, but the t3 targets can be supported too via cross-toolchains.
