### ISSUE TITLE
Support x86_64-unknown-linux-gnu using Intel sde emulation

### ISSUE THREAD

**Issue by gnzlbg** [cross-rs/cross#159]
See https://github.com/gnzlbg/stdsimd/commit/93cc2500b0ca8d55e3ad08b0c25225f1f50ba496

**Comment by Alexhuszagh** [comment]
It looks like this will be doable, and we can distribute images containing it if desired, as it uses Intel's [Simplified Software License](https://www.intel.com/content/www/us/en/developer/articles/license/end-user-license-agreement.html), which is an MIT-like license.
