### ISSUE TITLE
build-std is not passing to cargo if falling back to host

### ISSUE THREAD

**Issue by zonyitoo** [cross-rs/cross#1590]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I was trying to build for target `mips-unknown-linux-musl` with `cross` with latest master. Build with `Cross.toml` setting:

```toml
[target.mips-unknown-linux-gnu]
build-std = ["std", "panic_abort", "proc_macro"]
```

But no `-Zbuild-std=std,panic_abort,proc_macro` in the final command line.

### What target(s) are you cross-compiling for?

mips-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5 (4090bec 2024-10-15)

### Example

```
$ cross build --target "mips-unknown-linux-musl" --bin ssservice --features "full-extra" --release --verbose
+ cargo metadata --format-version 1 --filter-platform mips-unknown-linux-musl --features full-extra
[cross] warning: `cross` does not provide a Docker image for target mips-unknown-linux-musl, specify a custom image in `Cross.toml`.
[cross] note: Falling back to `cargo` on the host.
+ cargo build --target mips-unknown-linux-musl --bin ssservice --features full-extra --release --verbose
       Fresh unicode-ident v1.0.14
   Compiling cfg-if v1.0.0
... OTHER UNRELATED LOGS...
```

**Comment by Emilgardis** [comment]
I'm not sure if this is is what should happen or not. Could you explain why this is a problem?

**Comment by zonyitoo** [comment]
As a user, I would expect that when I run `cross`, it should be consistent for all targets.

Parameters that are passing from command line arguments will apply to builds that are running in both container and host. It should be consistent for parameters in `Cross.toml`.

**Comment by Emilgardis** [comment]
But this is an error, the error being that you've not setup cross correctly. This will eventually become a hard error without a fallback.

**Comment by zonyitoo** [comment]
Em, Ok. If there will be no fallback, it is Ok. But if there is a fallback, behavior should be kept consistent.

**Comment by Emilgardis** [comment]
The start of removing the fallback was done in #661, I do see thought that I've not documented the intent of fully removing the fallback. So I've created #1591  now
