### ISSUE TITLE
New Rust 1.83 targets

### ISSUE THREAD

**Issue by mcandre** [cross-rs/cross#1592]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom image](https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#custom-images) (optional)

### Describe your request

Per https://github.com/rust-lang/rust/releases/tag/1.83.0

### Describe why this would be a good inclusion for `cross`

Cross does an excellent job of managing complex compiler toolchains. Looking forward to supporting more of the available Rust targets. I believe Rust application users deserve best in class portable software.

**Comment by Emilgardis** [comment]
Im closing this with the same reasoning i used to close https://github.com/cross-rs/cross/issues/1575
