### ISSUE TITLE
No error on unsupported target

### ISSUE THREAD

**Issue by vorner** [cross-rs/cross#167]
If I choose a supported target (let's say `cross build --target=aarch64-unknown-linux-gnu`), everything works like charm ‒ it automatically downloads the std for that target, downloads the docker image and builds it.

However, if I choose an unsupported target (`aarch64-unknown-linux-musl`), it just tries to call cargo without any complaint. Then of course cargo complains:

```
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-unknown-linux-musl` target may not be installed
```

I'd expect to see one of:
* A message that such target is not supported
* A failed attempt at installing the target's std or the docker image

**Comment by Alexhuszagh** [comment]
We could possibly warn if `rust-std-${triple}`  isn't installed for the target and add an additional warning for that. This way, we could warn that the desired triple may not be supported. We should likely only do this on an error and if we're using a built-in target, to avoid incurring overhead or warning incorrectly if they're using `xargo` or `-Z build-std`
