### ISSUE TITLE
cross clippy fails

### ISSUE THREAD

**Issue by gnzlbg** [cross-rs/cross#176]
See https://travis-ci.org/gnzlbg/slice_deque/jobs/335220367#L1408

It seems that `cross clippy` works fine for the library and tests, but when trying to scan the benchmarks clippy fails to link.

**Comment by Alexhuszagh** [comment]
This no longer replicates as of the latest main: the following works (it fails for other reasons, but those are due to compile errors in the library):

```bash
$ git clone https://github.com/gnzlbg/slice_deque
$ cd slice_deque
$ cross +nightly clippy --tests --benches --target aarch64-unknown-linux-gnu --verbose
```

Current versions used are:
- cross 0.2.2 (48d2b7b 2022-06-25)
- cargo 1.63.0-nightly (39ad1039d 2022-05-25)
