### ISSUE TITLE
sparc64-unknown-linux-gnu fails

### ISSUE THREAD

**Issue by gnzlbg** [cross-rs/cross#177]
With error ([see here](https://travis-ci.org/gnzlbg/slice_deque/jobs/335226316#L549)): 

```shell
thread '<unnamed>' panicked at 'assertion failed: signal(libc::SIGPIPE, libc::SIG_IGN) != libc::SIG_ERR', libstd/sys/unix/mod.rs:85:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `qemu-sparc64 /target/sparc64-unknown-linux-gnu/release/deps/slice_deque-5da7fc08593c2b4e` (signal: 4, SIGILL: illegal instruction)
```

It doesn't look like cross tests are periodically run against travis (e.g. every 24-h), is that so? If so running the test suite periodically might help discover breakage introduced upstream.

**Comment by malbarbo** [comment]
The same error for i686-android https://github.com/japaric/cross/issues/140

**Comment by gnzlbg** [comment]
I've reported this upstream: https://github.com/rust-lang/rust/issues/55204

**Comment by Alexhuszagh** [comment]
This doesn't reproduce anymore as of cross 2f24bd4a81fcb375bc0acf9d0aa6a80d8f4123a0.

Sample code demonstrating it works is as of Rust 1.61.0 stable.

```bash
tmp_dir=$(mktemp -d)
cd "$tmp_dir"
git clone https://github.com/cross-rs/cross
cd cross
# checkout specific version known to work: latest commit on main tested.
git checkout 2f24bd4a81fcb375bc0acf9d0aa6a80d8f4123a0
cargo build

cd ..
git clone https://github.com/gnzlbg/slice_deque
cd slice_deque
"$tmp_dir"/cross/target/debug/cross test --target sparc64-unknown-linux-gnu

cd ~
rm -r "$tmp_dir"
```

All the tests pass, suggesting the issue has been fixed upstream.
