### ISSUE TITLE
Add sanitizer support to cross

### ISSUE THREAD

**Issue by gnzlbg** [cross-rs/cross#178]
Instead of going through `xargo` it would be great if `cross` could, at least for `x86_64-unknown-linux-gnu`, compile projects with a `std` library compiled with sanitizer support and optionally also run the tests with sanitizers enabled.

**Comment by jamesmunns** [comment]
Hey @gnzlbg, that sounds like a good idea. If you have an idea of how to implement it, let me know! I think you might need to wait until https://github.com/japaric/cross/pull/131 lands, since cross currently uses the host's Rust toolchain.

For now if your host system is using a version of `std` with sanitizer support, cros should use it.

**Comment by gnzlbg** [comment]
So one could compile std with sanitizer support using `xargo`, upload a docker image containing that, and expose it via `cross` API. Maybe as part of the target triple `x86_64-unknown-linux-gnu-msan` or as a flag in the config file.

**Comment by japaric** [comment]
> So one could compile std with sanitizer support using xargo, upload a docker image containing that, and expose it via cross API. 

if you put a std binary in the Docker image that std image will *only* work with a toolchain whose version is the exact same as the toolchain used to compile the std binary.

A more flexible solution that already works today is make Cross use Xargo to cross compile std with the sanitizer stuff enabled. You can set `target.$TARGET.xargo` to `true` in the Cross.toml and Cross should do that if the Docker image has a Xargo binary in it -- I *think* all Docker images do but haven't checked.

**Comment by Alexhuszagh** [comment]
This is now possible via `cross rustc` and `-Zbuild-std`:

```bash
$ cross +nightly rustc --target x86_64-unknown-linux-gnu -Zbuild-std -- -Zself-profile -Zsanitizer=leak
```

Currently, we should be able to support `CARGO_TARGET_${TARGET}_RUSTFLAGS`, however, we have another complicating issue in #903.
