### ISSUE TITLE
Looking for maintainers for the Cross and Trust projects

### ISSUE THREAD

**Issue by japaric** [cross-rs/cross#183]
Hey all,

As the GitHub activity of this repo evidences I have not had time to properly deal with the issues
and PRs that have been opened in the past months. Yet both Cross and [Trust] are used in the CI
systems of several Rust projects.

[Trust]: https://github.com/japaric/trust

I'd like to request your help maintaining these two projects -- I don't want to continue being
the development bottleneck.

If you'd like to become a maintainer leave a comment indicating which project you would like to help
with.

Thanks!

cc @jamesmunns @gnzlbg @malbarbo @Susurrus you might be interested

More info:

- Cross makes cross compilation easy: `cross build --target arm-unknown-linux-gnueabi` and you are done.
- Cross also makes multi platform testing easy. `cross test --target arm-unknown-linux-gnueabi` and you are done.
- Trust is a CI template (Travis CI / AppVeyor) that uses Cross to build, test and produce binary releases of a Rust program for a bunch of different platforms like Linux (lots of different archs), Windows and macOS.
- Cross makes heavy use of Docker so you should be familiar with Docker to be able to review PRs
- Cross also uses QEMU to execute non native binaries when testing so QEMU knowledge is welcome
- To review Trust PRs you should be familiar with Travis CI and/or AppVeyor configuration files.
- Even if you are not an expert in Docker, QEMU, Travis CI or AppVeyor you can still help us triage issues!
- The immediate roadmap for Cross is:
  - Support QEMU *system* mode when running non-native binaries. The stdsimd project would make use of Cross if it supported this. See PRs #153 and #166 
  - Support Cross on non-Linux hosts. Right now Cross only supports x86_64 Linux as a host. See PR #131

**Comment by gnzlbg** [comment]
@japaric I can help with cross (running tests for PRs and so on) but I am not experienced enough to be a maintainer. @malbarbo has my full support.

**Comment by jamesmunns** [comment]
@japaric I can help with cross. I think I should be familiar enough to be a maintainer.

**Comment by japaric** [comment]
Thanks @jamesmunns! I've sent you a collaborator invite.

**Comment by Dylan-DPC** [comment]
@japaric Even though i haven't used them I can help you with it.

**Comment by malbarbo** [comment]
Hey @japaric, thanks for the invitation. Thanks @gnzlbg  for the support. Thanks @jamesmunns for assuming the maintaining of cross, it is a very important project for the rust ecosystem.

I would love to help maintaining cross, but I cannot assume such responsibility right now. But I can work to make https://github.com/japaric/cross/pull/153 and https://github.com/japaric/cross/pull/166 land. 

@jamesmunns can you take I look at https://github.com/japaric/cross/pull/153 so we can move it forward?

**Comment by japaric** [comment]
Sorry for not answering until now.

@Dylan-DPC Thanks! I have sent you a collaborator invite to both Cross and Trust.

@malbarbo Thanks for considering collaborship, and thanks for all the work on Cross you have been doing! :heart:

**Comment by brainstorm** [comment]
I worked as a [maintainer of dockcross](https://github.com/dockcross/dockcross/pulls?q=is%3Apr+author%3Abrainstorm+is%3Aclosed) in the past.

Since I'm seeing that #452 is taking a bit too get reviewed/merged, I'm happy to help out a bit if people don't mind? :)

Cheers!

**Comment by therealprof** [comment]
@brainstorm We can always use more people in our teams. If you would like to submit your candidacy to join, please check out https://github.com/rust-embedded/wg/blob/master/rfcs/0136-teams.md#adding-new-members

**Comment by Alexhuszagh** [comment]
Trust seems to be in archive mode (no commits for 3 years), and we have #574 that has superseded this.
