### ISSUE TITLE
Support same android ndk versions as rust-lang/rust and rust-lang/libc

### ISSUE THREAD

**Issue by gnzlbg** [cross-rs/cross#195]
`cross` currently targets android ndk version 21. The following versions are targeted by Rust and libc:

* `rust-lang/rust`:

   * [ ] `arm-android`: NDK arm 15c
   * [ ] `armv7-android`: NDK arm 14
   * [x] `aarch64-android`: NDK arm64 21

* `rust-lang/libc`:

   * [ ] `arm-android`: NDK arm 15b
   * [ ] `armv7-android`: NDK arm 15b
   * [ ] `aarch64-android`: NDK arm64 15b

It would be nice if we could add an option to cross to let users specify the android NDK version. Or if we would at least support two different NDK versions natively (e.g. by providing docker images for both): latest (e.g. version 21), and rustc (same versions as rust-lang/rust).

This would be a pre-requisite for using `cross` as the testing framework for libc and other `rust-lang` /`rust-lang-nursery` components like `stdsimd`, `jemallocator`, etc.

**Comment by flxo** [comment]
@gnzlbg Where can I find the exact Android/NDK API levels used by Rust and libc?

**Comment by flxo** [comment]
I found in the [libc CI](https://github.com/rust-lang/libc/blob/master/ci/android-install-ndk.sh) a hint that master currently uses *r21d* and API level *28*.
