### ISSUE TITLE
Support path to Dockerfile in Cross.toml

### ISSUE THREAD

**Issue by gnzlbg** [cross-rs/cross#196]
Currently one can only provide an `image:tag`  in the `Cross.toml` to use other docker images, which means that one has to build the images first, which can be a pain to do in CI. 

It would be great if one could provide a path to a `Dockerfile` instead (or the docker context directory), so that `cross ` would build this image for you, and use it.

**Comment by jamesmunns** [comment]
I'm happy to help point the way for someone if they would like to tackle this. I think this should be reasonable to implement for someone familiar with Docker.

**Comment by Dylan-DPC** [comment]
@gnzlbg can you go ahead and submit a PR? we will help you out if needed. If not possible I'll try and do it.

**Comment by gnzlbg** [comment]
Does the following make sense?

* 1. add a `context` method to `Toml` https://github.com/japaric/cross/blob/master/src/main.rs#L470 that is similar to `image` but reads a `context = path/to/folder` where `folder` contains a `Dockerfile`. Update image and context to check that only one of both values is present
* 2. add an `or_else` call here in case `image()` returns none that calls `context`. If there is a context path, then just `docker build ...` the path, giving it a generic image name (e.g. `cross-image-${TARGET}:0.1` or similar), and returning the generic image name

And... that would be it? Does it make sense to "clean up" the image on exit? Maybe the generic image name should have the path of the current directory hard-coded or something?

**Comment by gnzlbg** [comment]
I've sent a PR, but I don't know how `cross` is tested, nor how to add tests for this. I would expect that, since `cross` is a CLI app, that it would be using something like `assert_cli` to test its behavior, but it seems that's not the case.

**Comment by Alexhuszagh** [comment]
This is done now that pre-build hooks are implemented (in #678).
