### ISSUE TITLE
ld i386 is incompatible with i386:x86-64 on i{586,686}-unknown-linux-gnu

### ISSUE THREAD

**Issue by gnzlbg** [cross-rs/cross#197]
I am using `cross` to build a library with a C dependency (the `jemallocator` crate, see this PR: https://github.com/alexcrichton/jemallocator/pull/42 ), and am having some issues with the `i{586,686}-unknown-linux-gnu` build bots:

* https://travis-ci.org/gnzlbg/jemallocator/jobs/373899242
* https://travis-ci.org/gnzlbg/jemallocator/jobs/373899243

In both cases, the error is preceded by a bunch of `ld` errors:

```shell
/usr/bin/ld: i386 architecture of input file `src/jemalloc.pic.o' is incompatible with i386:x86-64 output
```

I find this weird because the `i686-unknown-linux-musl` build bots work just fine:

* https://travis-ci.org/gnzlbg/jemallocator/jobs/373899244

Am I doing something wrong, or is some wrong version of some cross compilation tool being picked up by cross for these build bots?

**Comment by gnzlbg** [comment]
Also it seems that `make check` for the jemalloc tests fails under `cross` with:

```shell
=== test/unit/a0 ===
test/unit/a0: 1: test/unit/a0: Syntax error: "(" unexpected
```

which is weird on its own, but that's maybe due to a different issue.

**Comment by Alexhuszagh** [comment]
This doesn't reproduce anymore building `bzip2-rs`, a relatively simple build system with a C dependency. Neither does [rust-cpp-hello-world](https://github.com/cross-rs/rust-cpp-hello-word).

**Comment by Alexhuszagh** [comment]
This no longer replicates, and works (with the exception of a floating point bug, which is unrelated (for `i686-unknown-linux-gnu`) using the same logic as [here](https://github.com/cross-rs/cross/issues/221).
