### ISSUE TITLE
docker images should include basic utilities for building C programs

### ISSUE THREAD

**Issue by gnzlbg** [cross-rs/cross#203]
In some issues like #145 it was mentioned that it would be nice if the docker images would include basic utilities to build C programs, like:

* automake 
* libtool 
* m4

I'd add 

* autoconf
* cmake
* git

Taking a look at `stdsimd` and `libc` we have that they also use:

* make
* file

**Comment by mpapierski** [comment]
Hey,

I'd second this. Adding `git` would be very useful addition. Many programs use something similiar to `git rev-parse HEAD` as part of their build.rs script.

**Comment by ryankurte** [comment]
Thanks for the suggestions! Seems reasonable to me.

At the moment all the docker images are independently managed, I think we probably need to consider refactoring to use a shared base image with common tools before adding much more (cc. @japaric for your thoughts?)

**Comment by gnzlbg** [comment]
I've submitted a PR to address this: #226

**Comment by Alexhuszagh** [comment]
All Docker images now container:
- gcc
- g++
- make
- cmake
- libtool
- automake
- autoconf
- pkg-config
- m4
- git
- file
