### ISSUE TITLE
[Size improvement] Use Alpine as the base Docker image whenever possible

### ISSUE THREAD

**Issue by danielhenrymantilla** [cross-rs/cross#205]
As seen in the [rust-musl-builder](https://github.com/emk/rust-musl-builder#making-tiny-docker-images-with-alpine-linux-and-rust-binaries) repository, it should be possible to use Alpine as the base Docker image instead of Ubuntu,

in order for Cross to **pull tiny images (less than 100 MB !)**

**Comment by Alexhuszagh** [comment]
I don't think this is a good idea for the following reasons:
1. Ubuntu 20.04 images are ~72MB (substantially smaller than Ubuntu 16.04)
2. This gives us easy access to Debian and Ubuntu repositories, and a glibc-based image.
3. Alpine images may be significantly smaller (~3MB), but with all the dependencies required to use Cargo (libcc, libmusl-dev), the Rust install, our common dependencies (`g++`, `cmake`, `git`) and more, our images are already quite large, so ~100MB is very little when our smallest images are ~1.2GB and our larger ones ~3.6GB.
4. It's a breaking change with little benefit.

**Comment by Emilgardis** [comment]
Side-note, using alpine with cross is quite achievable for end-users, especially with `pre-build`/`dockerfile` to install libmusl-dev and gcompat (and whatever else is needed) and further improved on with #817 to use an actual `musl` rust toolchain
