### ISSUE TITLE
Syntax error "("

### ISSUE THREAD

**Issue by gnzlbg** [cross-rs/cross#221]
When trying to run `jemalloc`'s tests under `cross` in travis I get the following errors in some architectures:

```shell
[jemalloc-sys 0.2.0] === test/unit/a0 ===
[jemalloc-sys 0.2.0] test/unit/a0: 1: test/unit/a0: Syntax error: "(" unexpected
[jemalloc-sys 0.2.0] 
[jemalloc-sys 0.2.0] === test/unit/arena_reset ===
[jemalloc-sys 0.2.0] test/unit/arena_reset: 1: test/unit/arena_reset: m�@8: not found
[jemalloc-sys 0.2.0] test/unit/arena_reset: 1: test/unit/arena_reset: ELF��@@,H�D@: not found
[jemalloc-sys 0.2.0] test/unit/arena_reset: 2: test/unit/arena_reset: Syntax error: "(" unexpected
```

I am unsure about why this is the case - maybe something in the shell of the docker containers is off ?. I've disabled running jemalloc's tests on all of these architectures on `jemallocator`/`jemalloc-sys` CI.  

To reproduce, under linux, write:

```sh
git clone https://github.com/alexcrichton/jemallocator
cd jemallocator
TARGET=aarch64-unknown-linux-gnu ci/run.sh 
```

**Comment by gnzlbg** [comment]
@malbarbo are the `build.rs` scripts run under qemu ?

**Comment by Alexhuszagh** [comment]
This no longer replicates, using the following example with Rust 1.61.0 (stable):

```bash
$ git clone https://github.com/tikv/jemallocator
$ cd jemallocator
$ git submodule update --init --remote
```

I then replaced all instances of `cargo` in `ci/run.sh` with `"${cargo}"`, which defaults to `cargo` (can't use `CARGO` due to a bug in 0.2.2 that has since been patched), and then ran:

```bash
$ cargo=cross TARGET=x86_64-unknown-linux-gnu ci/run.sh
```

All tests pass.
