### ISSUE TITLE
Darwin targets

### ISSUE THREAD

**Issue by mcandre** [cross-rs/cross#223]
Pls.

**Comment by gnzlbg** [comment]
I don't think it is easily possible to emulate `MacOSX` on Linux - maybe with qemu and a disk image, but since the disk images are proprietary, i don't think we can include them here.

**Comment by mcandre** [comment]
I have heard this is now possible with osxcross, though I have not tried it myself.

**Comment by mogenson** [comment]
I've had success cross compiling cargo projects with the osxcross toolchain via this tutorial: https://www.reddit.com/r/rust/comments/6rxoty/tutorial_cross_compiling_from_linux_for_osx/

**Comment by mcandre** [comment]
Would it make sense for cross to add a dependency on osxcross? From where I sit, it would be ideal if Rust developers could use a single tool like cross to generate all their different platform ports.

**Comment by Alexhuszagh** [comment]
Closed in #841. A full description on how to use these images is described [here](https://github.com/cross-rs/cross/pull/480#issuecomment-1164982609).
