### ISSUE TITLE
GLIBC 2.15 is too new

### ISSUE THREAD

**Issue by siscia** [cross-rs/cross#249]
Hi all,

I know most of you will hate me for this, but GLIBC 2.15 is too new.

A lot of server still run Centos7 (some still Centos6 but that is another issue) that comes with GLIBC 2.14 It is not a mere convenienve since several people asked me to dowgrade my own software for this reason.

Is there any way to use cross to for linking to GLIBC 2.14

I am talking of the target: `x86_64-unknown-linux-gnu` and `armv7-unknown-linux-gnueabihf`

**Comment by briansmith** [comment]
@siscia In this kind of situation, why not use the `x86_64-unknown-linux-musl` and `armv7-unknown-linux-musleabihf` targets? Then you don't have to worry about libc.

**Comment by siscia** [comment]
@briansmith Thanks for the feedback. Actually, because I need to build a "cdylib" and it seems like it is not supported for those targets.

**Comment by Alexhuszagh** [comment]
This doesn't seem to be possible using our pre-built images (CentOS7 now uses glibc 2.17, and does not provide older libc versions), and probably would require building from source (unless you can find a mirror for CentOS 6). This should be done in a custom image, and would require building the toolchain from source (and therefore a lot of work), when we currently support a libc released a little over 9 years ago.
