### ISSUE TITLE
Set NDK_HOME

### ISSUE THREAD

**Issue by ArtemGr** [cross-rs/cross#256]
`rust-secp256k1` [wants](https://github.com/paritytech/rust-secp256k1/blob/ccc06e7480148b723eb44ac56cf4d20eec380b6f/build.rs#L69) `NDK_HOME` variable to be set when building it for Android:

```
cd /tmp
git clone --depth=1 https://github.com/paritytech/rust-secp256k1.git
cd rust-secp256k1/
cross build --target=armv7-linux-androideabi

    Updating crates.io index
  Downloaded rand v0.4.6
  Downloaded rand_core v0.3.1
  Downloaded fuchsia-cprng v0.1.1
  Downloaded clippy v0.0.302
  Downloaded rand_core v0.4.0
  Downloaded byteorder v1.3.1
  Downloaded rdrand v0.4.0
  Downloaded 7 crates (144.3 KB) in 1.28s
   Compiling libc v0.2.48
   Compiling arrayvec v0.4.10
   Compiling cc v1.0.29
   Compiling cfg-if v0.1.6
   Compiling nodrop v0.1.13
   Compiling rand v0.4.6
   Compiling eth-secp256k1 v0.5.7 (/project)
error: failed to run custom build command for `eth-secp256k1 v0.5.7 (/project)`
process didn't exit successfully: `/target/debug/build/eth-secp256k1-77b728ef084ab509/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'NDK_HOME is not set: NotPresent', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

Looking at the scripts at https://github.com/rust-embedded/cross/blob/3502de435ba5aae4c4eb88f9fe3c5a78ccd6007b/docker/android-ndk.sh and https://github.com/rust-embedded/cross/blob/ea1dc3f57e014b3b5d77a5bb4187b9f9c73d5fc9/docker/armv7-linux-androideabi/Dockerfile I don't see the NDK location shared. And it makes sense to share it in case the compiled packages would want to check the NDK version, etc. So why not share it as `NDK_HOME`?

**Comment by reitermarkus** [comment]
Sounds reasonable, can you submit a PR for this?

**Comment by ArtemGr** [comment]
We're using a workaround
```
[build.env]
passthrough = [
  "NDK_HOME",
  "RUST_BACKTRACE"
]
```
so nothing to make a PR from at the moment.

**Comment by Alexhuszagh** [comment]
There doesn't seem to be any official documentation regarding these variables, and it seems there's a lot of fragmentation over what variables are used.

- `ANDROID_NDK_HOME` (Android Studio)
- `ANDROID_NDK_ROOT` ([OpenSSL](https://github.com/openssl/openssl/blob/1c0eede9827b0962f1d752fa4ab5d436fa039da4/NOTES-ANDROID.md), mruby, etc.)
- `NDK_HOME` (also seems to be [Android Studio](https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-21-rust-on-android.html)
- `NDK_ROOT` (Android NDK [itself](https://android.googlesource.com/platform/ndk/+/ac5a15cc32244c9d24f84435693c21eabb4fd34d/build/core/init.mk))

`NDK_HOME` or `ANDROID_NDK_HOME` doesn't seem to be documented anywhere, nor used in the Android NDK, so I'm not sure we should handle these variables in cross itself.
