### ISSUE TITLE
Build fails for crates that uses ring 1.3.5

### ISSUE THREAD

**Issue by TotalKrill** [cross-rs/cross#264]
[ring issue](https://github.com/briansmith/ring/issues/673)

It is fixable by changing the docker image to use a more recent version of Ubuntu, 

should the Ubuntu version be upgraded, or could the ubuntu version be settable somehow?

**Comment by Alexhuszagh** [comment]
Relevant issues and PRs include #557 and #591, which should upgrade the Ubuntu to a more version. Unfortunately, due to some packages and especially images with Linux headers, allowing an arbitrary Ubuntu version is much more difficult than it sounds.

**Comment by Alexhuszagh** [comment]
No longer replicates as of the latest commit for ring (https://github.com/briansmith/ring/commit/0f3bf0031a8dbba741b26f1f02ebde6b7db4a3d6):

```bash
$ git clone https://github.com/briansmith/ring
$ cd ring
$ cross build --target aarch64-unknown-linux-gnu
$ cross test --target aarch64-unknown-linux-gnu
```

All pass.
