### ISSUE TITLE
cross build --target-dir=<path> ... doesn't work

### ISSUE THREAD

**Issue by vadimcn** [cross-rs/cross#272]
I'm calling cross from cmake to build a Rust component, and I wanted to relocate the `target` directory under cmake's build root.  Unfortunately, this does not work, because cross seems to assume that `target` must always be located next to `Cargo.toml`.

Relocating `target` via .cargo/config containing `target-dir = "build/target"` doesn't work either.

**Comment by Alexhuszagh** [comment]
This should have been patched as of #713. Let me know if the issue still remains.
