### ISSUE TITLE
Cross compiling forces a recompile for other architectures

### ISSUE THREAD

**Issue by timlyo** [cross-rs/cross#280]
Running the following: 
```
cargo build --release
cross build --release --target armv7-unknown-linux-musleabihf
cargo build --release
cross build --release --target armv7-unknown-linux-musleabihf
```

Results in 4 full recompiles. I'm building for two architectures simultaneously and this means my compile and run cycle take ~ 7 minutes rather than ~30s. Is there any way to cache the build for each architecture so that I'm only compiling my changes each time?

**Comment by massimiliano-mantione** [comment]
As a workaround `--target-dir` can be used to specify another target dir when building locally.
This does not invalidate the build cache.

Unfortunately `--target-dir` does not work for `cross`, only for `cargo`.

**Comment by Alexhuszagh** [comment]
Duplicate of #551.
