### ISSUE TITLE
Wishlist: Add a feature to support installing packages in the Docker image when cross runs

### ISSUE THREAD

**Issue by autarch** [cross-rs/cross#281]
I know I can use custom Docker images for this but creating and maintaining several (possibly 10+) images just to add a `git` binary seems very heavyweight and painful.

I would think that it'd be possible for `cross` to invoke `apt-get` in the image before it calls `cargo` (or `xargo`). I could look into implementing this if there's agreement that this is a thing that should be possible.

**Comment by SirWindfield** [comment]
Damn, I was wondering why my builds would constantly fail before I realised I'm running Docker instances 🤷‍♂ 

Would love if you could implement this! :smile:

**Comment by SirWindfield** [comment]
As using their images doesn't work for my dependencies either, I just forked the project, removed the Dockerfiles that I do not need and bump them up to xenial which allowed me to install my library dependencies without any issues. I modified the images directly and published them under a new organisation for my project that mentions that the images are only used to cross compile my project.

**Comment by Alexhuszagh** [comment]
This was implemented in #678, and the documentation on how to use pre-build hooks or custom Dockerfiles can be found on the [wiki](https://github.com/cross-rs/cross/wiki/Configuration#build).

**Comment by Himalayan313** [comment]
name: Build with Gradle
  uses: gradle/actions@v5.0.0
