### ISSUE TITLE
Remove typographic quotes

### ISSUE THREAD

**Issue by therealprof** [cross-rs/cross#324]
As per https://github.com/rust-embedded/cross/pull/302#issuecomment-528743478 someone should fix the use of typographic quotes in the markdown files to ensure compatibility with command line tools and editors.

CC @Dylan-DPC

**Comment by CryZe** [comment]
Which command line tools have problems handling these quotes? Also are those even needed to parse the README? Why would you even parse the README in the first place with anything that's not a Markdown parser? I fail to see the motivation behind this.

**Comment by therealprof** [comment]
@CryZe grep, sed, ... 

Editors need to have fonts installed which can render this and then even some do have problems rendering multi-byte characters which is the reason why using Unicode in Markdown without any compelling reason is generally frowned upon. Also there's the issue of equivalency classes in Unicode; there're tons of different quotes and who's going to ensure they're applied in a consistent manner.

The motivation for this issue is accessibility. The quotes should not have been changed in the first place but the nit changing them back has been dismissed because "we can always change that back later" which is what this issue is about.

**Comment by CryZe** [comment]
> Also there's the issue of equivalency classes in Unicode;

These are going to be copy pasted. I don't see how you are going to accidentally introduce a different one. And even if you did, I don't see what issue this even causes. Yes you might not find all of them anymore when grepping, but why would you ever even grep for these in the first place? Which brings us to grep. It works just fine for me:
```
cat README.md | grep '“'
> “Zero setup” cross compilation and “cross testing” of Rust crates
- “cross testing”, `cross` can test crates for architectures other than i686 and
A target is considered as “supported” if `cross` can cross compile a
“non-trivial” (binary) crate, usually Cargo, for that target.
of system calls from “foreign” (non x86_64) binaries.
  to modify its “source”, the build will fail. Well behaved crates should only
```

I don't find the fonts argument to be compelling either. The fonts for it should be installed on pretty much every system. I don't think any normal operating system is missing these. And if you are using a super random rare operating system, you probably have other problems than the quotation marks of the readme not rendering correctly.

Like that's what I not get. You act as if these quotation marks are going to cause massive issues when in reality the issues that could potentially happen are so rare and have so little impact.

**Comment by therealprof** [comment]
> Like that's what I not get. You act as if these quotation marks are going to cause massive issues when in reality the issues that could potentially happen are so rare and have so little impact.

They could cause problems and there's no reason for them to actually be there. It's not up to me to demonstrate that they **will** cause problems.

My nit about this needless change has been dismissed to not hold up the release and under the premise that this will be rectified later. I'm just following up on this and actually I'm slightly confused that I have to do so because where I come from, if you knowingly introduce or accept (technical) debt the onus is on you make sure it's rectified.

**Comment by therealprof** [comment]
> cat README.md | grep '“'

Sure, if you copy and paste the glyphs out of the document you can use any unicode aware tools to work with them. You're very much missing the point...

**Comment by reitermarkus** [comment]
> Editors need to have fonts installed which can render this and then even some do have problems rendering multi-byte characters which is the reason why using Unicode in Markdown without any compelling reason is generally frowned upon. 

What kind of editors cannot display Unicode characters? I'd switch editors or file a bug report for that editor in that case.

> They could cause problems

So should we also stop writing new code and keep using ancient technology instead since new one could cause problems? I wonder why no-one has filed an issue for the “✓” character in the ReadMe yet.

> You're very much missing the point...

The point being?

**Comment by therealprof** [comment]
> The point being?

It's best practice to stick to ASCII (i.e. characters which you can find on a regular keyboard) as much as possible to allow people to seamlessly work with those documents with regular tools. If a markdown renderer wants to render them as English textbook quotes for presentation, that's perfectly okay but they shouldn't be in the source files.

>  wonder why no-one has filed an issue for the “✓” character in the ReadMe yet.

Seriously?

**Comment by reitermarkus** [comment]
> It's best practice to stick to ASCII

Clearly there is no canonical best practice on this as is apparent by looking at this discussion.

**Comment by therealprof** [comment]
So all best practises are out of the window as soon as a single person disagrees with them (for whatever reason)? That's interesting...

**Comment by reitermarkus** [comment]
Well, it seems best practices for typesetting English text are out of the window because *you* disagree.

There is a place for compatibility best practices, a ReadMe file written in Markdown which the majority of people will only ever view rendered as HTML on GitHub isn't it.

**Comment by Emilgardis** [comment]
Closing this issue as stale. However, if someone wants to adjust these tokens, open a PR!

Reading through the thread, I feel there was some heated and opinionated discussion and I'd like to remind everyone of the [CoC](https://github.com/cross-rs/cross/blob/main/CODE_OF_CONDUCT.md)

> * Please be kind and courteous. There's no need to be mean or rude.
> * Respect that people have differences of opinion and that every design or implementation choice carries a trade-off and numerous costs. There is seldom a right answer.

I'm sure no one meant any harm, but remember that text is an inferiour medium when executed with emotion, and that words can hurt, even if not meant to be hurtful. <3
