### ISSUE TITLE
Running `cross` with `--metadata-path=directory/Cargo.toml` will fail to work

### ISSUE THREAD

**Issue by nagisa** [cross-rs/cross#334]
There are a couple of work-arounds for read-ability or write-ablity of certain files in the source of `cross`, but they won’t work when `--metadata-path` is specified.

**Comment by reitermarkus** [comment]
Yeah, this is related to the caveat in https://github.com/rust-embedded/cross#caveats. If you see a way to support arbitrary directories instead of just the directory containing the `Cargo.toml`, a PR would be appreciated.

**Comment by Alexhuszagh** [comment]
Should be fixed as of #684.
