### ISSUE TITLE
Support macOS targets

### ISSUE THREAD

**Issue by Timmmm** [cross-rs/cross#338]
Difficult, but apparently it can be done. See the discussion [here](https://github.com/japaric/rust-cross/issues/22) and [the linked repo](https://github.com/zmoazeni/rust-crossbuild).

**Comment by Dylan-DPC** [comment]
An attempt was made in #131

**Comment by Alexhuszagh** [comment]
This was attempted in #480, however, since we cannot distribute the generated image with macOS SDK, we've provided a Dockerfile and instructions how to build the required image for Apple targets (Darwin or iOS) on [cross-toolchains](https://github.com/cross-rs/cross-toolchains#apple-targets).
