### ISSUE TITLE
Build cache fingerprint does not invalidate when passthrough environment is modified

### ISSUE THREAD

**Issue by polarathene** [cross-rs/cross#365]
While unsucessfully trying to pass through some environment variables for a crate to find libs to link to within the cross container, I built a simple snippet to verify env vars were correctly being read within the container.

Some sort of caching is going on, in which if the rust code built successfully, modifications to `Cross.toml` or the environment provided to cross are ignored. In the example snippets below, `TEST_VAR` could be changed to `TEST_FOO` in `Cross.toml` or the value of `TEST_VAR` changed in the command, and performing a compile would claim it was successful(output `Finished release [optimized] target(s) in 0.07s`), but the previous build artifact remains instead.

I've removed the old binary, and run the command again. It is the same old binary(modification date is exactly the same, does not reflect the current time). Deleting `release/.fingerprint/` remedies the issue. Alternatively, modifying the rust source code will also invalidate the cache, raising an error if the example change on `Cross.toml` was performed. Correcting `Cross.toml` from a failed compile works fine without needing to modify the rust code again.

`Cross.toml`:
```TOML
[build.env]
passthrough = [
  "TEST_VAR",
]
```
`src/main.rs`:
```Rust
fn main() {
    const envvar: &'static str = env!("TEST_VAR");
    println!("Environment Variable is: {}", envvar);   
}
```

Command: `TEST_VAR="Hello World" cross build --target=x86_64-unknown-linux-gnu --release`

System:
```
Manjaro Linux x86_64
cross 0.1.16
cargo 1.39.0 (1c6ec66d5 2019-09-30)
```

**Comment by Alexhuszagh** [comment]
I don't believe this is an issue with `cross`: you're supposed to create a build script using [rerun-if-env-changed](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-env-changed). However, with the example above, I'm not reproducing the example: using the following updates the build each time:

```
$ cargo install cross --git https://github.com/cross-rs/cross
$ export TEST_VAR=1
$ cross run --target i686-unknown-linux-gnu --quiet
Environment Variable is: 1
$ export TEST_VAR=2
$ cross run --target i686-unknown-linux-gnu --quiet
Environment Variable is: 2
```
