### ISSUE TITLE
Support specifying a rustc channel via +channel argument

### ISSUE THREAD

**Issue by anti-social** [cross-rs/cross#370]
`cargo` supports specifying channels via:
```
cargo +nightly bench
```

At the moment `cross` just runs cargo on the host system. As a workaround it is possible to specify channel via an environment variable:
```
RUSTUP_TOOLCHAIN=nightly cross bench
```

Think it would be nice to have this feature in order to be more `cargo` friendly.

**Comment by Alexhuszagh** [comment]
This is currently supported and was added in #370.
