### ISSUE TITLE
Building with local dependencies

### ISSUE THREAD

**Issue by Piripant** [cross-rs/cross#388]
It seems that when building with a local dependency cross fails to load the source for that local dependency. If this is my Cargo.toml:
```toml
[dependencies]
nasatopo = { path = "../nasatopo" }
```
The output of `cross build` is:
```
error: failed to load source for a dependency on `nasatopo`

Caused by:
  Unable to update /nasatopo

Caused by:
  failed to read `/nasatopo/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```
Which is technically correct as the is not /nasatopo, but it the Cargo.toml I specified a local path, not a global one, as cross seems to understand.
Furthermore if I try to replace the relative path with a global one, the same error still happens, this time pointing to a path which is actually valid and takes to the location of the nasatopo source folder.

I think this has to do with how a docker container interfaces with the file-system, but I am not familiar and cannot tell.

**Comment by velvia** [comment]
This is hitting me as well.   I even tried symlink but it doesn't work either.

**Comment by zekronium** [comment]
Cross only mounts the cargo project.

I had this issue as well and resolved it by moving the dependency into the project dir.

The path then has to be changed to
`nasatopo = { path = "nasatopo" }`

**Comment by reitermarkus** [comment]
Yeah, we would need to parse the `Cargo.toml` and find all `path` dependencies, then mount them inside the container.

**Comment by kornelski** [comment]
Could you mount root of the workspace?

I'm trying to build one of crates in a workspace, but running into the same problem - that crate gets moved out of its workspace.

**Comment by bplower** [comment]
I'm bumping into this as well, but I was hoping to solve it using the volume mount feature. I tried adding a `Cross.toml` file with the following content:
```toml
[build.env]
volumes = [
    "MY_DEP",
]
```

In my Cargo.toml I have:

```toml
[dependencies]
my_dep = { path = "../my-dep" }
```
However when I run cross with that environment variable set, it fails with the same error reported by @Piripant. Verbose output shows that the volume mount isn't being added:

```console
$ MY_DEP=../my-dep cross build --target x86_64-unknown-linux-gnu --verbose
+ "rustc" "--print" "sysroot"
+ "rustup" "toolchain" "list"
+ "rustup" "target" "list" "--toolchain" "stable-x86_64-unknown-linux-gnu"
+ "rustup" "component" "list" "--toolchain" "stable-x86_64-unknown-linux-gnu"
+ "/usr/local/bin/docker" "run" "--userns" "host" "-e" "PKG_CONFIG_ALLOW_CROSS=1" "--rm" "--user" "501:20" "-e" "XARGO_HOME=/xargo" "-e" "CARGO_HOME=/cargo" "-e" "CARGO_TARGET_DIR=/target" "-e" "USER=me" "-e" "CROSS_RUNNER=" "-v" "/Users/me/.xargo:/xargo:Z" "-v" "/Users/me/.cargo:/cargo:Z" "-v" "/cargo/bin" "-v" "/Users/me/development/my-project/backend-api:/project:Z" "-v" "/Users/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:/rust:Z,ro" "-v" "/Users/me/development/my-project/backend-api/target:/target:Z" "-w" "/project" "-i" "-t" "rustembedded/cross:x86_64-unknown-linux-gnu-0.2.1" "sh" "-c" "PATH=$PATH:/rust/bin cargo build --target x86_64-unknown-linux-gnu --verbose"
error: failed to get `my_dep` as a dependency of package `backend_api v0.1.0 (/project)`

Caused by:
  failed to load source for dependency `my_dep`

Caused by:
  Unable to update /my-dep

Caused by:
  failed to read `/my-dep/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Am I using the volume feature wrong here? As far as I can tell, I'm using it as described by the documentation.
<hr>

Beyond my issue of using the volume feature, it looks like the volumes don't let you change where the path gets mounted in the container. The code for this is [here](https://github.com/rust-embedded/cross/blob/master/src/docker.rs#L136:L141):

```rust
if let Ok(val) = env::var(var) {
    let host_path = Path::new(&val).canonicalize()?;
    let mount_path = &host_path;
    docker.args(&["-v", &format!("{}:{}", host_path.display(), mount_path.display())]);
    docker.args(&["-e", &format!("{}={}", var, mount_path.display())]);
}
```

It looks like the path in the container will be the same as the canonical path on the host, which obviously won't work for us. For example, my attempted work around would result in the docker flag `-v /Users/me/development/my-project/my-dep:/Users/me/development/my-project/my-dep`, but we know cargo will be looking for the dependency at `/my-dep`.

We could expand the volume feature to respect host/container volume paths such that the environment variable `MY_DEP=../my-dep:/my-dep` would translate to the docker flag `-v /Users/me/development/my-project/my-dep:/my-dep`. @reitermarkus and @malbarbo Does that sound like a change you'd be comfortable with? If so, then I can get a PR put together for this.

**Comment by wngr** [comment]
The other possibility would be to run cross from the root dir, but be be able to give an additional working dir parameter (like `docker -w`).

**Comment by TarekkMA** [comment]
@bplower I did face issues with the volume feature as well. But I realized the code you linked is newer than the latest release.

I installed cross from git directly and the option worked
``
 cargo install cross --git https://github.com/rust-embedded/cross/
``

**Comment by conradkleinespel** [comment]
I needed to run tests with local dependencies referenced as symlinks in a monorepo, so I created a bit of tooling for myself around `cross`. The tool is available as open source, maybe it would work for you too. Here's how you can try it out:

- clone the git repository from https://github.com/conradkleinespel/duck
- install `dt`, which wraps `cross` with  `cargo install --path projects/dt --debug`
- now you can run `cross` with `dt cargo-test <path-to-your-crate>`, add the `--windows` option to test on a Windows target

This works simply by copying the create to a temporary directory and copying symlinks as regular files (ie `rsync --copy-links`). Note that you may need a [specific directory structure](https://github.com/conradkleinespel/duck#structure-of-rust-crates) for symlinks to work as expected.

Feel free to open a PR if you feel like you need other test options or an issue for any questions :+1:

**Comment by conradkleinespel** [comment]
I needed to run tests with local dependencies referenced as symlinks in a monorepo, so I created a bit of tooling for myself around `cross`. Here's a quick demo where I run tests once on Linux, once on Windows for a crate that has a local dependency in the parent directory: https://asciinema.org/a/53SXP4HopeeGNXKlWr20zQLvq

The tool is available as open source, maybe it would work for you too. Here's how you can try it out:

- clone the git repository from https://github.com/conradkleinespel/duck
- install `dt`, which wraps `cross` with  `cargo install --path projects/dt --debug`
- now you can run `cross` with `dt cargo-test <path-to-your-crate>`, add the `--windows` option to test on a Windows target

This works simply by copying the create to a temporary directory and copying symlinks as regular files (ie `rsync --copy-links`).

Note that you may need a [specific directory structure](https://github.com/conradkleinespel/duck#structure-of-rust-crates) for symlinks to work as expected. The use of symlinks also makes `cargo test --doc` fail in some cases but the [ability to move docs to separate markdown files](https://github.com/rust-lang/rust/pull/83366) will be stabilized soon, which would make this small problem go away.

Feel free to open a PR if you feel like you need other test options or an issue for any questions :+1:

**Comment by mkhattab** [comment]
I think have a work around for this that perhaps may help someone. The `cross` command accepts a `DOCKER_OPTS` environment variable, so you can use that to mount volumes into the container.

For example, assuming you have a workspace like the following:
```
.
├── Cargo.toml
├── foo                       # `foo` has a dependency on `../bar`
│   └── Cargo.toml
└── bar
    └── Cargo.toml
```

```bash
# in foo/
DOCKER_OPTS="-v $(realpath ..)/bar:/bar" cross build --target x86_64-unknown-linux-gnu
```

On macOS the above command works for me.

**Comment by neilvv** [comment]
@Emilgardis  - tried with #684  and solves the local dependency problem for me.  Thanks.

**Comment by Alexhuszagh** [comment]
This is also partially related to #405, however, #684 fixes the issue much more robustly.
