### ISSUE TITLE
Windows 32bit support

### ISSUE THREAD

**Issue by loriopatrick** [cross-rs/cross#402]
I have a few users for a small tool that I'm working on that need 32bit windows support. Happy to try contributing an update if I find the time. Currently setting up the tool chain on a windows machine to get things working but would really appreciate support for this target.

**Comment by buxx** [comment]
32bit image look like to exist, but i have an compile error, see: https://github.com/rust-embedded/cross/issues/406

**Comment by BornToRain** [comment]
+1

**Comment by LAGonauta** [comment]
Today I had to compile some Windows stuff for 32-bit but I received the `Docker image not available error`. The i686 image seems to be [available](https://hub.docker.com/layers/rustembedded/cross/i686-pc-windows-gnu/images/sha256-db772092dea11026b41a12b2c63a7ff6d0b7676a0de2c285d40c2ec6d9f4223d?context=explore), but wasn't detected by cross.

I just had to add to my `Cross.toml` file:
```
[target.i686-pc-windows-gnu]
image = "rustembedded/cross:i686-pc-windows-gnu"
```

Still need to test the compiled result, though.

**Comment by Alexhuszagh** [comment]
This should be fixed on main, using cross installed from the latest commits. The following works out-of-the-box:

```bash
cargo install cross --git https://github.com/cross-rs/cross
cargo init --bin --name hello hello
cd hello
cross build --target i686-pc-windows-gnu
```
