### ISSUE TITLE
Define PKG_CONFIG_PATH in Docker images

### ISSUE THREAD

**Issue by gdesmott** [cross-rs/cross#404]
As stated on https://github.com/rust-embedded/cross/issues/149#issuecomment-610265947 one has to manually define `PKG_CONFIG_PATH` in their custom docker image in order to build Rust code relying on external libs.

Automatically defining it in the `cross` images would make things easier as users would just have to derive from the official images and install their extra packages.
Would you consider such change in the docker files?

**Comment by capnfabs** [comment]
I just ran into this and agree that changing the docker images for this would be helpful. The fact that `cross` sets `PKG_CONFIG_ALLOW_CROSS=1` in the env for the build without changing the path, set me up to make a mistake when building my own container: I installed both the host + target arch for a given lib, and then pkg-config picked the host arch.

In the end, my solution was to set `PKG_CONFIG_LIBDIR` in the Dockerfile, as per [this article](https://www.freedesktop.org/wiki/Software/pkg-config/CrossCompileProposal/), so my Dockerfile now looks like this:

```
FROM rustembedded/cross:armv7-unknown-linux-gnueabihf-0.2.1

RUN dpkg --add-architecture armhf

RUN apt-get update && \
    apt-get install --assume-yes libasound2-dev:armhf libssl-dev:armhf

ENV PKG_CONFIG_LIBDIR=/usr/local/lib/arm-linux-gnueabihf/pkgconfig:/usr/lib/arm-linux-gnueabihf/pkgconfig
```

The advantage of `PKG_CONFIG_LIBDIR` over `PKG_CONFIG_PATH` is that it _overrides_ what `pkg-config` selects by default, which means you can't accidentally link the host architecture version of something if you forget to install the target arch package.

**Comment by Crell** [comment]
This seems to be causing issues with rust-openssl as well.  I don't know the guts of Cross well enough to say what may be going on or how to fix it, but I can confirm the problem still exists.

**Comment by capnfabs** [comment]
@Crell in case it's helpful to you (and others!), I kept digging into this after I left that comment, and have written a couple of in-depth blog posts about getting cross-compile working with system packages, they're here:

- [Cross-Compiling Rust apps for the Raspberry Pi](https://capnfabs.net/posts/cross-compiling-rust-apps-raspberry-pi/) -- describes building a custom container using the approach in my comment, above (but improved a little)
- [Cross-Compiling Rust Apps II: Linux Subtrees and Linker Shenanigans](https://capnfabs.net/posts/cross-compiling-rust-apps-linker-shenanigans-multistrap-chroot/) -- describes building a custom container which has a target linux distribution in a subdirectory of the container's filesystem.

**Comment by zwhitchcox** [comment]
Is there a workaround?

**Comment by zwhitchcox** [comment]
I don't have the directory `/usr/local/lib/arm-linux-gnueabihf/pkgconfig` on my local computer

**Comment by zwhitchcox** [comment]
Ok, I'm able to buidl using the Dockerfile from @capnfabs

**Comment by zwhitchcox** [comment]
Was able to get this to work in the docker file.

Here's my file for aarch64 in case it helps anyone:

```Dockerfile
FROM rustembedded/cross:aarch64-unknown-linux-gnu-0.2.1

WORKDIR /home/src

RUN dpkg --add-architecture arm64

RUN apt-get update && \
    apt-get install --assume-yes libssl-dev:arm64

ENV PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig

RUN curl https://sh.rustup.rs -sSf | \
    sh -s -- --default-toolchain stable -y

ENV PATH=/root/.cargo/bin:$PATH

RUN apt-get install libssl-dev pkg-config -y

COPY . .

CMD cargo build --release
```
