### ISSUE TITLE
rustc ICE when building with cross

### ISSUE THREAD

**Issue by RalfJung** [cross-rs/cross#407]
xargo CI [is failing](https://travis-ci.org/github/japaric/xargo/builds/674306076) with a strange ICE:
```
thread 'rustc' panicked at 'failed to lookup `SourceFile` in new context', src/librustc_middle/ty/query/on_disk_cache.rs:456:17

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (3712e11a8 2020-04-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: could not compile `xargo`.
```
The ICE occurs not always in the same place, but [replacing `cross` by `cargo`](https://github.com/japaric/xargo/pull/289/commits/e4a842cab7e10ab80bb874b55a4f57243f9aae54) makes it go away. I have no idea what is going on.

**Comment by RalfJung** [comment]
Looks like this is fixed now, whether through rustc or cross changes I do not know.

**Comment by RalfJung** [comment]
Actually [no it's not solved](https://travis-ci.org/github/japaric/xargo/jobs/682695584).

This currently means we cannot land any xargo PRs.

**Comment by RalfJung** [comment]
Setting `export CARGO_INCREMENTAL=0` seems to work around the issue.

**Comment by reitermarkus** [comment]
I tried the `cross test` command locally and cannot reproduce this, neither on stable nor on nightly.

**Comment by RalfJung** [comment]
I never used cross myself so I'm afraid I can't help much here... I just inherited this as part of the existing xargo CI setup that I barely understand.^^

**Comment by Alexhuszagh** [comment]
This isn't replicating for me, and I believe this is probably related to the incremental compilation issues that Rust was having and then mostly fixed? I'm very unsure of that, but I can't seem to replicate this issue anymore. I've tried also using a nightly very close to yours and the latest xargo.


```bash
$ TARGET=armv7-unknown-linux-gnueabihf
$ rustc +nightly-2020-04-12 --version
rustc 1.44.0-nightly (e82734e56 2020-04-11)
$ cross +nightly-2020-04-12 run --bin xargo --target $TARGET -- -V
Warning: using older rustc `1.44.0-nightly (e82734e56 2020-04-11)` for the target. Current active rustc on the host is `rustc 1.63.0-nightly (ca122c7eb 2022-06-13)`.
 > Update with `rustup update --force-non-host nightly-2020-04-12-x86_64-unknown-linux-gnu`
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running `/linux-runner armv7 /target/armv7-unknown-linux-gnueabihf/debug/xargo -V`
xargo 0.3.26 (2b00127 2022-06-01)
cargo 1.44.0-nightly (390e8f245 2020-04-07)
```

**Comment by RalfJung** [comment]
xargo CI also cannot reproduce any more. Our CI was ported from Travis to GHA since then so that might be a factor, but anyway it probably makes sense to close this issue and reopen if the problem ever arises again.
