### ISSUE TITLE
Native dependencies

### ISSUE THREAD

**Issue by mark2b** [cross-rs/cross#410]
My project is depended from libSDL2. 
Currently compilation / linking failed with "cannot find -lSDL2"
How can I add this dependency?

**Comment by CarlosLanderas** [comment]
I am having the same issue with OpenSSL

**Comment by vimmerru** [comment]
@CarlosLanderas You need to use customer docker image that have corresponded dependencies cross-compiled. For example, in case of openssl

Make Dockerfile and inherit it form cross image

```docker
FROM rustembedded/cross:x86_64-unknown-linux-musl

RUN apt-get update && \
    apt-get install -y software-properties-common
COPY openssl.sh /
RUN bash /openssl.sh linux-x86_64 x86_64-linux-musl-

ENV OPENSSL_DIR=/openssl \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib
```

place openssh.h with openssl cross-compilation code near it

```bash
set -ex

main() {
    local version=1.0.2t
    local os=$1 \
          triple=$2

    local dependencies=(
        ca-certificates
        curl
        m4
        make
        perl
    )

    # NOTE cross toolchain must be already installed
    apt-get update
    local purge_list=()
    for dep in ${dependencies[@]}; do
        if ! dpkg -L $dep; then
            apt-get install --no-install-recommends -y $dep
            purge_list+=( $dep )
        fi
    done

    td=$(mktemp -d)

    pushd $td
    curl https://www.openssl.org/source/openssl-$version.tar.gz | \
        tar --strip-components=1 -xz
    AR=${triple}ar CC=${triple}gcc ./Configure \
      --prefix=/openssl \
      no-dso \
      $os \
      -fPIC \
      ${@:3}
    nice make -j$(nproc)
    make install

    # clean up
    apt-get purge --auto-remove -y ${purge_list[@]}

    popd

    rm -rf $td
    rm $0
}

main "${@}"
```

Build docker image 

```bash
$ docker build -t my/image:tag path/to/where/the/Dockerfile/resides
```

Create Cross.toml file in your project root and map it to target

```
[target.x86_64-unknown-linux-musl]
image = "my/image:tag"
```

after this new images with available openssl will be used.

**Comment by autodidaddict** [comment]
I'm having an openssl problem with `aarch64-unknown-linux-gnu` (targeting Ubuntu 64-bit on a Raspberry Pi). When I use regular `cross` with that target, my dependency on `openssl-sys` fails to compile. When I try and build a Dockerfile using the above example but switching it out for aarch64, I get an error claiming that the aarch64 gnu toolchain isn't installed:

```
/bin/sh: 1: aarch64-unknown-linux-gcc: not found
```

any help anyone can provide with getting this to work would be immensely helpful.

**Comment by meldron** [comment]
@autodidaddict 

you are using the wrong compiler prefix. For `aarch64-unknown-linux-gnu` it is `aarch64-linux-gnu-`

(BTW for @vimmerru `build_openssl.sh` script you also have to supply the correct `openssl` target. In your case it is `linux-aarch64`.)

This should work for you:
```Dockerfile
FROM rustembedded/cross:aarch64-unknown-linux-gnu

COPY build_openssl.sh /
# first parameter is the openssl arch target (see openssls ./Configure LIST)
# second parameter is the gcc compiler prefix
RUN bash /build_openssl.sh linux-aarch64 aarch64-linux-gnu-

ENV OPENSSL_DIR=/openssl \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib \
    OPENSSL_STATIC=1
```
