### ISSUE TITLE
Rust WASM toolchain not installed, please install it

### ISSUE THREAD

**Issue by AurevoirXavier** [cross-rs/cross#423]
I'm working on substrate. It'll also compile a WASM part at the same time.

```rust
Caused by:
  process didn't exit successfully: `/target/release/build/crab-runtime-b00ee5d1b3acfcb8/build-script-build` (exit code: 1)
--- stderr
   Compiling wasm-build-runner-impl v1.0.0 (/target/x86_64-unknown-linux-gnu/release/wbuild-runner/crab-runtime7359505889082344466)
    Finished release [optimized] target(s) in 13.61s
     Running `/linux-runner x86_64 /target/x86_64-unknown-linux-gnu/release/wbuild-runner/crab-runtime7359505889082344466/target/x86_64-unknown-linux-gnu/release/wasm-build-runner-impl`
Rust WASM toolchain not installed, please install it!

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by reitermarkus** [comment]
Please feel free to submit a pull request adding it.

**Comment by AurevoirXavier** [comment]
> Please feel free to submit a pull request adding it.

But I'm not familiar to docker. IDK how to add it.

**Comment by AurevoirXavier** [comment]
After I read the code, I think I should add a flag somthing like `--substrate`. I'll open a PR.

**Comment by thanhdeptrai69** [comment]
Please try,
rustup toolchain install nightly-2020-08-23
rustup target add wasm32-unknown-unknown --toolchain nightly-2020-08-23

Then compile your node with:
cargo +nightly-2020-08-23 build --release

**Comment by SarahKay99** [comment]
@thanhdeptrai69 I ran the second command

`rustup target add wasm32-unknown-unknown --toolchain nightly-2020-08-23`

I got 

`error: toolchain 'nightly-2020-08-23-x86_64-pc-windows-msvc' is not installed`
