### ISSUE TITLE
No longer needed to ship qemu-static in containers

### ISSUE THREAD

**Issue by gdesmott** [cross-rs/cross#425]
Cross is building `qemu-static` to make transparent binary translation work inside the container. That's because it comes from a time when the binfmt_misc subsystem was not namespace aware, so it needed the static qemu to live as `/usr/bin/qemu-${arch}-static` inside the container.

With the ["F fix binary" flag of binfmt_misc](https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html) this is no longer needed, you only need the right qemu to be installed on the host, with no special provision inside the container.

As a result, on recent enough hosts we can remove all the `qemu`, `dropbear`, `linux-image`, `linux-runner` part of the Dockerfile and still get `scross` testing feature working.
I tested this on a Fedora 32 and it worked just fine. Debian Buster should also [have the right fix](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868030).

Does shipping `qemu-static` bring any other value than supporting older host not having this binfmt flag? If not I think we should consider removing it at some point. It would reduce the size and build time of image as well as the boilerplate to create custom images.

CC @em- would actually figure out all this :)

**Comment by Alexhuszagh** [comment]
It would be a breaking change, but I think it would be a good idea to drop support for host Rust versions < 1.19, since it's ~5 years old at this point.

**Comment by Emilgardis** [comment]
Seems fine! I just looked at this today and were wondering why it's needed, guess it actually isn't.

**Comment by Alexhuszagh** [comment]
After looking closer, considering we still need `linux-image` for full-system emulation (`qemu-system`), we can't exactly drop `dropbear`, `linux-image`, or `linux-runner` unless we no longer wish to support this functionality. But I still think the clearer code paths would probably make it worth it, and we never use the `qemu-${arch}-static` versions anyway anymore. It may not save much on image space, but it's effectively dead code these days.

**Comment by Alexhuszagh** [comment]
Closing this since we might still want to support Rust <= 1.19, and the static Qemu builds are actually a hack that use the dynamically-linked binaries to trick binfmt to work:

https://github.com/cross-rs/cross/blob/86e3f62e0521e6a5db29ede40195bf69e849dc07/docker/qemu.sh#L221-L223
