### ISSUE TITLE
Can't target Raspberry Pi 1 and Pi Zero

### ISSUE THREAD

**Issue by BrianHoldsworth** [cross-rs/cross#426]
This issue is related to #391 and #414 

I am trying to build for the Pi Zero W using target=arm-unknown-linux-gnueabihf. I think that's the right target for RPi, but there is no way to distinguish between building for ARMv6 (RPi 1 and Zero) vs. ARMv7 (RPi 2). The resulting binary is ARMv7, which works on RPi2, but crashes with a segmentation fault on RPi Zero.

I add the following in my simple Rust project's `Cross.toml` file to avoid using the older "0.2" version docker image that was upgraded for #391 
```
[target.arm-unknown-linux-gnueabihf]
image = "rustembedded/cross:arm-unknown-linux-gnueabihf"
```
AND I can confirm using `docker images` after running `cross build` that I'm not using the older `arm-unknown-linux-gnueabihf-0.2.0`
```
REPOSITORY           TAG                           IMAGE ID            CREATED             SIZE
rustembedded/cross   arm-unknown-linux-gnueabihf   ba2dc7364b10        5 days ago          2.2GB
```
It appears to me that `cross build` is creating an ARMv7 binary, and this causes the Seqmentation Fault on the Pi Zero, which is an ARMv6 CPU.
```
$ !readelf
readelf --arch-specific target/arm-unknown-linux-gnueabihf/debug/rpi-test
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3-D16
  Tag_ABI_PCS_GOT_use: GOT-indirect
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
  Tag_ABI_FP_16bit_format: IEEE 754
```

**Comment by schlamar** [comment]
Yes, the compiler downloaded from developer.arm.com in the Dockerfile (https://github.com/rust-embedded/cross/blob/master/docker/Dockerfile.arm-unknown-linux-gnueabihf#L14) is built with `--with-arch=armv7-a` (you can check that with arm-linux-gnueabihf-gcc -v). So it cannot target ARMv6.

Here is a possible solution: https://github.com/Pro/raspi-toolchain

**Comment by schlamar** [comment]
I just confirmed that the above toolchain works for Pi Zero.

And the [official Raspberry toolchain](https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf) works, too. Here is a description: https://github.com/japaric/rust-cross/issues/42

**Comment by BrianHoldsworth** [comment]
@schlamar Thanks for the response and I'm aware of those other options. Problem is they aren't suitable for complex projects that need to install native arm packages into the docker image; something that this project manages quite nicely. Case in point my current Rust project builds fine using this project for RPi 2 but cannot link (due to dependency issues) using this alternate approach. So, I'll continue to pursue support here and/or cobble together a Dockerfile that merges the necessary ARMv6 toolchain support.

**Comment by schlamar** [comment]
Yes, of course :-) The cross maintainers should integrate one of these solutions (or another working alternative for ARMv6) into their arm-unknown-linux-gnueabihf Dockerfile.

But other persons who stumble about this issue by Google (like me two days ago) will be thankful for a workaround I guess ;-)

**Comment by reitermarkus** [comment]
> The cross maintainers should integrate one of these solutions

PRs are welcome. 😉

**Comment by tmigone** [comment]
hey @BrianHoldsworth did you find a solution? I think I'm having a similar problem. I'm building a project for the Raspberry Pi Zero and failing to link dependencies even though they are installed.

**Comment by BrianHoldsworth** [comment]
@tmigone I punted for now, since I am just in prototype and can target an RPi2

**Comment by zenria** [comment]
Hi, I've managed to make it work using a custom docker image: https://github.com/zenria/rbp1-cross-docker

**Comment by BrianHoldsworth** [comment]
#zenria I can see how that *should* work. Unfortunately, something about this Dockerfile seems to revert to a different / older glibc for ARM, which breaks linking for me.

**Comment by zenria** [comment]
> @zenria I can see how that _should_ work. Unfortunately, something about this Dockerfile seems to revert to a different / older glibc for ARM, which breaks linking for me.

Which distro do you run on your Pi?

I'm building executables with this docker image that runs successfully on Raspbian 9.11:
```
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
```

**Comment by BrianHoldsworth** [comment]
I am targeting Arch Linux ARM, a rolling distro, on RPi2 (works fine linking and running with `cross build`) and PRi Zero (generates armv7 when used with normal `cross build` and fails linking with your custom docker image).

**Comment by chaseboren** [comment]
I was able to successfully compile for the Pi Zero with this patch that utilizes abhitronix pre-built tool chains. It breaks the toolchain versioning, but GCC 8, 9, and 10 versions are available. 

diff --git a/docker/Dockerfile.arm-unknown-linux-gnueabihf b/docker/Dockerfile.arm-unknown-linux-gnueabihf
index 0edd07e..ba0f926 100644
--- a/docker/Dockerfile.arm-unknown-linux-gnueabihf
+++ b/docker/Dockerfile.arm-unknown-linux-gnueabihf
@@ -1,7 +1,9 @@
-FROM ubuntu:18.04
+FROM ubuntu:20.04

 COPY common.sh lib.sh /
-RUN /common.sh
+RUN /common.sh
+
+

 COPY cmake.sh /
 RUN /cmake.sh
@@ -9,12 +11,13 @@ RUN /cmake.sh
 COPY xargo.sh /
 RUN /xargo.sh

+
 RUN mkdir /usr/arm-linux-gnueabihf \
- && cd /usr/arm-linux-gnueabihf \
- && export TOOLCHAIN_VERSION=8.3-2019.03 \
- && curl --retry 3 -sSfL https://developer.arm.com/-/media/Files/downloads/gnu-a/${TOOLCHAIN_VERSION}/binrel/gcc-arm-${TOOLCHAIN_VERSION}-x86_64-arm-linux-gnueabihf.tar.xz -O \
- && tar --strip-components 1 -xJf gcc-arm-${TOOLCHAIN_VERSION}-x86_64-arm-linux-gnueabihf.tar.xz \
- && rm gcc-arm-${TOOLCHAIN_VERSION}-x86_64-arm-linux-gnueabihf.tar.xz
+    && cd /usr/arm-linux-gnueabihf \
+    && export TOOLCHAIN_VERSION=10.2-2020.11 \
+    && curl --retry 3 -SfL --output tool.tar.gz https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Buster/GCC%2010.2.0/Raspberry%20Pi%201%2C%20Zero/cross-gcc-10.2.0-pi_0-1.tar.gz/download -O \
+    && tar --strip-components 1 -xzf tool.tar.gz \
+    && rm tool.tar.gz

 ENV PATH /usr/arm-linux-gnueabihf/bin:$PATH

diff --git a/docker/common.sh b/docker/common.sh
index 16396a8..fddfbe0 100755
--- a/docker/common.sh
+++ b/docker/common.sh
@@ -35,4 +35,5 @@ if_centos install_packages \
 if_ubuntu install_packages \
     g++ \
     libc6-dev \
-    pkg-config
+    pkg-config \
+    xz-utils

**Comment by Alexhuszagh** [comment]
Rust's official [Platform Support](https://doc.rust-lang.org/rustc/platform-support.html#tier-2-with-host-tools) says that these targets should be ARMv6, so I would consider this a bug:

> | target | notes |
> | -- | -- |
> | arm-unknown-linux-gnueabi | ARMv6 Linux (kernel 3.2, glibc 2.17) |
> | arm-unknown-linux-gnueabihf | ARMv6 Linux, hardfloat (kernel 3.2, glibc 2.17) |

The current toolset uses ARMv7-A.
