### ISSUE TITLE
Add support for Redox

### ISSUE THREAD

**Issue by briansmith** [cross-rs/cross#427]
Apparently this is how people commonly test things in Redox:

```
cargo install redoxer
redoxer toolchain
redoxer test
```

It would be nice to be able to do the equivalent of that using `cross` instead.

**Comment by briansmith** [comment]
There is also a Dockerfile already: https://github.com/redox-os/redoxer/blob/master/Dockerfile.

**Comment by asomers** [comment]
redoxer is a pretty heavyweight solution.  And in my experience, it often hangs.  I think it would be worthwhile for cross to add compile-only support for Redox, much like it currently has for NetBSD.

**Comment by Alexhuszagh** [comment]
We've now documented how to use [redoxer](https://github.com/cross-rs/cross/wiki/Recipes#redoxer) with `cross`, but this is too heavyweight of a solution to use by default with `cross` itself.

**Comment by mcandre** [comment]
Rust 1.81.0 promotes Redox to tier 3.

https://github.com/rust-lang/rust/releases/tag/1.81.0
