### ISSUE TITLE
Upgrade gcc/musl version for the musl images

### ISSUE THREAD

**Issue by anupdhml** [cross-rs/cross#432]
The musl images currently come with gcc [version 6.40](https://github.com/rust-embedded/cross/blob/master/docker/musl.sh#L45-L46) which fails to compile C/C++ dependencies for crates that require at least version 7 (eg: [snmalloc-rs](https://github.com/SchrodingerZhu/snmalloc-rs)).

I see that there's a [new release](https://github.com/richfelker/musl-cross-make/releases/tag/v0.9.9) of musl-cross-make now (comes with gcc 9.2 and musl 1.2 by default) so can we start using it for musl installation in the cross images? 

---

Looks like there was an attempt to do something similar earlier but was closed out then due to CI failures: https://github.com/rust-embedded/cross/pull/397

I have tried doing it from a [fork](https://github.com/anupdhml/cross/commit/cc75d477ad7b7f6adcc37d4375949854d1c3071b) locally (also bumped up the gcc/musl versions passed to the musl-cross-make setup) and the musl image builds from there seem to work fine. If it's ok to go ahead with these changes, I can file a PR for it.

**Comment by brainstorm** [comment]
@anupdhml , as soon as maintainers merge https://github.com/rust-embedded/cross/pull/452, you should be good to go and close this issue ;)

**Comment by Alexhuszagh** [comment]
The musl images currently use GCC v9.2.0, so this should be fixed.

https://github.com/cross-rs/cross/blob/459e03ec6451802d71b8befaf8df05eedf99f3f7/docker/musl.sh#L49-L56
