### ISSUE TITLE
Linking

### ISSUE THREAD

**Issue by Tockra** [cross-rs/cross#434]
Hi,

how can I cross compile crates like https://crates.io/crates/paho-mqtt ?
I can pass the OPENSSL_ROOT_DIR variable but how can I mount that directory ?

T

**Comment by Tockra** [comment]
Okay maybe I could use a own Dockerimage which installs the i368 libssl-dev. 
But now I don't know where to install the libs on my target system.
I found a package, which place the libssl.so.1.0.0 at /usr/lib/i386-linux-gnu/i686/cmov/libssl.so.1.0.0 .

I doubt my binary wouldn't find it there ?

**Comment by Alexhuszagh** [comment]
Yeah, I've documented this extensively now in the README for how to create your own container for this purpose. We use `pkg-config` to allow the build script to automatically find the include and link paths to pass the compiler and linker. See [here](https://github.com/cross-rs/cross/wiki/Recipes#openssl) for both using system packages or vendored OpenSSL, or if you need more general external libraries, see [here](https://github.com/cross-rs/cross/wiki/FAQ#linking-external-libraries).
