### ISSUE TITLE
Create github actions action

### ISSUE THREAD

**Issue by bfjelds** [cross-rs/cross#439]
It would be great to have some code demonstrating how to use Cross in github actions.

Here is an attempt (with workarounds for the "cargo not found" issue and for docker-in-docker volume mounting) that works for me: https://github.com/bfjelds/cargo-cross-in-github-action

**Comment by reitermarkus** [comment]
I'm not sure why you need to use Docker-in-Docker on Github Actions. Can you clarify your use-case?

You should be able to simply use https://github.com/actions-rs/cargo, which also provides a `use-cross` flag.

**Comment by bfjelds** [comment]
Very cool ... I hadn't seen actions-rs/cargo.

We have a project that is building Rust binaries and creating docker containers with those binaries.  Initially, we created some Github Actions [workflows](https://help.github.com/en/actions/configuring-and-managing-workflows) (.github/workflows/*.yml) to handle this and it worked fine for our initial linux/amd64 system.  Once we had that baseline working, we started working on multi-arch support.  That's when we started looking at Cross (awesome!).  We added Cross to our workflows and things pretty much just worked!

The problem we had at this point was that the workflow code was highly redundant and we decided to create Github Actions [actions](https://help.github.com/en/actions/creating-actions/about-actions) (.github/actions) to reduce the redundancy.  This is where we started running into issues.  We chose to create a Docker action (rather than perhaps the better choice: nodejs), and this is where we ran into `cargo not found` and our Docker-in-Docker issues.

**Comment by svenstaro** [comment]
You can look at [my project's flow](https://github.com/svenstaro/miniserve/blob/master/.github/workflows/publish.yml) to get a good feel for how to use cross in a best-practices GitHub Actions use case.

**Comment by bfjelds** [comment]
@svenstaro, that is defintely cool ... but it is a workflow not an action.

**Comment by Alexhuszagh** [comment]
I don't see why you've need a custom action when [actions-rs/cargo](https://github.com/actions-rs/cargo) already supports cross out-of-the-box. I've added a sample [workflow](https://github.com/cross-rs/cross/wiki/FAQ#github-workflows) to the FAQ which should show how to integrate this, but if you really want to write your own action, you can always look at the source code for [actions-rs/core/src/commands/cross.ts](https://github.com/actions-rs/core/blob/4487ec12063a411d19993339db585c95b354ffb4/src/commands/cross.ts) and how this is [parsed](https://github.com/actions-rs/cargo/blob/master/src/input.ts) from the config file and how cross integration is [implemented](https://github.com/actions-rs/cargo/blob/master/src/main.ts).
