### ISSUE TITLE
It's hard to fetch the binaries published with the latest release of `cross` without knowing the version in advance

### ISSUE THREAD

**Issue by thomcc** [cross-rs/cross#457]
It's nice that `cross` publishes binaries, since (among other things) this means CI can avoid `cargo install cross` and just use curl to fetch from the github download page.

This works great if you hardcode the version you expect, however if you try to access the download URL via the github latest link, you'll notice that the URL of the latest release's linux (gnu) binary is:

`https://github.com/rust-embedded/cross/releases/latest/download/cross-v0.2.1-x86_64-unknown-linux-gnu.tar.gz`

Tragically, this still contains the version number of the release, and so it requires hard-coding the version. 

(As an example, mozilla/grcov does not contain the version number, and so linux binary is very nicely available at `https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2`)

It's of course [possible](https://gist.github.com/thomcc/1edaa0c080377e5834587d897b6b14e8) to fetch the latest version number using the github api, but this increases the complexity a great deal, especially if you handle errors (which is worth doing, since either you or github could always change the URL) and fall back to `cargo install cross`.

So, it would be nice if cross's published binaries didn't contain the version number in their path, or that there were some fairly easy way of fetching the binary.

For what it's worth, this seems trivial to fix if you're ok with removing it, and looks like it would just require changing https://github.com/rust-embedded/cross/blob/699f07a0f1e88a4489f6c086d9766ddcc048c2d4/azure-pipelines.yml#L106

**Comment by Emilgardis** [comment]
if we do this, we should do the following: https://github.com/ryankurte/cargo-binstall#supporting-binary-installation

**Comment by Emilgardis** [comment]
This has been implemented, will come into effect with new version.

Since this breaks cargo-binstall, we've added support for it in #844
