### ISSUE TITLE
Image fetch problems with podman

### ISSUE THREAD

**Issue by MGlolenstine** [cross-rs/cross#458]
Whenever you try to run `cross build` without `Cross.toml` and with the default crate, it throws the following error: 
```
$ cross build
Error: unable to pull rustembedded/cross:x86_64-unknown-linux-gnu-0.2.1: image name provided is a short name and no search registries are defined in the registries config file.
```
The problem is that Podman doesn't have docker hub added to their default lookup list for non-annotated crate names (docker hub crates should be annotated with `docker://`), but it starts working after you add `Cross.toml` and add the following to it:
```
[target.x86_64-unknown-linux-gnu]
image = "docker://rustembedded/cross:x86_64-unknown-linux-gnu-0.2.1"
```

**Comment by b-zee** [comment]
`docker://` is actually the default for Podman, but on my system (Arch Linux) it has no default registries. This means that prefixing it with `docker.io/` will work.

Thus, before building, try e.g. `podman pull docker.io/rustembedded/cross:x86_64-unknown-linux-gnu-0.2.1`. Then Cross will find the image in your local machine.

**Comment by Alexhuszagh** [comment]
This is no longer relevant, since we now use Github container registries (ghcr.io).
