### ISSUE TITLE
Use of environment variables can make use of `.cargo/config` impossible

### ISSUE THREAD

**Issue by jonas-schievink** [cross-rs/cross#463]
The Docker containers used by cross set various environment variables that cannot be overridden in any way. This causes various issues, because this makes Cargo silently ignore the configuration from `.cargo/config`.

* On `x86_64-unknown-linux-musl`, `cross` sets `CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER`. This makes it impossible to use a custom linker wrapper by setting the `linker` key. Instead, I had to use the `rustflags` key to pass `-Clinker`.

* On `aarch64-unknown-linux-musl`, `cross` sets `CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER` as well as `RUSTFLAGS` (!), which makes it *impossible* to use a custom linker without replacing rustc with a custom wrapper (which can be made to work by setting the `RUSTC` env var, but is a lot of work and a pretty gross hack).

**Comment by jonas-schievink** [comment]
Ah I should note that most of this is only a problem due to https://github.com/rust-lang/cargo/issues/5376

**Comment by Alexhuszagh** [comment]
I believe this is fixable by using the environment variable passthrough, or by extending the Docker image (less than ideal). It might be a good idea to allow overrides of these variables in `Cross.toml`. For example, overriding `CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER` should be possible by adding it to `[target.(...).env.passthrough]`.

We currently allow overriding the runner, but it might be good to also add keywords to override the linker and rustflags.

https://github.com/cross-rs/cross/blob/c8df3539e97e43b641033be84d05feeaa40f5d4f/src/cross_toml.rs#L29-L35

**Comment by Emilgardis** [comment]
#682 would help for this

**Comment by Alexhuszagh** [comment]
This has been fixed as of #869 and it is documented on the [wiki](https://github.com/cross-rs/cross/wiki/Configuration#cargo-configuration) now.
