### ISSUE TITLE
Images with cargo and rustc built-in?

### ISSUE THREAD

**Issue by avkonst** [cross-rs/cross#468]
Great docker images are provided. When used with cross tool it works great. However, cross can not be invoked in any of the CI systems running builds inside a container. I have found what inheriting the images from "rust" base image instead or ubuntu/debian addresses the issue and the images can be used with cross and in CI too.

Is it possible to modify the images so they are inherited from "rust" image, or alternatively, where rustup/cargo/rustc are installed as a last step? If you would like to keep the current images smallish, is it possible to provide an additional set of the same images where rustup/cargo are installed too?

If these images were provided, I believe rust developers would consolidate and use these, instead of working around the issue creating private not-well-maintained derivatives from your images.

I am keen to submit pull request if you are ok with any of the above options.

Makes sense?

**Comment by Alexhuszagh** [comment]
Isn't this superseded by the addition of the `CROSS_DOCKER_IN_DOCKER` environment variable, which was added in f2c70b311a0ade06b07dafca9202e1060d96c04f
