### ISSUE TITLE
musl cannot be update to 1.2.0 yet

### ISSUE THREAD

**Issue by malbarbo** [cross-rs/cross#478]
musl was update to 1.2.0 in https://github.com/rust-embedded/cross/pull/452. The 1.2 changed the definition of time_t from 32 to 64bits, which can generate some compatibility issues (https://musl.libc.org/time64.html).

Considering that libc crate and the rust std library does not yet updated to 1.2.0 (https://github.com/rust-lang/libc/issues/1848) and the problems that can arising by using musl 1.1.x together with 1.2.x, I think it's best to not update musl used in cross images.

CC @brainstorm @therealprof

**Comment by brainstorm** [comment]
Good catch! IIRC In my experience introducing Musl 1.2.x in cross was the only way to get OpenSSL compiling in static, so it seems like we are in a crossroads here: openssl or rust-libc w/ time64, I hope they fix rust-libc soon so that openssl keeps compiling fine :/
