### ISSUE TITLE
provide a Docker image for target x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by rustbomber** [cross-rs/cross#487]
Please provide  x86_64-pc-windows-msvc image.

**Comment by paulrberg** [comment]
Perhaps a duplicate of #238.

**Comment by Alexhuszagh** [comment]
We now have [Dockerfiles](https://github.com/cross-rs/cross-toolchains) for MSVC targets, however, we're unable to distribute the built images. The Dockerfiles do not need any external dependencies, and can be built with:

```bash
git clone https://github.com/cross-rs/cross
cd cross
git submodule update --init --remote
cargo build-docker-image x86_64-pc-windows-msvc-cross
```

They use WINE to run the MSVC toolchain, so they may not be perfect with all build systems, but for pure Rust crates and those with a simple Makefile/CMake/Meson build system.
