### ISSUE TITLE
Feature request: Support for Docker's rootless mode

### ISSUE THREAD

**Issue by cptpcrd** [cross-rs/cross#490]
[Docker's rootless mode](https://docs.docker.com/engine/security/rootless/) (currently experimental) allows running the Docker daemon and containers as a user other than `root`. In some ways it is set up similarly to `userns-remap` mode (which, it seems, `cross` attempts to bypass by [specifying `--userns host`](https://github.com/rust-embedded/cross/blob/8cb7df508a113f88dc267175e982f862dc41f465/src/docker.rs#L35)). Rootless mode has major security benefits, since very little code runs with any elevated privileges during the entire process of launching the container.

However, currently `cross` assumes that the UID/GID of the user outside the container will [map to the same UID/GID inside the container](https://github.com/rust-embedded/cross/blob/8cb7df508a113f88dc267175e982f862dc41f465/src/docker.rs#L152). This is not usually true in rootless mode; usually the current user outside the container maps to `root` inside the container.

Adding an option to disable this mapping (maybe `--no-switch-user`?) or customize it (`--container-user`?) or even automatic detection of rootless mode (probably by looking for `rootless` in `docker info`) would make `cross` usable with rootless mode.

**Comment by Alexhuszagh** [comment]
Implemented in #889. We both support disabling user namespace remapping and specifying that the host is rootless now. See the [wik[(https://github.com/cross-rs/cross/wiki/Configuration#environment-variables) for documentation on the environment variables to use this.
