### ISSUE TITLE
Docker Ubuntu images should be upgraded to 20.04

### ISSUE THREAD

**Issue by Absolucy** [cross-rs/cross#517]
Outdated Ubuntu is starting to cause issues for cross-compiling some things, see https://github.com/khvzak/mlua/issues/32 for a real-world example of an issue caused by an outdated image (in this case, 16.04 in `aarch64-unknown-linux-gnu`).

**Comment by JNissi** [comment]
Please update the images. I have a miserable time trying to compile GTK stuff either for Nokia N900 Maemo Leste (`arm-unknown-linux-gnueabihf`) or the Pinephone (`aarch64-unknown-linux-gnu`).

I managed to whip up a working Ubuntu 20.04 image for the N900, but trying the same approach for the Pinephone failed miserably, so I guess that counts as not production ready. =/

When I have some time to clean up the N900 image and maybe base it on the latest config here so it works reliably I can share the docker files.

For non-Linux embedded stuff I've tried (like an nrf52 dev board and PineTime) the old Ubuntu images seem to work quite well enough.

**Comment by JNissi** [comment]
I got 20.10 working for Pinephone cross compilation with as little as:
```
diff --git a/docker/Dockerfile.aarch64-unknown-linux-gnu b/docker/Dockerfile.aarch64-unknown-linux-gnu
index 675d4bc..da43e96 100644
--- a/docker/Dockerfile.aarch64-unknown-linux-gnu
+++ b/docker/Dockerfile.aarch64-unknown-linux-gnu
@@ -1,4 +1,4 @@
-FROM ubuntu:16.04
+FROM ubuntu:20.10
 
 COPY common.sh lib.sh /
 RUN /common.sh
diff --git a/docker/linux-image.sh b/docker/linux-image.sh
index 1fd03e9..511179d 100755
--- a/docker/linux-image.sh
+++ b/docker/linux-image.sh
@@ -6,7 +6,7 @@ set -euo pipefail
 main() {
     # arch in the rust target
     local arch="${1}" \
-          kversion=4.19.0-11
+          kversion=5.8.0-25
 
     local debsource="deb http://http.debian.net/debian/ buster main"
     debsource="${debsource}\ndeb http://security.debian.org/ buster/updates main"
@@ -21,7 +21,7 @@ main() {
     case "${arch}" in
         aarch64)
             arch=arm64
-            kernel="${kversion}-arm64"
+            kernel="${kversion}-generic"
             ;;
         armv7)
             arch=armhf
```

**Comment by Alexhuszagh** [comment]
I'm currently working on updating all images to the latest LTS release (20.04) [here](https://github.com/Alexhuszagh/cross/tree/increment_versions). Afterwards, ideally we can update the Qemu versions. Testing building all the images currently, should have a PR within the next day or 2.

**Comment by 2opremio** [comment]
@Alexhuszagh any news?

**Comment by 2opremio** [comment]
For `armv7-unknown-linux-gnueabihf` it was as simple as applying this patch:

```diff
diff --git a/docker/Dockerfile.armv7-unknown-linux-gnueabihf b/docker/Dockerfile.armv7-unknown-linux-gnueabihf
index ba2c184..f9670bf 100644
--- a/docker/Dockerfile.armv7-unknown-linux-gnueabihf
+++ b/docker/Dockerfile.armv7-unknown-linux-gnueabihf
@@ -1,4 +1,4 @@
-FROM ubuntu:16.04
+FROM ubuntu:20.04
 
 COPY common.sh lib.sh /
 RUN /common.sh
```

and then running `./build-docker-image.sh armv7-unknown-linux-gnueabihf`

**Comment by bjesus** [comment]
Any reason not to update again to the latest LTS?
Ubuntu 20.04 doesn't have `gtk-4-dev`, making it a pain to build GTK4 applications...

**Comment by Alexhuszagh** [comment]
> Any reason not to update again to the latest LTS? Ubuntu 20.04 doesn't have `gtk-4-dev`, making it a pain to build GTK4 applications...

Two major reasons: backwards compatibility with glibc reasons, and also the work of implementation. Once we do, I'll start working on upgrading the images in another PR to 22.04.

**Comment by knitHacker** [comment]
This is closed but i'm using latest and it is still pulling 16.04. Are the updated versions not on the registry yet?

**Comment by Alexhuszagh** [comment]
> This is closed but i'm using latest and it is still pulling 16.04. Are the updated versions not on the registry yet?

They are, for `main` and `edge`. You may need to pull the image, since if the image exists, we don't automatically check for a newer version: `docker pull ghcr.io/cross-rs/$TARGET:main`.

**Comment by crazystylus** [comment]
I tried pulling `ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.5` which is greater than `v0.2.4` and it still uses `Ubuntu 16.04 Xenial`!!

```
root@d965fa0b314d:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
``

**Comment by Emilgardis** [comment]
0.2.5 is a backport, use `:main` instead for now, the change to 20.04 will be in `0.3.0`

**Comment by pvshvp-oss** [comment]
> 0.2.5 is a backport, use `:main` instead for now, the change to 20.04 will be in `0.3.0`

Could you please provide me a brief summary of what I will need to do to add Ubuntu 22 support? I want to be able to use the Gtk4 packages from the distribution. I would like know how much effort is involved. If it just involves changing the base docker image's version, I will be able to create a custom image that I could use.

**Comment by Emilgardis** [comment]
@pvshvp-oss see https://github.com/cross-rs/cross/issues/1450#issuecomment-1967771164
