### ISSUE TITLE
How to pass rustflags / static compile ? 

### ISSUE THREAD

**Issue by hanusek** [cross-rs/cross#519]
Hello. I would like static compile libc with my program.
How do it?

**Cross.toml**
```
[target.arm-unknown-linux-gnueabihf]
image = "cross-armhf:lastest"
volumes = [
    "BUILD_DIR",
    "RUSTFLAGS"
]
rustflags = [
    "-C", "link-arg=-static",
    "-C", "target-feature=+crt-static"
]
```

**Comment by olitha** [comment]
Hi hanusek,

as far as I know you have 2 options:
you could just set them with the cargo configuration file described here https://doc.rust-lang.org/cargo/reference/config.html.
and create a config file `.cargo/config.toml`.

Or If you don't want to use the config, but pass the RUSTFLAGS env variable to the container, you should set them in your shell that you are calling cross from. You can then remove the rustflags entry from Cross.toml.
You have to use the `passthrough` key in Cross.toml and add `RUSTFLAGS` there. Note that no values are set in cross but only the variable name that will then be set to the value that are set in your shell (passed through).

**Comment by Alexhuszagh** [comment]
> Hi hanusek,
> 
> as far as I know you have 2 options: you could just set them with the cargo configuration file described here https://doc.rust-lang.org/cargo/reference/config.html. and create a config file `.cargo/config.toml`.
> 
> Or If you don't want to use the config, but pass the RUSTFLAGS env variable to the container, you should set them in your shell that you are calling cross from. You can then remove the rustflags entry from Cross.toml. You have to use the `passthrough` key in Cross.toml and add `RUSTFLAGS` there. Note that no values are set in cross but only the variable name that will then be set to the value that are set in your shell (passed through).

Unfortunately, this won't work, since `RUSTFLAGS` is ignored for cross-compilation. We've documented how to configure cargo when cross-compiling in the [wiki](https://github.com/cross-rs/cross/wiki/Configuration#cargo-configuration).

**Comment by Nuxij** [comment]
Any interest in making this a thing? Just not sure how to set some rust flags decoratively, but only for the cross compile.

**Comment by Emilgardis** [comment]
@Nuxij you can use the env var `CARGO_TARGET_${TARGET}_RUSTFLAGS`

**Comment by Nuxij** [comment]
And I can put that in `[workspace.metadata.cross.target.arm-unknown-linux-gnueabi.build.env]` ?

**Comment by Emilgardis** [comment]
No, you pass it as an environment variable, it is automatically forwarded, no need to change the config file

**Comment by Emilgardis** [comment]
So for you it would be `CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABI_RUSTFLAGS`

See https://doc.rust-lang.org/cargo/reference/config.html#targettriplerustflags and https://doc.rust-lang.org/cargo/reference/config.html#environment-variables

**Comment by Nuxij** [comment]
It would be much nicer to have all the config in the config file. 

`cross build --target xyz` already explains everything I mean to say, but now I have to conditionally at run time add flags like `if [[ $target == "something" ]]; MY_RUST_FLAGS=blablah; fi`

**Comment by Emilgardis** [comment]
The environment variable is already conditional, only applies when compiling for that target, but sure you can add it to the config like you wanted :)

**Comment by Nuxij** [comment]
I understand now thank you, I took too long to try and write my reply and you answered it with those links. Thanks for your patience and speed!
