### ISSUE TITLE
Failure when podman-docker is installed

### ISSUE THREAD

**Issue by ilya-zlobintsev** [cross-rs/cross#530]
If one has `podman-docker` installed (a wrapper for podman that emulates docker's CLI, needed for things like docker-compose to be compatible), cross fails:
```
cross build --release --target=aarch64-unknown-linux-gnu

Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
error: failed to open: /target/release/.cargo-lock

Caused by:
  Permission denied (os error 13)
```

It looks like cross is trying to use docker, but since my user doesn't have access to "docker" (the emulated interface) it fails. 

Without `podman-docker`, everything works perfectly fine using rootless podman containers.

Cross should probably either default to trying podman first and then falling back to docker, or have some sort of check so this doesn't happen.

**Comment by alexhunt7** [comment]
I can reproduce this on Fedora 31 with `podman` and `podman-docker`. This happens even when setting `CROSS_CONTAINER_ENGINE=podman`.

```
CROSS_CONTAINER_ENGINE=podman cross build --target aarch64-unknown-linux-gnu --release    
error: failed to create directory `/target/release`

Caused by:
  Permission denied (os error 13)
```

After uninstalling `podman-docker`, it works.

**Comment by alexhunt7** [comment]
It seems that `CROSS_CONTAINER_ENGINE` does not exist in the latest version that would be installed by `cargo install cross`. When building from master, it works with `podman-docker` installed and `CROSS_CONTAINER_ENGINE=podman` specified.

This is still a bit silly, as `podman-docker` is the most common way to use `podman`, and having it work by default would make much more sense. Perhaps a change to defaulting to `podman` first would remove the need to specify `CROSS_CONTAINER_ENGINE`.

In the meantime, can we get a new release, so `cargo install` defaults to a working version?

**Comment by alexhunt7** [comment]
Here's a PR to default to `podman` first. Thanks for the tips @ilyazzz

**Comment by ctron** [comment]
This is indeed weird, and pretty annoying. I would expect that providing the `CROSS_CONTAINER_ENGINE` override would force podman.
