### ISSUE TITLE
Running tests on *-apple-ios targets

### ISSUE THREAD

**Issue by Robert-Steiner** [cross-rs/cross#535]
Hi,
the [table](https://github.com/rust-embedded/cross#supported-targets) shows that the command `test` is supported for `*-apple-ios` targets (on a macOS host).
I tried to test a simple project with it, but the command always fails:

```
cross test --target x86_64-apple-ios         
info: downloading component 'rust-src'
info: installing component 'rust-src'
info: using up to 500.0 MiB of RAM to unpack components
Warning: `cross` does not provide a Docker image for target x86_64-apple-ios, specify a custom image in `Cross.toml`. Falling back to `cargo` on the host.
   Compiling test_cross v0.1.0 (/Users/robert/projects/test_cross)
    Finished test [unoptimized + debuginfo] target(s) in 3.24s
     Running target/x86_64-apple-ios/debug/deps/test_cross-b8eaa5221164d63b
dyld: attempt to run simulator program outside simulator (DYLD_ROOT_PATH not set)
error: test failed, to rerun pass '--bin test_cross'

Caused by:
  process didn't exit successfully: `/Users/robert/projects/test_cross/target/x86_64-apple-ios/debug/deps/test_cross-b8eaa5221164d63b` (signal: 6, SIGABRT: process abort signal)
```

Same for 
```
cross test --target aarch64-apple-ios 
info: downloading component 'rust-std' for 'aarch64-apple-ios'
info: installing component 'rust-std' for 'aarch64-apple-ios'
info: using up to 500.0 MiB of RAM to unpack components
 15.0 MiB /  15.0 MiB (100 %)   9.8 MiB/s in  1s ETA:  0s
Warning: `cross` does not provide a Docker image for target aarch64-apple-ios, specify a custom image in `Cross.toml`. Falling back to `cargo` on the host.
   Compiling test_cross v0.1.0 (/Users/robert/projects/test_cross)
    Finished test [unoptimized + debuginfo] target(s) in 0.94s
     Running target/aarch64-apple-ios/debug/deps/test_cross-f09c7c28a6ce0011
error: test failed, to rerun pass '--bin test_cross'

Caused by:
  could not execute process `/Users/robert/projects/test_cross/target/aarch64-apple-ios/debug/deps/test_cross-f09c7c28a6ce0011` (never executed)
```

Do I have to use a custom docker image for this?

Specs: 
- Rust: 1.49.0

**Comment by simlay** [comment]
I was just looking at the `README` that mentioned `*-apple-ios` works with `test`and was curious how it worked. In short, it actually doesn't I think.

To run tests on the iOS simulator, I'd recommend [`cargo-dinghy`'s iOS simulator support](https://github.com/sonos/dinghy/blob/main/docs/ios.md#simulator). Here's an [example of usage](https://github.com/sonos/dinghy/blob/c77cd8c6c0ebea38f046097e189acb498956ceda/.travis.sh#L58-L85).

**Comment by Alexhuszagh** [comment]
You've have to provide a custom wrapper for `CARGO_TARGET_X86_64-APPLE_IOS_RUNNER` to run the tests with `cargo`, but we do not provide a pre-built image for `x86_64-apple-ios` (although we do provide a Dockerfile for [aarch64-apple-ios](https://github.com/cross-rs/cross-toolchains#ios-targets) which requires your own iOS SDK), so this is outside the scope of `cross`.
