### ISSUE TITLE
error: failed to install component: 'rust-docs-x86_64-unknown-linux-gnu', detected conflict: '"share/doc/rust/html/std/keyword.self.html"'

### ISSUE THREAD

**Issue by avnerbarr** [cross-rs/cross#545]
running like so and getting a warning strait away:

```
cross build -p frontend --target x86_64-unknown-linux-musl
warning: toolchain '1.51.0-x86_64-unknown-linux-gnu' may not be able to run on this system.
warning: If you meant to build software to target that platform, perhaps try `rustup target add x86_64-unknown-linux-gnu` instead?
```

after a bit get this error:

```
error: failed to install component: 'rust-docs-x86_64-unknown-linux-gnu', detected conflict: '"share/doc/rust/html/std/keyword.self.html"'
error: couldn't install toolchain `1.51.0-x86_64-unknown-linux-gnu`
caused by: `"rustup" "toolchain" "add" "1.51.0-x86_64-unknown-linux-gnu"` failed with exit code: Some(1)
```

which version of rust is being used by cross? do i need to configure a specific version somehow?

**Comment by Alexhuszagh** [comment]
The version of Rust cross uses is the one on your host machine. You can use whatever toolchain you wish, for example, using `cross +stable build ...` or `cross +nightly build ...`. We merely mount cargo into the container, which with all the pre-installed tools, allows you to cross compile. It also auto-adds targets to the Rust toolchain if they're not already present.
