### ISSUE TITLE
 can't find crate for `core`

### ISSUE THREAD

**Issue by dosgo** [cross-rs/cross#564]
![image](https://user-images.githubusercontent.com/9545458/123542163-958d9d00-d77a-11eb-83f2-693abd1997ec.png)

Windows is not supported?

**Comment by burrbull** [comment]
Show
```
rustup show
```

**Comment by dosgo** [comment]
![image](https://user-images.githubusercontent.com/9545458/123576796-1db88480-d805-11eb-9cf6-2a101237c091.png)
Rustup show does not have this target. I don't understand! Isn't this based on docker? I have docker。

**Comment by burrbull** [comment]
Try:
```
rustup toolchain install mipsel-unknown-linux-gnu
```
and then rerun.

**Comment by dosgo** [comment]
rustup target add mipsel-unknown-linux-gnu   success
![Uploading 111.png…]()

**Comment by dosgo** [comment]
The http library fails to compile with hyper v0.14.4. If you use minreq to open https, openssl-sys (v0.9.65) fails to compile, and uses rustls ring v0.16.20 to compile fails.

**Comment by Alexhuszagh** [comment]
You should be able to use the vendored openssl or use the package manager to fix the issue with `openssl-sys`, as documented in [Recipes](https://github.com/cross-rs/cross/wiki/Recipes). Cross should automatically add new targets to rustup however.

**Comment by Alexhuszagh** [comment]
I'm unable to replicate this on the latest cross (v0.2.2), and both `openssl-sys` with the `vendored` and `hyper` v0.14.14 compile without issue. If you don't use the vendored option, you will have to install OpenSSL from [Ubuntu or Debian repositories](https://github.com/cross-rs/cross/wiki/FAQ#linking-external-libraries).

**Comment by rapiz1** [comment]
> Cross should automatically add new targets to rustup however.

I'm running into the same issue for cfg-if. Why rustup target add is needed?

**Comment by rapiz1** [comment]
It looks like `mipsel-unknown-linux-gnu` has been downgraded to tier 3 in rust 1.72

**Comment by Emilgardis** [comment]
Where did you find that information @rapiz1? Wondering if that's the cause for https://github.com/cross-rs/cross/issues/1336 also, but https://doc.rust-lang.org/stable/rustc/platform-support.html still shows it as t2

**Comment by Emilgardis** [comment]
Ah, you're right, platform doc is outdated https://github.com/rust-lang/rust/issues/115218

**Comment by rapiz1** [comment]
LoL someone in a rust telegram group told me. Looks like he's lurking in the community long enough to know that doc is outdated
