### ISSUE TITLE
Permanently enable scl in centos extending from x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by robertcorponoi** [cross-rs/cross#566]
I'm attempting to cross compile a library from Windows to Linux. However, since I need clang I have to create a custom image extending from `x86_64-unknown-linux-gnu`.

This initially led me to creating a Dockerfile that looks like:

```docker
FROM rustembedded/cross:x86_64-unknown-linux-gnu

RUN yum update && \
        yum install -y \
        libclang-dev \
        clang
```

However, this installs a version of clang lower than the version I need which is at least 3.9. Looking for a way to upgrade clang, I came across this StackOverflow post [How to install Clang and LLVM 3.9 on CentOS 7](https://stackoverflow.com/questions/44219158/how-to-install-clang-and-llvm-3-9-on-centos-7). Using it, I adjusted my Dockerfile to look like:

```docker
FROM rustembedded/cross:x86_64-unknown-linux-gnu

RUN yum update && \
        yum install -y \
        scm-utils \
        centos-release-scl \
        llvm-toolset-7
```

However, since I am new to CentOS, I wasn't aware of the SCL toolsets and how they worked so that didn't work. Since when cross-compiling I don't have access to the shell and can't enable the toolset with `scl enable llvm-toolset-7 bash`, I attempted to add it to `.bash-profile` so that it would be enabled by default like so:

```docker
FROM rustembedded/cross:x86_64-unknown-linux-gnu

RUN yum update -y && \
    yum install centos-release-scl -y && \
    yum install llvm-toolset-7 -y && \
    yum install scl-utils -y && \
    echo "source scl_source enable llvm-toolset-7" >> ~/.bash_profile
```

This also didn't work so I tried adding that line to several other places like `.bashrc` and `/profile`. It was later pointed out to me that it doesn't work because `.bash_profile` will only be called on a login shell so it won't be used when trying to cross-compile.

Is there any way to do this so that the toolset is enabled and cross has access to the upgraded clang? Or is there just an entirely different recommended way of doing this?

Note: I also tried building clang from source but I needed an upgraded version of gcc which involves the same process of using scl and it takes a long time to build.

**Comment by jszwedko** [comment]
I was able to get this working by setting the libclang environment variables in the Dockerfile:

```
FROM rustembedded/cross:x86_64-unknown-linux-gnu

RUN yum update -y && \
    yum install centos-release-scl -y && \
    yum install llvm-toolset-7 -y

ENV LIBCLANG_PATH=/opt/rh/llvm-toolset-7/root/usr/lib64/ \
  LIBCLANG_STATIC_PATH=/opt/rh/llvm-toolset-7/root/usr/lib64/ \
  CLANG_PATH=/opt/rh/llvm-toolset-7/root/usr/bin/clang
```

**Comment by temrix** [comment]
The above works, however I prefer "Method 2" of https://austindewey.com/2019/03/26/enabling-software-collections-binaries-on-a-docker-image/ .

**Comment by Alexhuszagh** [comment]
This should be documented in the wiki.

**Comment by Alexhuszagh** [comment]
This is now [documented](https://github.com/cross-rs/cross/wiki/Recipes#using-clang-and-software-collections-on-centos7), and the wiki is soon to be referenced in the README once #796 merges.
