### ISSUE TITLE
Use qualified Docker image names

### ISSUE THREAD

**Issue by link2xt** [cross-rs/cross#571]
Currently unqualified `rustembedded/*` image names are used instead of `docker.io/rustembedded/*`, so I have to add
```
unqualified-search-registries = ["docker.io"]
```
to `/etc/containers/registries.conf`.

I am using `podman`, which has no default registries and discourages using unqualified names.

**Comment by ryankurte** [comment]
sorta related, when we have qualified names it'd be neat to also push the containers to ghcr.io to improve the fetch speed with actions (dockerhub is slow and the new API limits are, rough)

**Comment by Emilgardis** [comment]
The images are now (to-be) hosted on ghcr.io/cross-rs/<target>
