### ISSUE TITLE
C compiler cannot create executables

### ISSUE THREAD

**Issue by luigi311** [cross-rs/cross#576]
I keep running into and not sure how to resolve it. 
```
checking for x86_64-unknown-linux-musl-gcc... x86_64-unknown-linux-musl-gcc
checking whether the C compiler works... no
configure: error: C compiler cannot create executables
``` 

Ive created my own image that extends the cross base located here
https://github.com/luigi311/av1an-cross
that adds some dependencies to build 
https://github.com/luigi311/Av1an/tree/deploy

I am trying to cross compile to 
linux x86_64, aarch64
windows x86_64
macos x86_64, aarch64
but for now just trying to get linux building. I was able to get it to build natively without cross if I installed all the dependencies in the action image but only for x86_64 so I am going the cross route with the dependencies built into here but I can not get pass the C compiler cannot create executables.

**Comment by sei0o** [comment]
In my case that is because the name of the executable is `x86_64-linux-musl-gcc` instead of `x86_64-unknown-linux-musl-gcc`. I have no idea whether this is a bug of `cross`, but a simple workaround is [inherit the default Docker container](https://github.com/rust-embedded/cross#custom-docker-images) and explicitly designate where the compiler and the linker are located (fit below to your target architecture): 

```Dockerfile
FROM rustembedded/cross:arm-unknown-linux-gnueabihf-0.2.1

ENV CC=arm-linux-gnueabihf-gcc
ENV AR=arm-linux-gnueabihf-ar

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install --assume-yes libfoo:arm64
```

**Comment by Alexhuszagh** [comment]
This no longer reproduces with the latest main builds (and almost certainly as of v0.2.2):

```bash
$ git clone https://github.com/Alexhuszagh/rust-c-hello-world
$ cd rust-c-hello-world
$ cross build --target x86_64-unknown-linux-musl
   Compiling hellopp v0.1.0 (/project)
    Finished dev [unoptimized + debuginfo] target(s) in 0.80s
$ cd ..
$ git clone https://github.com/cross-rs/rust-cpp-hello-word
$ cd rust-cpp-hello-word
$ cross build --target x86_64-unknown-linux-musl
   Compiling hellopp v0.1.0 (/home/ahuszagh/Desktop/cross/rust-cpp-hello-word)
    Finished dev [unoptimized + debuginfo] target(s) in 0.75s
```
