### ISSUE TITLE
iOS compilation support on non-macOS hosts

### ISSUE THREAD

**Issue by Moxinilian** [cross-rs/cross#579]
It is possible to compile applications for iOS from Linux using [a port of Apple’s cctools for Linux](https://github.com/tpoechtrager/cctools-port). The process is a bit complicated but looks fairly easy to automate. Maybe `cross` could support it.

The Godot documentation has [a page describing how to build Godot for iOS on Linux](https://docs.godotengine.org/en/stable/development/compiling/cross-compiling_for_ios_on_linux.html) for further information.

About the terms of use and disapproval from Apple of it all: it actually seems to be okay, see Godot link.

**Comment by Alexhuszagh** [comment]
We've added support for the `aarch64-apple-ios` in [cross-toolchains](https://github.com/cross-rs/cross-toolchains#apple-targets), which provides a Dockerfile for you to build your own image. We cannot distribute pre-built images since they contain the iOS SDK, but can be built as follows:

```bash
cargo build-docker-image aarch64-apple-ios-cross \
  --build-arg 'IOS_SDK_URL=$URL'
```

**Comment by Moxinilian** [comment]
Amazing! Thank you for all the excellent work.
