### ISSUE TITLE
Explain abscense of OpenSSL in README

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#580]
Readme should mention why OpenSSL is not in image, provide solutions (i.e rustsl), and provide a workaround by requiring user to maintain an image with OpenSSL-dev installed.

Related:
https://github.com/rust-embedded/cross/issues/565

**Comment by snowpoke** [comment]
Yes please 🥺

I'm setting up my first pipeline at the moment, and as a basic test I thought I'd have my pipeline compile cargo.
cargo happens to require OpenSSL, and I spent the past days thinking I was doing some fundamental mistake regarding dependencies.

As far as I understood, compiling cargo is considered a very basic test, and cross not passing this test with its default setup should be explained somewhere, in my opinion.

**Comment by Alexhuszagh** [comment]
This is documented now in the [wiki](https://github.com/cross-rs/cross/wiki/Recipes#openssl), at least, for how to create an image with OpenSSL installed or how to use the vendored OpenSSL. Using external dependencies is also [documented](https://github.com/cross-rs/cross/wiki/FAQ#linking-external-libraries), however, I believe the wiki should be referenced from the README and some of the duplicated information should be removed from the README.

**Comment by Alexhuszagh** [comment]
Documented on the [wiki](https://github.com/cross-rs/cross/wiki/FAQ#openssl-is-not-installed).

**Comment by Emilgardis** [comment]
The reason why it's not included is not mentioned though, I feel like we could still do it, but thats minor I think

**Comment by Alexhuszagh** [comment]
I feel like it was explained: that it was the source of numerous bugs while maintaining images.

> Why isn't OpenSSL installed? Maintaining images with OpenSSL proved to be a source of numerous bugs (see [#229](https://github.com/cross-rs/cross/issues/229) and [#332](https://github.com/cross-rs/cross/pull/322)), and only some images provide OpenSSL to begin with.

I did fail the hotlinks, so I've restored those.

**Comment by Emilgardis** [comment]
I meant in the readme, that description is good though!
