### ISSUE TITLE
`--target-dir` results in `failed to create directory /target/release`

### ISSUE THREAD

**Issue by giggio** [cross-rs/cross#581]
Cross is running docker with `--user`, and when you use `--target-dir` it adds a volume mount from the directory to `/target`, like so:

```bash
docker run <...> -v mytargetdir:/target:Z <...>
```

The `/target` directory will be owned by root, and cross will fail to create anything there.

**Comment by Emilgardis** [comment]
This shouldn't happen due to https://github.com/rust-embedded/cross/blob/a1ca96d787c7bbe1c2f4971de34de24a6974572a/src/docker.rs#L77-L79 which has been a thing since the first release.

What version of cross are you using?

**Comment by giggio** [comment]
I'm on:

````
❯ cross --version
cross 0.2.1
cargo 1.54.0 (5ae8d74b3 2021-06-22)
````

I was able to reproduce the problem with `--verbose`. This is what I get when I run `cross build --target x86_64-unknown-linux-musl --target-dir zcross --verbose`:

````
+ "rustc" "--print" "sysroot"
+ "rustup" "toolchain" "list"
+ "rustup" "toolchain" "add" "nightly-x86_64-unknown-linux-gnu"
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.56.0-nightly (5a19ffe1c 2021-08-13)

info: checking for self-updates
+ "rustup" "target" "list" "--toolchain" "nightly-x86_64-unknown-linux-gnu"
+ "rustup" "component" "list" "--toolchain" "nightly-x86_64-unknown-linux-gnu"
+ "/usr/bin/docker" "run" "--userns" "host" "-e" "PKG_CONFIG_ALLOW_CROSS=1" "--rm" "--user" "1000:1000" "-e" "XARGO_HOME=/xargo" "-e" "CARGO_HOME=/cargo" "-e" "CARGO_TARGET_DIR=/target" "-e" "USER=user" "-e" "CROSS_RUNNER=" "-v" "/home/user/.xargo:/xargo:Z" "-v" "/home/user/.cargo:/cargo:Z" "-v" "/cargo/bin" "-v" "/home/user/p/examples/minirust:/project:Z" "-v" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu:/rust:Z,ro" "-v" "zcross:/target:Z" "-w" "/project" "-i" "-t" "rustembedded/cross:x86_64-unknown-linux-musl-0.2.1" "sh" "-c" "PATH=$PATH:/rust/bin cargo build --target x86_64-unknown-linux-musl --target-dir /target --verbose"
error: failed to create directory `/target/debug`

Caused by:
  Permission denied (os error 13)
````

From there, I ran the docker command, but swapped cargo build with bash:

````
$ "/usr/bin/docker" "run" "--userns" "host" "-e" "PKG_CONFIG_ALLOW_CROSS=1" "--rm" "--user" "1000:1000" "-e" "XARGO_HOME=/xargo" "-e" "CARGO_HOME=/cargo" "-e" "CARGO_TARGET_DIR=/target" "-e" "USER=user" "-e" "CROSS_RUNNER=" "-v" "/home/user/.xargo:/xargo:Z" "-v" "/home/user/.cargo:/cargo:Z" "-v" "/cargo/bin" "-v" "/home/user/p/examples/minirust:/project:Z" "-v" "/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu:/rust:Z,ro" "-v" "zcross:/target:Z" "-w" "/project" "-i" "-t" "rustembedded/cross:x86_64-unknown-linux-musl-0.2.1" bash
groups: cannot find name for group ID 1000
I have no name!@e5848d8f1be0:/project$ ls -la /target/
total 8
drwxr-xr-x 2 root root 4096 Aug 14 01:04 .
drwxr-xr-x 1 root root 4096 Aug 14 01:07 ..
````

As you can see, `/target` is owned by root.

The `zcross` directory (the target dir) was created at the cwd as expected, and is owned by my user.

What seems to be happening is that the command is trying to use a relative value for the volume host directory, but that is not allowed, you need to use an absolute path, otherwise the name is interpreted as a name, and a volume is created. I checked and there is now a volume named `zcross` in docker. See from [Docker docs](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems):

> The host-src can either be an absolute path or a name value. If you supply an absolute path for the host-src, Docker bind-mounts to the path you specify. If you supply a name, Docker creates a named volume by that name.

And as I wrote this I found a workaround, if I specify the full path it works:

````bash
cross build --target x86_64-unknown-linux-musl --target-dir `pwd`/zcross
````

I believe this should be handled automatically by cross, to mimic the behavior from cargo build.
