### ISSUE TITLE
Build broken with Rust 1.46.0

### ISSUE THREAD

**Issue by asomers** [cross-rs/cross#603]
A recent bug in object (https://github.com/gimli-rs/object/issues/394) has caused that crate's build to break with Rust 1.46.0.  And by extension, it breaks cross, too.  You might consider locking the object version to 0.26.0 to fix the build, until the object project fixes it.

**Comment by Alexhuszagh** [comment]
We no longer support Rust <= 1.58.1 (at the time this issue was created, we did support 1.42.0+). Closing this since I believe it's no longer relevant, please let me know if this is not the case.

**Comment by Emilgardis** [comment]
The issue was introduced with 1.46.0 but persists with 0.26.0, but has since been fixed. So it should be closed
