### ISSUE TITLE
CI can not push to DockerHub

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#607]
CI is currently [unable to push](https://dev.azure.com/rust-embedded/cross/_build/results?buildId=955&view=logs&j=e6deedce-f53c-5dcc-524e-14349f140ffd&t=84c95e2c-b119-54b2-30cb-3663d0087f10) to DH as it used a password, password authentication was disabled sometime lately.

We need to update the specified password secret to use a token instead.

**Comment by adamgreig** [comment]
This seems tricky: as far as I can tell, DockerHub recently changed their pricing model so free teams can only have 3 members and also you need to use a specific account's personal access token to have CI push images. Together that means we'd probably need to remove 4 of the 6 current team members, make a new machine account (is that allowed?), add it to the team, and use its PAT in CI.

Ooooor swap to GHA+GHCR.
