### ISSUE TITLE
Add possibility to reduce memory and cpu

### ISSUE THREAD

**Issue by Kaiser1989** [cross-rs/cross#638]
Is there any possibility to set -m and -cpus command to docker run? If not, it would be nice if one can adjust the docker resources:
https://docs.docker.com/config/containers/resource_constraints/

It would be best, if this can be configured via env vars. We are running cross on our CI and run into some resource issues.

**Comment by Emilgardis** [comment]
you should be able to use the env `DOCKER_OPTS` to specify your own options

let us know if this works for you!

**Comment by Kaiser1989** [comment]
Thanks, exactly what i was looking for!
