### ISSUE TITLE
alsa library not resolved correctly for arm target

### ISSUE THREAD

**Issue by hildebro** [cross-rs/cross#641]
I'm trying to compile an audio program for a raspberry pi 1. The program requires the `alsa` crate. To compile I ran:

```
cross build --target arm-unknown-linux-gnueabihf
```
which work out of the box before I introduced the `alsa` dependency. afterwards I got an error about alsa missing on the cross docker container. Then I followed the instructions in this repo to build a custom docker image and installed required packages as described in [this post](https://stackoverflow.com/questions/57037550/alsa-linking-when-cross-compiling-rust-program-for-arm). My `Dockerfile`:

```
FROM rustembedded/cross:arm-unknown-linux-gnueabihf

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install libasound-dev -y && \
    apt-get install libasound-dev:armhf -y
```

and this `Cross.toml`:
```
[target.arm-unknown-linux-gnueabihf]
image = "custom-cross"
```

and this `.cargo/config`:
```
[build]

[target.arm-unknown-linux-gnueabihf.libasound]
linker = "arm-linux-gnueabihf-gcc"
rustc-link-lib = ["libasound"]
rustc-link-search = ["/usr/lib/arm-linux-gnueabihf"]
```

However I still get this exception during compilation:
```
/usr/lib/x86_64-linux-gnu/libasound.so: file not recognized: file format not recognized
          collect2: error: ld returned 1 exit status
```

So for some reason, the problem that the aforementioned post described ("Depending on the order it links, it may try to use the x86 version instead of the armhf version.") is happening to me even thought I configured cargo to run the arm version. I checked `ls /usr/lib` on my docker image and it does show the arm folder containing the desired libasound package. It looks to me like `.cargo/config` and/or `--features "alsa-backend"` is ignored by `cross`. I also tried to copy the contents of `.cargo/config` into `Cross.toml`, but that didn't help.

Do you have any suggestion on this?

**Comment by Dumdidldum** [comment]
i am having the same issue

**Comment by Dumdidldum** [comment]
hello, so if you are still facing this issue i found out how to build with alsa
here is my `Dockerfile`:
```
FROM rustembedded/cross:arm-unknown-linux-gnueabihf-0.2.1

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN dpkg --add-architecture armhf
RUN apt-get update && apt-get -y install libasound2-dev:armhf

ENV CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_RUSTFLAGS="-L /usr/lib/arm-linux-gnueabihf $CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_RUSTFLAGS"
ENV CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_RUSTFLAGS="-C link-args=-Wl,-rpath-link,/usr/lib/arm-linux-gnueabihf $CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_RUSTFLAGS"
```

The critical part are the CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_RUSTFLAGS env variables.
Because cargo does not care about the normal RUSTFLAGS as soon as you specify a target.

**Comment by hildebro** [comment]
@Dumdidldum cool thanks for letting me know. I'll try it out when I get the chance
