### ISSUE TITLE
Permission denied error - rootless docker

### ISSUE THREAD

**Issue by Dumdidldum** [cross-rs/cross#648]
hello, i have set up rootless docker according to this guide:
https://docs.docker.com/engine/security/rootless/

now i can no longer build with cross, as it always results in this error:
```
error: failed to create directory `/target/debug`

Caused by:
  Permission denied (os error 13)
```

version:
```
cross 0.2.1
cargo 1.59.0 (49d8809dc 2022-02-10)
```

**Comment by reitermarkus** [comment]
Try running with `--verbose` to get more details on what happens. Also, try installing `cross` from the `main` branch since 0.2.1 is quite old at this point.

**Comment by Alexhuszagh** [comment]
Related to #889.
