### ISSUE TITLE
The example to create a custom Docker image doesn't work

### ISSUE THREAD

**Issue by guihkx** [cross-rs/cross#649]
Trying to follow [this](https://github.com/cross-rs/cross#custom-docker-images) section from the README yields me this:

```
$ docker build -t test .
Sending build context to Docker daemon  231.4kB
Step 1/2 : FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest
unauthorized
```

The error message seems a bit odd to me (though I'm still learning Docker), considering that I've already authenticated myself and other images (such as`ghcr.io/rse-ops/gcc-ubuntu-20.04:gcc-7.3.0` ) are downloaded just fine.

Any help is appreciated, thanks.

**Comment by reitermarkus** [comment]
We just migrated to GHCR and there has not yet been a stable release yet, so there is no `latest` tag for this image yet.

You can try `ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main` instead.

**Comment by Emilgardis** [comment]
actually, we forgot to make them public :)

**Comment by Emilgardis** [comment]
Made aarch64-unknown-linux-gnu public now, let us know if it works better now, use the `main` or `edge` tag for now

**Comment by guihkx** [comment]
Oh, that explains it 😄 

(Side: @reitermarkus using that URL didn't work either, but as pointed out by @Emilgardis , I suppose it's due to it no being public, so I'll just wait)

Thanks guys

**Comment by reitermarkus** [comment]
I assume we can make them public by default using some label since the once which are private show `Label: Private`.

**Comment by guihkx** [comment]
Thank you very much @Emilgardis, it does work now using the`main` tag.

This is a bit awkward though, I was actually more interested in the  `x86_64-unknown-linux-gnu` image because I want to compile my program using an old glibc version than I have on my personal machine, so if you could make that public also... 😁 

I'm only interested in having a custom image because one of the dependencies of this Rust program calls `python3` in the build process for some reason.

**Comment by Emilgardis** [comment]
We can make them public by default by not enabling private packages, I'll do that soon when I'm done with chaning all of them

**Comment by Emilgardis** [comment]
Doesn't seem like it's possible to disable private packages, if we add new packages we'll have to make sure to change them into public packages/images

**Comment by detly** [comment]
Is this why I get:

```none
⚬ docker pull ghcr.io/cross-rs/aarch64-unknown-linux-gnu
Using default tag: latest
Error response from daemon: manifest unknown
```

Or is that something else entirely?

**Comment by detly** [comment]
Things I have tried:

1. Making a custom image for `cross` using the instructions in the README. Failed because the instructions say to use `ghcr.io/cross-rs/x86_64-unknown-linux-musl:latest` image, which doesn't seem to exist
2. They *do* exist with the tag `:main`, but don't have `dpkg` or `apt-get` (??)
3. It worked when I based the image on `rustembedded/cross:x86_64-unknown-linux-musl`

**Comment by Emilgardis** [comment]
We've switched to centos for now in x86_64-unkown-linux-gnu, see #680 for switching back. Long story short, apt and dpkg is not available because its not debian/ubuntu anymore. The instructions are for aarch64 so it uses debian. use `yum` on centos

**Comment by Emilgardis** [comment]
Rereading your message @detly I see I missed the fact you're trying to use the `musl` image, the `musl` image do have apt installed, so the only thing you'd need to do is figure out why you can use them.

```
$ docker run --rm -it ghcr.io/cross-rs/x86_64-unknown-linux-musl:edge apt-get -v
apt 2.0.6 (amd64)
```
