### ISSUE TITLE
add way to manually trigger a workflow run for certain target

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#651]
This should be possible with

[workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) and a bot/app/workflow that triggers on a comment

* A comment is made on a pr. `@ghost try target: x86_64-unknown-linux-gnu` or `@ghost try target: x86_64.*`
* The comment is picked up and eventually triggers `docker-image` for the pr rebased on current main, and skipping all targets in the matrix except for matched targets.

**Comment by reitermarkus** [comment]
For triggering via a comment, I have used https://github.com/peter-evans/slash-command-dispatch previously.

**Comment by reitermarkus** [comment]
Apparently bors supports arguments: https://github.com/bors-ng/bors-ng/blob/e8a5757e01cd4b32fae8b200ad48f38685b35bbf/lib/web/command.ex#L7-L14

So we could make `bors try --target <target>` work.
