### ISSUE TITLE
error/panic on fallback to host `cargo` or when in CI environment

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#659]
https://github.com/cross-rs/cross/blob/eaeff5b3fed37c4762a82b27870c1543acdab72b/src/main.rs#L344-L350

**Comment by jpmckinney** [comment]
I would also like an option to error/panic on fallback. This is especially useful in CI. I guess for now I can do:

```
      - id: cross
        run: echo "stderr=$(cross build --release --target ${{ matrix.target }})" 2>> $GITHUB_OUTPUT
      - if: steps.cross.outputs.stderr != ''
        run: |
          echo "${{ steps.cross.outputs.stderr }}"
          exit 1
```

**Comment by Emilgardis** [comment]
thats something I hadn't considered, maybe providing a way to not allow any warnings would be helpful.

We definitely want this included in the next release
