### ISSUE TITLE
Create documentation for Cross.toml

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#664]
### Discussed in https://github.com/cross-rs/cross/discussions/532

We should add some kind of specification, this should be helped with #657

**Comment by Alexhuszagh** [comment]
`Cross.toml` is now extensively documented on the [wiki](https://github.com/cross-rs/cross/wiki/Configuration#config-file), which includes a link to a sample configuration [file](https://github.com/cross-rs/wiki_assets/blob/main/Configuration/Cross.toml) where every variable is explained in depth.
