### ISSUE TITLE
When compiling binary from git source, use `main`/`edge` version instead of `x.y.z`

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#666]
When compiling from source, i.e "git clone .. && cargo install --locked --path ." (not `cargo install cross --locked`) we should by default use `main` branch images instead of `x.y.z`

**Comment by reitermarkus** [comment]
I guess in that case we also want the `cross` version to include the commit hash, something like `x.y.z-git.fffffff`.

**Comment by Emilgardis** [comment]
It already does! (when available)

**Comment by Emilgardis** [comment]
I think I misunderstood your remark. Yes, if we'd want every cross "git"-version to use their specific built images we'd do that, but I think the effort is not needed. If you're installing from git, you probably know what you want and are fine with just using `:main` as the tag.

**Comment by reitermarkus** [comment]
No, I didn't mean to use the images specific to that commit. I meant simply to differentiate the output of `cross --version` for use in bug reports etc.

**Comment by Emilgardis** [comment]
I see! We do that already thankfully :D
