### ISSUE TITLE
Rationale for Using x86_64-linux-gnu with CentOS?

### ISSUE THREAD

**Issue by Alexhuszagh** [cross-rs/cross#669]
Looking at the source code for cross, the only image that uses a CentOS base image is [x86_64-unknown-linux-gnu](https://github.com/cross-rs/cross/blob/main/docker/Dockerfile.x86_64-unknown-linux-gnu), and the only relevant commit I can find for this addition is [here](https://github.com/cross-rs/cross/commit/b0f4bd76950c013dcf89b3ea3e961c30cac5a898), which has no explanation of the rationale.

Since CentOS 8 is EOL, and CentOS 7 is discontinued, it might be preferable to use Ubuntu as a base image for `x86_64-unknown-linux-gnu`, which would also simplify other issues like #517 (and the associated PR #591). If there is a good reason to keep CentOS as a base image, I would love to know, otherwise, I am happy to submit a PR to remove the CentOS logic and simplify package installation, image upgrades, etc.

**Comment by Emilgardis** [comment]
The rationale is that people are still using CentOS 7, see #455 for example.

I can't find any info about CentOS 7 being unsupported now, if/when it is i think we'd gladly drop support for it

**Comment by Alexhuszagh** [comment]
Yeah maybe my wording was wrong: CentOS 8 is EOL and CentOS 7 is receiving security updates. I'll work around this to upgrade the Ubuntu base image, thank you.
