### ISSUE TITLE
Compile Rust application for Windows with cross and sqlite3 dependecy

### ISSUE THREAD

**Issue by buxx** [cross-rs/cross#676]
Hello !

I'm trying to compile [my Rust application](https://github.com/buxx/trsync) for Windows with [cross](https://github.com/cross-rs/cross). I got this error :

```
   Compiling trsync v0.1.3 (/project)
error: linking with `x86_64-w64-mingw32-gcc` failed: exit status: 1
  |
  = note: "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "/rust/lib/rustlib/x86_64-pc-windows-gnu/lib/rsbegin.o" "/target/x86_64-pc-windows-gnu/debug/deps/trsync-36594acb4f0db109.trsync.69d5ec1a-cgu.0.rcgu.o" [...] "-Wl,--gc-sections" "-no-pie" "-nodefaultlibs" "/rust/lib/rustlib/x86_64-pc-windows-gnu/lib/rsend.o"
  = note: /usr/bin/x86_64-w64-mingw32-ld: cannot find -lsqlite3
          collect2: error: ld returned 1 exit status
          

error: could not compile `trsync` due to previous error
```

How to compile my application for Windows with `cross` ?

**Comment by Emilgardis** [comment]
Hi!

You'll need to provide a custom docker image that includes sqlite. See the readme 
https://github.com/cross-rs/cross#custom-docker-images


Note that the example won't work right now as the `latest` tag has not been pushed to yet, use a specific sha or simply the `main` tag instead in the from step. Or use the old dockerhub images

Note that if you decide to compile cross from current main branch, be aware that it's currently broken on windows pending #665

**Comment by DanielRivasMD** [comment]
Hi, I have a rather similar problem, and it is unclear which docker image I should use to compile. To be concrete: compile using cross from OSX to Windows with sqlite dependency. Much appreciated
