### ISSUE TITLE
Validate README.md supported targets with CI

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#686]
We should investigate if it would be possible to validate that the supported target table is correct

https://github.com/cross-rs/cross#supported-targets

**Comment by Alexhuszagh** [comment]
I've created a very rudimentary attempt at this in [target_info](https://github.com/Alexhuszagh/cross/tree/target_info) (only partially working on Android, and works for a few tested musl targets) to auto-generate a table similar to the one in README to compare and validate the information. This might also simplify the validation of the versions in #591.

The use of the script is quite simple (and a wrapper with many targets would be provided to extract info for all targets):

```bash
$ export TARGET=aarch64-unknown-linux-musl
$ docker run -e TARGET ghcr.io/cross-rs/"$TARGET":main bash -c "`cat extract_target_info.sh`"
| `aarch64-unknown-linux-musl`         | 1.2.0  | 9.2.0   | ✓   | 5.1.0 |
```

How this works is it queries the version information from GCC (or Clang), detects if Qemu is present and if so, gets the Qemu version. and determines if the command provided by `CXX_$target` exists, and if so, says there is C++ support. For libc, it's a bit more complicated, but most libc libraries are executable (especially musl), or have version info attached to them (glibc). For glibc, we might have a library like `libc-2.31.so`, or glibc 2.31. For musl, we can just execute the libc (using qemu if required) and extract  the version info.

This is then formatted to the desired output.

**Comment by Emilgardis** [comment]
Awesome!

Something I just realised, we should/could label the images with the different version

**Comment by Alexhuszagh** [comment]
That might be easier. I can get the libc versions for everything except FreeBSD pretty easily, and FreeBSD isn't **hard**, but the libc reported in the README is the base release (which is quite different than the symbol libc version).

For example, for the current base release of 12.3, we would get `FBSD_1.5` based on [Symbol Versioning](https://wiki.freebsd.org/SymbolVersioning).

So for this and Android, I'm not sure what the correct output should be. For FreeBSD, is the correct libc version `12.3` or `1.5`? And for Android, I'm currently reporting the LLVM version, but should I report the NDK version?
