### ISSUE TITLE
error: failed to create directory `/target/debug`

### ISSUE THREAD

**Issue by qxqxq** [cross-rs/cross#693]
MacBookPro:xdls qxq$ cross build --target aarch64-unknown-linux-gnu
WARNING: the sysroot can't be built for the Stable channel. Switch to nightly.
error: failed to create directory `/target/debug`

Caused by:
  No such file or directory (os error 2)

MacBookPro:xdls qxq$ cross build --target aarch64-unknown-linux-gnu --verbose
+ "rustc" "--print" "sysroot"
+ "rustup" "toolchain" "list"
+ "rustup" "target" "list" "--toolchain" "stable-x86_64-unknown-linux-gnu"
+ "rustup" "component" "list" "--toolchain" "stable-x86_64-unknown-linux-gnu"
+ "/usr/local/bin/docker" "run" "--userns" "host" "-e" "PKG_CONFIG_ALLOW_CROSS=1" "--rm" "--user" "501:20" "-e" "XARGO_HOME=/xargo" "-e" "CARGO_HOME=/cargo" "-e" "CARGO_TARGET_DIR=/target" "-e" "USER=qxq" "-e" "CROSS_RUNNER=" "-v" "/Users/qxq/.xargo:/xargo:Z" "-v" "/Users/qxq/.cargo:/cargo:Z" "-v" "/cargo/bin" "-v" "/Users/qxq/Desktop/xdls:/project:Z" "-v" "/Users/qxq/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:/rust:Z,ro" "-v" "/Users/qxq/Desktop/xdls/target:/target:Z" "-w" "/project" "-i" "-t" "rustembedded/cross:aarch64-unknown-linux-gnu-0.2.1" "sh" "-c" "PATH=$PATH:/rust/bin xargo build --target aarch64-unknown-linux-gnu --verbose"
+ "rustc" "--print" "sysroot"
WARNING: the sysroot can't be built for the Stable channel. Switch to nightly.
+ "cargo" "build" "--target" "aarch64-unknown-linux-gnu" "--verbose"
error: failed to create directory `/target/debug`

Caused by:
  No such file or directory (os error 2)

A few days ago it was ok, but today it was suddenly wrong.
Thanks!

**Comment by Emilgardis** [comment]
this seems like a docker or file perm issue, can you try to do `docker run -userns host -v "/Users/qxq/Desktop/xdls/target:/target:Z" --rm -it ubuntu mkdir /target/debug`

**Comment by qxqxq** [comment]
MacBookPro:~ qxq$ docker run --userns host -v "/Users/qxq/Desktop/xdls/target:/target:Z" --rm -it ubuntu mkdir /target/debug
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
8527c5f86ecc: Pull complete 
Digest: sha256:18b083992355354958fd861c9f89b393f34d27442c07fa7492a5dbbd516b1c9a
Status: Downloaded newer image for ubuntu:latest
mkdir: cannot create directory '/target/debug': File exists



There seems to be no problem now.

-----------------------------------------------

> 这似乎是一个码头工人或文件烫发问题，你能试试吗`docker run -userns host -v "/Users/qxq/Desktop/xdls/target:/target:Z" --rm -it ubuntu mkdir /target/debug`

**Comment by qxqxq** [comment]
Today that question doesn't come up. Now there are other problems.

```
MacBookPro:xdls qxq$ cross build --target aarch64-unknown-linux-gnu --verbose
+ "rustc" "--print" "sysroot"
+ "rustup" "toolchain" "list"
+ "rustup" "target" "list" "--toolchain" "stable-x86_64-unknown-linux-gnu"
+ "rustup" "component" "list" "--toolchain" "stable-x86_64-unknown-linux-gnu"
+ "/usr/local/bin/docker" "run" "--userns" "host" "-e" "PKG_CONFIG_ALLOW_CROSS=1" "--rm" "--user" "501:20" "-e" "XARGO_HOME=/xargo" "-e" "CARGO_HOME=/cargo" "-e" "CARGO_TARGET_DIR=/target" "-e" "USER=qxq" "-e" "CROSS_RUNNER=" "-v" "/Users/qxq/.xargo:/xargo:Z" "-v" "/Users/qxq/.cargo:/cargo:Z" "-v" "/cargo/bin" "-v" "/Users/qxq/Desktop/xdls:/project:Z" "-v" "/Users/qxq/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:/rust:Z,ro" "-v" "/Users/qxq/Desktop/xdls/target:/target:Z" "-w" "/project" "-i" "-t" "rustembedded/cross:aarch64-unknown-linux-gnu-0.2.1" "sh" "-c" "PATH=$PATH:/rust/bin xargo build --target aarch64-unknown-linux-gnu --verbose"
+ "rustc" "--print" "sysroot"
WARNING: the sysroot can't be built for the Stable channel. Switch to nightly.
+ "cargo" "build" "--target" "aarch64-unknown-linux-gnu" "--verbose"
       Fresh version_check v0.9.4
       Fresh autocfg v1.1.0
       Fresh smallvec v1.8.0
       Fresh pin-project-lite v0.2.8
       Fresh scopeguard v1.1.0
       Fresh futures-sink v0.3.21
       Fresh once_cell v1.10.0
       Fresh pin-utils v0.1.0
       Fresh futures-io v0.3.21
       Fresh slab v0.4.5
       Fresh ppv-lite86 v0.2.16
       Fresh cfg-if v1.0.0
       Fresh percent-encoding v2.1.0
       Fresh matches v0.1.9
       Fresh tinyvec_macros v0.1.0
       Fresh adler v1.0.2
       Fresh alloc-no-stdlib v2.0.3
       Fresh time-macros v0.2.4
       Fresh num_threads v0.1.5
       Fresh bitflags v1.3.2
       Fresh ryu v1.0.9
       Fresh bytes v1.1.0
       Fresh local-waker v0.1.2
       Fresh base64 v0.13.0
       Fresh regex-syntax v0.6.25
       Fresh paste v1.0.7
       Fresh fnv v1.0.7
       Fresh hashbrown v0.11.2
       Fresh unicode-bidi v0.3.7
       Fresh itoa v1.0.1
       Fresh convert_case v0.4.0
       Fresh mime v0.3.16
       Fresh pkg-config v0.3.24
       Fresh httpdate v1.0.2
       Fresh language-tags v0.3.2
       Fresh firestorm v0.5.0
       Fresh unicode-xid v0.2.2
       Fresh byteorder v1.4.3
       Fresh gimli v0.26.1
       Fresh opaque-debug v0.3.0
       Fresh same-file v1.0.6
       Fresh cache-padded v1.2.0
       Fresh untrusted v0.7.1
       Fresh spin v0.5.2
       Fresh lazy_static v1.4.0
       Fresh event-listener v2.5.2
       Fresh if_chain v1.0.2
       Fresh rustc-demangle v0.1.21
       Fresh humantime v2.1.0
       Fresh zeroize v1.5.4
       Fresh http-range v0.1.5
       Fresh futures-timer v3.0.2
       Fresh askama_escape v0.10.3
       Fresh termcolor v1.1.3
       Fresh json v0.12.4
       Fresh dotenv v0.15.0
       Fresh instant v0.1.12
       Fresh lock_api v0.4.6
       Fresh tracing-core v0.1.23
       Fresh tinyvec v1.5.1
       Fresh form_urlencoded v1.0.1
       Fresh alloc-stdlib v0.2.1
       Fresh actix-utils v3.0.0
       Fresh bytestring v1.0.0
       Fresh pem v1.0.2
       Fresh http v0.2.6
   Compiling libsqlite3-sys v0.22.2
       Fresh walkdir v2.3.2
       Fresh addr2line v0.17.0
     Running `rustc --crate-name libsqlite3_sys --edition=2018 /cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.22.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="min_sqlite_version_3_6_8"' --cfg 'feature="min_sqlite_version_3_7_16"' --cfg 'feature="pkg-config"' --cfg 'feature="vcpkg"' -C metadata=3e5e0e1d1f052f6b -C extra-filename=-3e5e0e1d1f052f6b --out-dir /target/aarch64-unknown-linux-gnu/debug/deps --target aarch64-unknown-linux-gnu -C linker=aarch64-linux-gnu-gcc -L dependency=/target/aarch64-unknown-linux-gnu/debug/deps -L dependency=/target/debug/deps --cap-lints allow -L /usr/lib/aarch64-linux-gnu/ -L /usr/lib/aarch64-linux-gnu/sqlite3 -l sqlite3`
       Fresh concurrent-queue v1.2.2
   Compiling libc v0.2.121
   Compiling memchr v2.4.1
   Compiling typenum v1.15.0
     Running `rustc --crate-name memchr --edition=2018 /cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.4.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=8d6e2ff752fcf1cb -C extra-filename=-8d6e2ff752fcf1cb --out-dir /target/aarch64-unknown-linux-gnu/debug/deps --target aarch64-unknown-linux-gnu -C linker=aarch64-linux-gnu-gcc -L dependency=/target/aarch64-unknown-linux-gnu/debug/deps -L dependency=/target/debug/deps --cap-lints allow`
     Running `rustc --crate-name typenum --edition=2018 /cargo/registry/src/github.com-1ecc6299db9ec823/typenum-1.15.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=8deb16ebbf2aba56 -C extra-filename=-8deb16ebbf2aba56 --out-dir /target/aarch64-unknown-linux-gnu/debug/deps --target aarch64-unknown-linux-gnu -C linker=aarch64-linux-gnu-gcc -L dependency=/target/aarch64-unknown-linux-gnu/debug/deps -L dependency=/target/debug/deps --cap-lints allow`
     Running `rustc --crate-name libc /cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.121/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=ece9f6c8188c588f -C extra-filename=-ece9f6c8188c588f --out-dir /target/debug/deps -L dependency=/target/debug/deps --cap-lints allow --cfg freebsd11 --cfg libc_priv_mod_use --cfg libc_union --cfg libc_const_size_of --cfg libc_align --cfg libc_core_cvoid --cfg libc_packedN --cfg libc_cfg_target_vendor --cfg libc_non_exhaustive --cfg libc_ptr_addr_of`
error: couldn't read /target/aarch64-unknown-linux-gnu/debug/build/libsqlite3-sys-9253ecbf7f6a15b5/out/bindgen.rs: No such file or directory (os error 2)
  --> /cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.22.2/src/lib.rs:56:5
   |
56 |     include!(concat!(env!("OUT_DIR"), "/bindgen.rs"));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `libsqlite3-sys` due to previous error

Caused by:
  process didn't exit successfully: `rustc --crate-name libsqlite3_sys --edition=2018 /cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.22.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="min_sqlite_version_3_6_8"' --cfg 'feature="min_sqlite_version_3_7_16"' --cfg 'feature="pkg-config"' --cfg 'feature="vcpkg"' -C metadata=3e5e0e1d1f052f6b -C extra-filename=-3e5e0e1d1f052f6b --out-dir /target/aarch64-unknown-linux-gnu/debug/deps --target aarch64-unknown-linux-gnu -C linker=aarch64-linux-gnu-gcc -L dependency=/target/aarch64-unknown-linux-gnu/debug/deps -L dependency=/target/debug/deps --cap-lints allow -L /usr/lib/aarch64-linux-gnu/ -L /usr/lib/aarch64-linux-gnu/sqlite3 -l sqlite3` (exit status: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed
 
```

**Comment by qxqxq** [comment]
> cargo install cross --git https://github.com/cross-rs/cross

MacBookPro:~ qxq$ cargo install cross --git https://github.com/cross-rs/cross
    Updating git repository `https://github.com/cross-rs/cross`
  Installing cross v0.2.1 (https://github.com/cross-rs/cross#3a5210c7)
    Updating crates.io index
warning: spurious network error (2 tries remaining): SecureTransport error: connection closed via error; class=Net (12)
   Compiling proc-macro2 v1.0.37
   Compiling unicode-xid v0.2.2
   Compiling libc v0.2.124
   Compiling syn v1.0.91
   Compiling lazy_static v1.4.0
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.136
   Compiling once_cell v1.10.0
   Compiling memchr v2.4.1
   Compiling serde v1.0.136
   Compiling autocfg v1.1.0
   Compiling pin-project-lite v0.2.8
   Compiling cc v1.0.73
   Compiling eyre v0.6.8
   Compiling adler v1.0.2
   Compiling gimli v0.26.1
   Compiling semver v1.0.7
   Compiling serde_json v1.0.79
   Compiling owo-colors v3.3.0
   Compiling indenter v0.3.3
   Compiling rustc-demangle v0.1.21
   Compiling itoa v1.0.1
   Compiling bitflags v1.3.2
   Compiling either v1.6.1
   Compiling ryu v1.0.9
   Compiling cross v0.2.1 (/Users/qxq/.cargo/git/checkouts/cross-dac8861107f29545/3a5210c)
   Compiling home v0.5.3
   Compiling shell-escape v0.1.5
   Compiling tracing-core v0.1.26
   Compiling sharded-slab v0.1.4
   Compiling thread_local v1.1.4
   Compiling miniz_oxide v0.5.1
   Compiling memoffset v0.6.5
   Compiling tracing v0.1.34
   Compiling backtrace v0.3.65
   Compiling tracing-subscriber v0.3.11
   Compiling addr2line v0.17.0
   Compiling rustc_version v0.4.0
   Compiling quote v1.0.18
   Compiling object v0.28.3
   Compiling tracing-error v0.2.0
   Compiling which v4.2.5
   Compiling atty v0.2.14
   Compiling nix v0.23.1
   Compiling color-spantrace v0.2.0
   Compiling color-eyre v0.6.1
   Compiling toml v0.5.9
   Compiling serde_ignored v0.1.2
error: there is no argument named `target`
  --> src/config.rs:27:25
   |
27 |         format!("TARGET_{target}_{key}")
   |                         ^^^^^^^^

error: there is no argument named `key`
  --> src/config.rs:27:34
   |
27 |         format!("TARGET_{target}_{key}")
   |                                  ^^^^^

error: there is no argument named `key`
  --> src/config.rs:31:24
   |
31 |         format!("BUILD_{key}")
   |                        ^^^^^

error: there is no argument named `value`
  --> src/config.rs:49:40
   |
49 |                 format!("error parsing {value} from XARGO environment variable")
   |                                        ^^^^^^^

error: there is no argument named `mentioned_target`
   --> src/config.rs:132:58
    |
132 | ...   eprintln!("Warning: a target named \"{mentioned_target}\" is mentioned in the Cross configuration, but the current specified target...
    |                                            ^^^^^^^^^^^^^^^^^^

error: there is no argument named `target`
   --> src/config.rs:132:158
    |
132 | ...the Cross configuration, but the current specified target is \"{target}\".");
    |                                                                   ^^^^^^^^

error: there is no argument named `val`
   --> src/docker.rs:156:74
    |
156 |                     .wrap_err_with(|| format!("when canonicalizing path `{val}`"))?;
    |                                                                          ^^^^^

error: there is no argument named `username`
   --> src/docker.rs:196:44
    |
196 |         docker.args(&["-e", &format!("USER={username}")]);
    |                                            ^^^^^^^^^^

error: there is no argument named `value`
   --> src/docker.rs:200:51
    |
200 |         docker.args(&["-e", &format!("QEMU_STRACE={value}")]);
    |                                                   ^^^^^^^

error: there is no argument named `value`
   --> src/docker.rs:204:51
    |
204 |         docker.args(&["-e", &format!("CROSS_DEBUG={value}")]);
    |                                                   ^^^^^^^

error: there is no argument named `target`
   --> src/docker.rs:268:65
    |
268 |             "`cross` does not provide a Docker image for target {target}, \
    |                                                                 ^^^^^^^^

error: there is no argument named `CROSS_IMAGE`
   --> src/docker.rs:279:17
    |
279 |     Ok(format!("{CROSS_IMAGE}/{target}:{version}"))
    |                 ^^^^^^^^^^^^^

error: there is no argument named `target`
   --> src/docker.rs:279:31
    |
279 |     Ok(format!("{CROSS_IMAGE}/{target}:{version}"))
    |                               ^^^^^^^^

error: there is no argument named `version`
   --> src/docker.rs:279:40
    |
279 |     Ok(format!("{CROSS_IMAGE}/{target}:{version}"))
    |                                        ^^^^^^^^^

error: there is no argument named `driver_name`
   --> src/docker.rs:344:48
    |
344 |         eyre::bail!("want driver overlay2, got {driver_name}")
    |                                                ^^^^^^^^^^^^^

error: there is no argument named `toolchain`
  --> src/rustup.rs:74:64
   |
74 |         .wrap_err_with(|| format!("couldn't install toolchain `{toolchain}`"))
   |                                                                ^^^^^^^^^^^

error: there is no argument named `target`
  --> src/rustup.rs:83:63
   |
83 |         .wrap_err_with(|| format!("couldn't install `std` for {target}"))
   |                                                               ^^^^^^^^

error: there is no argument named `component`
  --> src/rustup.rs:90:58
   |
90 |         .wrap_err_with(|| format!("couldn't install the `{component}` component"))
   |                                                          ^^^^^^^^^^^

error: failed to compile `cross v0.2.1 (https://github.com/cross-rs/cross#3a5210c7)`, intermediate artifacts can be found at `/var/folders/gc/pgx95rrs74s71dn_lkkxv_s40000gn/T/cargo-installmJbk6y`

Caused by:
  could not compile `cross` due to 18 previous errors

**Comment by Emilgardis** [comment]
Please update your rust version, minimally you can use rust 1.58.1 now for cross, but you should use the latest stable. These error messages are due to an outdated rust
