### ISSUE TITLE
Preferred way to run docker

### ISSUE THREAD

**Issue by jonas-schievink** [cross-rs/cross#71]
Being able to run the `docker` command is equivalent to being root, which is why I'm not quite comfortable adding my regular user to the `docker` group.

Running docker via `sudo` is fine, but cross doesn't do this, so I'd have to run cross itself via `sudo`, which in turn causes all sorts of problems: Build files would be created that belong to root, `rustup` uses root's configuration (which doesn't exist in my case), and it's just running much more code than necessary as root (including random build scripts of any dependencies, I think!).

This tells me that being in the `docker` group is indeed the preferred way of using cross (right?), which is already a bit questionable, but there's also no way to get around this, so I'd like some way of configuring how docker is invoked.

**Comment by dflemstr** [comment]
@jonas-schievink You could also `setuid` the `cross` binary to an user that is in the `docker` group, or `setgid` the `cross` binary to the `docker` group.

```
chmod g+s `which cross`
chown :docker `which cross`
```

**Comment by jonas-schievink** [comment]
Using `setgid` and the `chown :docker` gives this error:

    error: `"rustc" "--print" "target-list"` failed with exit code: Some(127)

With no further information. Further inspection of the `cross` source code reveals that many commands it executes require being root. Cleaning that up so that `cross` runs as much as possible as my unprivileged user and uses `sudo` (or something configurable) for privileged operations would be *really* helpful.

**Comment by astonbitecode** [comment]
Any updates on this? Is it possible to use cross without being a superuser?

**Comment by astonbitecode** [comment]
Thanks, I may do so.

@jonas-schievink for now, I could just propose running cross with sudo like:
`sudo env "PATH=$PATH" cross build ...` 
in order to at least maintain the user $PATH

**Comment by Alexhuszagh** [comment]
We support [podman](https://podman.io/getting-started/installation) on Linux, macOS, and Windows, which runs as the normal user. I believe Docker on Windows also does not require admin privileges, and there's also [rootless Docker](https://docs.docker.com/engine/security/rootless/) (although I've never used it, so I'm unsure how easy it is to integrate with cross). Since `podman` is supported, this should be the preferred way to run `cross` without root privileges.

Using podman can be done via:

```bash
CROSS_CONTAINER_ENGINE=podman cross ...
```
