### ISSUE TITLE
error: failed to run custom build command for `openssl-sys v0.9.73`

### ISSUE THREAD

**Issue by qxqxq** [cross-rs/cross#710]
MacBookPro:xdls qxq$ cross -V
cross 0.2.1
cargo 1.60.0 (d1fd9fe2c 2022-03-01)

MacBookPro:xdls qxq$ cross build --target aarch64-unknown-linux-gnu --release
   Compiling digest v0.10.3
   Compiling sha2 v0.9.9
   Compiling cipher v0.4.3
   Compiling futures-util v0.3.21
   Compiling serde v1.0.136
   Compiling tracing v0.1.32
   Compiling actix-rt v2.7.0
   Compiling diesel v1.4.8
   Compiling thiserror v1.0.30
   Compiling openssl-sys v0.9.73
error: failed to run custom build command for `openssl-sys v0.9.73`

Caused by:
  process didn't exit successfully: `/target/release/build/openssl-sys-0d7f2860411bbeb4/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit status: 1\nerror: could not find system library 'openssl' required by the 'openssl-sys' crate\n\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'openssl' found\n"

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = aarch64-unknown-linux-gnu
  openssl-sys = 0.9.73

  ', /cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.73/build/find_normal.rs:191:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by qxqxq** [comment]
```
FROM rustembedded/cross:aarch64-unknown-linux-gnu-0.2.1
RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install --assume-yes libssl-dev:arm64 &&  \
    apt-get install --assume-yes sqlite3:arm64 &&  \
    apt-get install --assume-yes libsqlite3-dev:arm64
```
It's the same error

**Comment by qxqxq** [comment]
```
FROM rustembedded/cross:aarch64-unknown-linux-gnu-0.2.1
RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install --assume-yes libssl-dev:arm64 &&  \
    apt-get install --assume-yes libssl-dev &&  \
    apt-get install --assume-yes sqlite3:arm64 &&  \
    apt-get install --assume-yes libsqlite3-dev:arm64
```
Compile successfully.

**Comment by alekspickle** [comment]
I am really sorry if that is obvious but how do I plug this new Dockerfile for cross?
[This section](https://github.com/cross-rs/cross/blob/main/docs/cross_toml.md#targettargetdockerfile) seems to be covering this but I still get the same openssl error...
Here is what I am trying with:

```Dockerfile

FROM rustembedded/cross:aarch64-pc-windows-gnu-0.2.1
RUN dpkg --add-architecture amd64 && \
    apt-get update && \
    apt-get install --assume-yes libssl-dev:amd64 &&  \
    apt-get install --assume-yes libssl-dev &&  \
    apt-get install --assume-yes sqlite3:amd64 &&  \
    apt-get install --assume-yes libsqlite3-dev:amd64

```

```Cargo.toml
[target.x86_64-pc-windows-gnu]
dockerfile = "./Dockerfile"

```

`cross build -p mycrate --target x86_64-pc-windows-gnu`

**Comment by Alexhuszagh** [comment]
> I am really sorry if that is obvious but how do I plug this new Dockerfile for cross? [This section](https://github.com/cross-rs/cross/blob/main/docs/cross_toml.md#targettargetdockerfile) seems to be covering this but I still get the same openssl error... Here is what I am trying with:
> 
> ```dockerfile
> FROM rustembedded/cross:aarch64-pc-windows-gnu-0.2.1
> RUN dpkg --add-architecture amd64 && \
>     apt-get update && \
>     apt-get install --assume-yes libssl-dev:amd64 &&  \
>     apt-get install --assume-yes libssl-dev &&  \
>     apt-get install --assume-yes sqlite3:amd64 &&  \
>     apt-get install --assume-yes libsqlite3-dev:amd64
> ```
> 
> ```toml
> [target.x86_64-pc-windows-gnu]
> dockerfile = "./Dockerfile"
> ```
> 
> `cross build -p mycrate --target x86_64-pc-windows-gnu`

There's a few issues here:
1. Your image is asking for a an ARMv8 Windows MinGW target, which we do not have.
2. You are telling cross and Rust that you are using a x86_64 Windows MinGW target, which is a different target.
3. You are installing Debian packages for `aarch64-unknown-linux-gnu` for OpenSSL, but this won't work for `aarch64-pc-windows-gnu` or `x86_64-pc-windows-gnu`.
4. You are also using a very old version of our images: you should use at least the v0.2.4 images (`ghcr.io/cross-rs/$target:0.2.4)`.
