### ISSUE TITLE
arm-unknown-linux-gnueabihf generates dependency on GLIBC_2.28

### ISSUE THREAD

**Issue by jadamcrain** [cross-rs/cross#712]
Hi,

We're using rust-cross in our CI to generate FFI libraries for a number of targets:

https://github.com/stepfunc/dnp3/blob/refactor/jni-ci-gen/.github/workflows/ci.yml#L274

The generated GLIBC dependencies are as advertised with the exception of `arm-unknown-linux-gnueabihf`.  The table in the README says 2.27 for this target, whereas we have the following two 2.28 dependencies in the .so:

```
00000000      DF *UND*  00000000  GLIBC_2.28  fcntl
00000000  w   DF *UND*  00000000  GLIBC_2.28  statx
```

The full [objdump.txt](https://github.com/cross-rs/cross/files/8748349/objdump.txt)

Is this expected? Can the minimum required GLIBC be lowered for this target?

thanks!
 
Adam

**Comment by jadamcrain** [comment]
The ARM toolchain referenced in the [dockerfile](https://github.com/cross-rs/cross/blob/main/docker/Dockerfile.arm-unknown-linux-gnueabihf#L15) explicitly [says](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads/8-3-2019-03) it contains 2.28 so maybe best to update the table from 2.27 -> 2.28.

I have a user who'd like to use our ARM cross builds on Ubuntu 18.04 which only has 2.27 and is TLS until 2028.

**Comment by Emilgardis** [comment]
Thanks for the issue!

Yeah, the table is not accurate, feel free to submit a pr to correct it. We also have #591 which probably will change stuff as well, we haven't gotten to that though yet.

See #680 for a way to possibly select glibc version

**Comment by jadamcrain** [comment]
@Emilgardis Thanks for these.

`cargo-zigbuild` is pretty fascinating. I just tried to do this locally installing it, zig, and the `arm-unknown-linux-gneuabihf` target.

My project has [ring](https://github.com/briansmith/ring) as an indirect dependency which has a complicated, platform-dependent build script.

```
  error: Unknown CPU: 'armv6'
  thread 'main' panicked at 'execution failed', /home/jadamcrain/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:656:9
```

I'll take this issue over to the cargo-zigbuild project for suggestions to see if they can help.

**Regardless of outcome with zigbuild, is rust-cross interested in supported older GLIBC for this architecture?**

**Comment by jadamcrain** [comment]
It looks like I'm hamstrung by https://github.com/ziglang/zig/issues/4911 and unable to use cargo-zigbuild until that resolves.

**Comment by Emilgardis** [comment]
> **Regardless of outcome with zigbuild, is rust-cross interested in supporting older GLIBC for this architecture?**. Not supporting Ubuntu 18.04 doesn't seem portable.

Yes, as hinted in #680, we want to try to do that

**Comment by Alexhuszagh** [comment]
This has actually been fixed: we've lowered this (for this target only) to glibc 2.17 (see [supported targets](https://github.com/cross-rs/cross#supported-targets)). This was part of another bug fix (reported in #426 and fixed in #734).

**Comment by jadamcrain** [comment]
That's great! How often are releases done? Does it matter if the referenced docker image are updated more frequently?

I guess I'm just wondering when this fix would show up if I'm using Github actions with `cross: true`.

**Comment by Emilgardis** [comment]
You can try it out already if you add

`- run: cargo install --git https://github.com/cross-rs/cross --locked` to your action

#761
