### ISSUE TITLE
Add FAQ Documentation

### ISSUE THREAD

**Issue by Alexhuszagh** [cross-rs/cross#723]
Certain questions repeatedly show up in the issues section or are relevant to cross-compilation but may be difficult to find while reading the cargo documentation. Examples include:
- Linking C dependencies
- Extending images (already documented)
- Adding `RUSTFLAGS`, custom runners, etc.

To avoid polluting the README, it may be worthwhile to create an FAQ with a table of contents that documents answers to these questions.

**Comment by Emilgardis** [comment]
Sounds like a good opportunity for a wiki ;)

wikis on gh are good also with the fact that they don't touch the repo. I've enabled the wiki feature on the repo now

**Comment by Alexhuszagh** [comment]
Ok I've added a few initial pages:

- [Configuration](https://github.com/cross-rs/cross/wiki/Configuration)
- [FAQ](https://github.com/cross-rs/cross/wiki/FAQ)

This information could potentially be removed from the README as long as we properly link to it.

**Comment by Alexhuszagh** [comment]
We've got some pretty extensive documentation on the wiki, we should add a reference on the readme.
