### ISSUE TITLE
Unable to find `libclang.so`

### ISSUE THREAD

**Issue by NobodyXu** [cross-rs/cross#731]
When using `cross` to cross compiling crate [`zstd`] in PR https://github.com/ryankurte/cargo-binstall/pull/148, the CI that `use-cross: true` all failed with `libclang.so` not found.

Edit:

The PR enabled feature `bindgen` of [`zstd`] and `bindgen` uses `libclang.so` to parse C headers.

[`zstd`]: https://github.com/gyscos/zstd-rs

**Comment by Emilgardis** [comment]
https://github.com/ryankurte/cargo-binstall/runs/6665668295?check_suite_focus=true#step:7:569

**Comment by Emilgardis** [comment]
works kinda on the newest images, either pull the newest unreleased cross version to override whatever actions-rs does, or set 

```
CARGO_TARGET_${TARGET}_IMAGE=ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:edge
```

seems like there's some more issues though, we're missing `linux-libc-dev-<target>-cross` on the linux images

**Comment by NobodyXu** [comment]
We are using `cross` via [actions-rs/cargo] by setting `use-cross: true`.

Does changing env work for [actions-rs/cargo]?

[actions-rs/cargo]: https://github.com/actions-rs/cargo

**Comment by Emilgardis** [comment]
Yes, it works for everything using cross.
You can also install cross before invoking use-cross and if actions-rs finds the cross binary it won't/shouldn't override it

You can adjust the image in the Cross.toml too ofc :)

**Comment by NobodyXu** [comment]
@Emilgardis The [build](https://github.com/ryankurte/cargo-binstall/runs/6666823248?check_suite_focus=true) still failed:

```
  /usr/arm-linux-gnueabihf/include/limits.h:123:16: fatal error: 'limits.h' file not found
```

**Comment by Emilgardis** [comment]
As mentioned, missing `linux-libc-dev-<target>-cross` @NobodyXu 

We should include that, pr pending :)

**Comment by NobodyXu** [comment]
> As mentioned, missing linux-libc-dev-<target>-cross @NobodyXu

Ok, sorry I missed that part.

**Comment by Emilgardis** [comment]
hmm, seems like that's not it

**Comment by NobodyXu** [comment]
@Emilgardis We need it to be statically linked so that it can run on everywhere, so we probably cannot use external version of `libzstd` that is dynamically linked.

**Comment by Emilgardis** [comment]
of course, the issue is not with cross now however, you need to install zstd and clang-3.9 _in the image_ that cross uses so that it/cargo/bindgen can find the relevant files.
