### ISSUE TITLE
Add LLVM MINGW cross target

### ISSUE THREAD

**Issue by calvin2021y** [cross-rs/cross#790]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [X] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

Current we only have GCC based MINGW toolchain,  it will be nice to have https://github.com/mstorsjo/llvm-mingw/releases

The target will be i686-w64-windows-gnu, x86_64-w64-windows-gnu, and maybe aarch64 too.

### Describe why this would be a good inclusion for `cross`

LLVM MINGW support cross build multi target with same compiler,  one clang can build x86, x64, aarch64, armv7.  This will make a much smaller docker image for multi target.

Rust being a lllvm-backend language, this make more sense.

With LLVM MINGW LTO build, Rust can use cross language boundary link optimization.

**Comment by Alexhuszagh** [comment]
Nice,, sounds like a great addition especially if ARM64 is supported. Just a quick question because I only checked out llvm-mingw like a year ago: is Windows ARM64 well-supported now?

**Comment by calvin2021y** [comment]
Yes.

It use llvm-clang backend,  RUST & Android & Xcode also use this backend.  

Android studio use this to reduce NDK size because same binary can generate all support target with high quality generated code.

Use automake/cmake/meson it can cross build most of library from linux, for all target.  

It has few problem but easy to fix:

1) some source code use uppercase filename when include,  llvm mingw only use lower case.  from windows this is not a problem, but linux filesystem will not able to find it.  you need change source code to made it lower case

2) some library like GRPC use _MSC_VER for windows target, it should use _WIN32

With llvm mingw you can use all sanitizers, and fakestack for coroutine.  This is very helpful when you need build c/c++ library.   `-fsanitize=address  -fsanitize=memory -fsanitize=thread`,  I use  address sanitize  all the time.

The generate binary can be free from MSVC runtime,  it mean you dont need install a specific runtime version to start your exec binary.  

It also support windows mobile pad.

**Comment by Alexhuszagh** [comment]
There's a few issues here, but I have an initial implementation for this up-and-running. The main issues are as follows:

The rust targets expect the following standard libraries that LLVM does not provide:
- `-lstdc++`, `-lgcc_eh` and `-lgcc` (LLVM uses `-lc++`).
- No rustup support for any targets other than `i686` and `x86_64`, which we already support.
- No WINE support for anything other than `i686` and `x86_64`.

Unfortunately, we therefore cannot support these targets out-of-the-box, but this should be a good starting point if you would like to use these targets. It might be possible by overriding the following following environment variable to fix the linker issues `LDFLAGS_x86_64_pc_windows_gnu` (for `x86_64-pc-windows-gnu`, simply substitute `-` for `_` in the target and prefix it with `LDFLAGS_`).

The target names should be:
- `aarch64-pc-windows-gnu`
- `armv7-pc-windows-gnu`
- `i686-pc-windows-gnu`
- `x86_64-pc-windows-gnu`

And you can see what Dockerfiles they correspond to as a result.

See [cross-toolchains/llvm-mingw](https://github.com/cross-rs/cross-toolchains/tree/llvm-mingw) for the partially-working Dockerfiles. The images build, but cross cannot compile for these targets, and most do not have runners.

**Comment by calvin2021y** [comment]
Thanks for the explain and tips.

I try build staticlib  for https://github.com/xacrimon/dashmap and link with C.  some time I get " Illegal instruction" error and not sure why it gone late.

If I use `--emit=llvm-ir`,  then the staticlib will be LTO link with `clang -flto` ?
