### ISSUE TITLE
Output diagnostics in cargo-style

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#797]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

cross should output it's warnings, notes and errors in the same way cargo does it

e.g something like this https://github.com/rust-lang/cargo/blob/ca4edabb28fc96fdf2a1d56fe3851831ac166f8a/src/cargo/core/shell.rs#L251-L257

### Describe why this would be a good inclusion for `cross`

This will make integration with cargo look better

**Comment by Emilgardis** [comment]
When doing this, we could also insert a `[c]` or something similar as a prefix to the output we make to make it clear what cross is doing

**Comment by Alexhuszagh** [comment]
This should also have the verbosity settings: we should also parse `quiet`.

**Comment by Emilgardis** [comment]
reopening as there still some action left, i.e info/note messages

**Comment by Alexhuszagh** [comment]
Is this closes now that we can erase lines via #911? We should have essentially full support of the functionality of cargo's diagnostics itself.

**Comment by Emilgardis** [comment]
No, I'm thinking something like

```
$ cross build --target arm-unknown-linux-gnueabi
  Installing target arm-unknown-linux-gnueabi
      Docker running pre-build hooks
      Docker ...
```

**Comment by Emilgardis** [comment]
Basically, instead of some wait time when there's some setup needed for cross, display some nice data so that one doesn't think it's stuck
