### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#798]
We should add a CONTRIBUTING.md file, specifying how

* How to interact with the repository
* How to find easy issues
* Explain how cross works in a lower level than "just works"
* How to integrate new targets (explain xtask, the ci pipeline etc)
* How releases are done
* more?
* link to coc

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by Alexhuszagh** [comment]
Maybe also add an AUTHORS.md file? Might be nice to give credit. We can also quickly grep the commit history to add one.

**Comment by Alexhuszagh** [comment]
Do we still need this? We've added the contributing section to the [wiki](https://github.com/cross-rs/cross/wiki/Contributing).

**Comment by Emilgardis** [comment]
I think it would be good to have, either just duplicating or making it a link to the wiki

**Comment by Alexhuszagh** [comment]
So I guess the real question is do we want it in the git history then? If so, I can duplicate it. If not, we should probably link it.
