### ISSUE TITLE
README Dockerfile section is wrong

### ISSUE THREAD

**Issue by lucasvanmol** [cross-rs/cross#809]
Under "Configuration", the [Dockerfiles](https://github.com/cross-rs/cross#dockerfiles) section is wrong.

It currently says:

```
[target.aarch64-unknown-linux-gnu.dockerfile]
dockerfile = "./path/to/where/the/Dockerfile/resides"
```

According to https://github.com/cross-rs/cross/blob/main/docs/cross_toml.md it should either say:
```
[target.aarch64-unknown-linux-gnu.dockerfile]
file = "./path/to/where/the/Dockerfile/resides"
```

or:

```
[target.aarch64-unknown-linux-gnu]
dockerfile = "./path/to/where/the/Dockerfile/resides"
```

**Comment by Emilgardis** [comment]
Thanks for the report!
