### ISSUE TITLE
CI no longer supports wildcard matching, nor multiple `--target` specificiers.

### ISSUE THREAD

**Issue by Alexhuszagh** [cross-rs/cross#815]
Trying `bors try --target x86_64-unknown-linux-gnu*` produces no targets in the matrix, nor does it seemingly support more than one target. This seems to be a regression related that undoes #744.

**Comment by Emilgardis** [comment]
Yep, there is a missing `test(q)` in the query i think

**Comment by Alexhuszagh** [comment]
> Yep, there is a missing `test(q)` in the query i think

It should be `if has(".sub") ...`, not `if .sub ...`. Working on this right now, it's still incomplete but almost ready. Currently doesn't work if the target query doesn't have a sub but the CI target does. Not sure if that's easy to fix, however.
