### ISSUE TITLE
Add full android test support

### ISSUE THREAD

**Issue by malbarbo** [cross-rs/cross#82]
~~Should https://github.com/snipsco/dinghy be used?~~

Support for testing android binaries that depends only on libc was added in https://github.com/japaric/cross/pull/132.

We should add support to test android binaries in the android emulator. See https://github.com/japaric/cross/pull/132 for a brief discussion of the issues of distributing the android emulator.

**Comment by japaric** [comment]
If it can provide a transparent testing experience like the other `cross test` targets, sure!

**Comment by jan-hudec** [comment]
Since https://github.com/rust-lang/cargo/pull/3954 it is possible to run the generated binaries through a wrapper. So there could be a wrapper that would start the emulator (which can be done; [here are Travis' instructions](https://docs.travis-ci.com/user/languages/android/#How-to-Create-and-Start-an-Emulator)) and then run the tests there.

**Comment by jamesmunns** [comment]
@malbarbo is this okay to close since #132 has landed?

**Comment by malbarbo** [comment]
@jamesmunns I updated the issue to make clear what is missing.

**Comment by Alexhuszagh** [comment]
This would require a full-system Android emulator, which I believe is beyond the scope of `cross` itself. The best way to test the binaries would be any of the many Android emulators, which also require a full Android image, including Android Studio, BlueStacks, or the open-source [anbox](https://github.com/anbox/anbox/blob/master/docs/install.md). Anbox supports Snap installs, and so should be compatible with our images.  If anyone wants to document this on the wiki, that would be appreciated, but it is assumed most developers targeting Android already have these tools available.
