### ISSUE TITLE
ring 0.16.20 fails on glibc for armv7-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by leshow** [cross-rs/cross#832]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

`cross` fails to build `ring 0.16.20` (it is not a direct dependency) for armv7-unknown-linux-gnueabihf

### What target(s) are you cross-compiling for?

`armv7-unknown-linux-gnueabihf`

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.1 (05c4490 2022-06-21)

### Example

```
❯ cross build --target armv7-unknown-linux-gnueabihf         
   Compiling libc v0.2.126
   Compiling ring v0.16.20
   Compiling anyhow v1.0.58
   Compiling protobuf v2.27.1
   Compiling typenum v1.15.0
   Compiling httparse v1.7.1
   Compiling crc32fast v1.3.2
   Compiling crossbeam-utils v0.8.9
   Compiling libsqlite3-sys v0.24.2
   Compiling encoding_rs v0.8.31
   Compiling brotli-decompressor v2.3.2
   Compiling lock_api v0.4.7
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/target/debug/build/ring-c5ea9685f52c1129/build-script-build` (exit status: 1)
  --- stderr
  /target/debug/build/ring-c5ea9685f52c1129/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /target/debug/build/ring-c5ea9685f52c1129/build-script-build)
  /target/debug/build/ring-c5ea9685f52c1129/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /target/debug/build/ring-c5ea9685f52c1129/build-script-build)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Alexhuszagh** [comment]
Have you tried running `cargo clean`? See #724.

**Comment by leshow** [comment]
Oh, yes that seems to work. Thank you!
