### ISSUE TITLE
cross-util requires a target for listing images

### ISSUE THREAD

**Issue by Alexhuszagh** [cross-rs/cross#848]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When running `cross-util images list`, it now requires a (singular) target, rather than list all images or filter by a list of targets. Likewise, if providing a target, it does not seem to correctly filter for said target.

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

latest main build

### Example

```bash
$ cross-util images list
error: The following required arguments were not provided:
    <TARGET>

USAGE:
    cross-util images list [OPTIONS] <TARGET>

For more information try --help
$ cross-util images list arm-unknown-linux-gnueabihf
ghcr.io/cross-rs/aarch64-pc-windows-msvc:local
ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:main
ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main
ghcr.io/cross-rs/i686-apple-darwin:local
ghcr.io/cross-rs/i686-pc-windows-gnu:main
ghcr.io/cross-rs/i686-pc-windows-gnu-llvm-cross:local
ghcr.io/cross-rs/i686-pc-windows-msvc:local
ghcr.io/cross-rs/powerpc64le-unknown-linux-gnu:local
ghcr.io/cross-rs/powerpc64le-unknown-linux-gnu:main
ghcr.io/cross-rs/sparcv9-sun-solaris:local
ghcr.io/cross-rs/thumbv7a-pc-windows-msvc:local
ghcr.io/cross-rs/wasm32-unknown-emscripten:local
ghcr.io/cross-rs/x86_64-apple-darwin:local
ghcr.io/cross-rs/x86_64-pc-windows-msvc:local
ghcr.io/cross-rs/x86_64-pc-windows-msvc-cross:local
ghcr.io/cross-rs/x86_64-sun-solaris:local
ghcr.io/cross-rs/x86_64-unknown-dragonfly:local
ghcr.io/cross-rs/x86_64-unknown-linux-gnu:local
ghcr.io/cross-rs/x86_64-unknown-linux-gnu:local-centos
ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main
```

### Additional information / notes

`cross-util` should accept optional targets for both listing and removing images, similar to `RemoveImages`.

**Comment by Emilgardis** [comment]
if zero, two or more targets are specified, it would be nice if it had a column with the specific target for that image

**Comment by Alexhuszagh** [comment]
> if zero, two or more targets are specified, it would be nice if it had a column with the specific target for that image

Guessing we should calculate the width as well as everything is nicely padded?

**Comment by Emilgardis** [comment]
should be easy, just use `{:<width$}`
