### ISSUE TITLE
Document why some images use different ubuntu version

### ISSUE THREAD

**Issue by malbarbo** [cross-rs/cross#85]

**Comment by japaric** [comment]
We do this the get the oldest glibc version possible as linking against the oldest glibc makes the binary more portable (it will work on LTS-ish distros that ship with old glibc). We *could* use the latest Ubuntu everywhere but then we would have to build a toolchain with an old glibc version ourselves and that would be very expensive CI time wise.

**Comment by malbarbo** [comment]
@japaric Thank you for the clarifications!

**Comment by Alexhuszagh** [comment]
This is now documented on the [wiki](https://github.com/cross-rs/cross/wiki/FAQ#newer-linux-versions):

> Due to backwards compatibility, cross uses older images and repositories for binary compatibility with code compiled against older libc versions. This requires older Ubuntu versions and Linux images. However, this can break some more recent workflows.

We also have images with much newer Ubuntu versions which are pending release in v0.3.0 in #591.
