### ISSUE TITLE
Remove WSLPath

### ISSUE THREAD

**Issue by Alexhuszagh** [cross-rs/cross#854]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Currently, we use `wsl -e wslpath -a ...` to find the WSL2 path of a file for our mount point on Windows. This poses a few issues:
- It requires external commands, which add significant overhead.
- It does not work for UNC paths.

A simple test is as follows:

```bash
wsl -e wslpath -a "\\server\share"
wslpath: \\server\share
```

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [x] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [x] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

latest main build

**Comment by Emilgardis** [comment]
for context, wslpath was added in https://github.com/cross-rs/cross/pull/665
