### ISSUE TITLE
How to loop over all valid targets?

### ISSUE THREAD

**Issue by mcandre** [cross-rs/cross#86]
How could a `cross` user automatically build for every supported target, like gox?

Is there a command invocation that lists the supported triples?

**Comment by japaric** [comment]
>  Is there a command invocation that lists the supported triples?

Cross has the exact same CLI as Cargo so there isn't one. We could list the supported targets in the output of something like `cross -Vv` though.

> How could a cross user automatically build for every supported target, like gox?

A shell script? The supported targets match the directories [here](https://github.com/japaric/cross/tree/62b402ac46ae6f667045f1a8229d56bb7ec6e2e3/docker)

I'm pretty sure no *binary* crate will compile for all the targets supported by Cross as some targets, e.g. the thumbv\*m-none-eabi\* ones, don't support `std`. If you just want to check that some crate compiles (no object file generation or linking) then you are better just calling `cargo check --target $T` (\*); no need for the C toolchain that comes with Cross.

(\*) still needs the `rust-std` component (`rustup target add`). Won't work with targets that don't have a `rust-std` component, i.e. the thumbv\*-none-eabi\* ones.

**Comment by japaric** [comment]
> (*) still needs the rust-std component (rustup target add).

Oh, so `cross check --target $T` also works and install `rust-std` for you.

> If you just want to check that some crate compiles

Closest thing to that:

``` sh
for t in $(rustup target list | cut -d' ' -f1); do
    cross check --target $t
done
```

Probably the ios targets won't work on Linux because they require an ios simulator to be installed on the system.

**Comment by jamesmunns** [comment]
@mcandre does the shell script approach work for you? Or are you still interested in integrating this functionality into cross?

**Comment by mcandre** [comment]
@jamesmunns

I'm not sure that I fully understand cross's configuration or capabilities. What I want to do is to build Rust applications for macOS, Windows, and Linux, using the same workflow and tools from any of these hosts to any of these targets. From comments around cross and rustup, I think that one needs LLVM in order to be able to build Rust applications targeting Linux from Windows hosts. I am curious if LLVM also helps Rust to build the opposite direction, Windows binaries from Linux, or if a virtual machine with full-blown Visual Studio would be required to do that.

For now, I'm cross-compiling my Rust apps with [tonixxx](https://github.com/mcandre/tonixxx), because while virtual machines aren't the fastest, they do at least work!

**Comment by Alexhuszagh** [comment]
Not sure this is relevant anymore: the list of valid targets is provided in the README, and we don't provide pre-built images for all targets supported by rustup.

**Comment by Alexhuszagh** [comment]
You should be able to do this after authenticating using the packages Github API, documented [here](https://docs.github.com/en/rest/packages#list-packages-for-an-organization). However, if you want a more scriptish way of doing this, I'd probably just use a Bash commands:

```bash
#!/bin/bash

# first install yq if not available
export VERSION=v4.25.3
export BINARY=yq_linux_amd64
wget "https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz" -O - | tar xz
sudo mv "${BINARY}" /usr/local/bin/yq

wget https://raw.githubusercontent.com/cross-rs/cross/main/.github/workflows/ci.yml
matrix_str="$(yq -r '.jobs.generate-matrix.steps[0].env.matrix' ci.yml)"
targets=($(yq -r '.[].target' <<< "${matrix_str}"))

for target in "${targets[@]}"; do
    ...
done
```

And this will let you loop over every maintained image we have, as of the latest main commit.
