### ISSUE TITLE
`error: linking with 'cc' failed: signal: 11` on aarch64-unknown-linux-musl

### ISSUE THREAD

**Issue by tranzystorek-io** [cross-rs/cross#883]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I am trying to test building the https://github.com/gleam-lang/gleam repository with cross, I switched its dependencies manually to use rustls and ran `cross build --release --target aarch64-unknown-linux-musl`, and I get the

```console
error: linking with `cc` failed: signal: 11
```

when building the following dependencies:

```console
error: could not compile `libc` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `syn` due to previous error
error: could not compile `proc-macro2` due to previous error
error: could not compile `log` due to previous error
error: could not compile `memchr` due to previous error
error: could not compile `serde_derive` due to previous error
```

I'm building on a WSL linux installation if that changes anything.

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-musl

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [X] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [X] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.2

**Comment by Emilgardis** [comment]
I'm unable to replicate this on WSL

`Linux EmilsPC-wsl 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux`

the only changes I did is setting `reqwest = { version = "0.11.6", default-features = false, features = ["rustls-tls"]}
` in `compiler-cli/Cargo.toml`

Are you maybe running out of memory and it's somehow presenting this way?

Can you post the full verbose log (`cross build --release --target aarch64-unknown-linux-musl -v`)  and if you did something else to use rustls describe those changes

**Comment by tranzystorek-io** [comment]
On my other computer with practically the same WSL setup, but with more memory this issue doesn't reproduce 😕

**Comment by Alexhuszagh** [comment]
I don't think there's any reasonable way to try to handle OOM, since we'd have to allocate memory to create an error message (can't do that), so I think it's not ideal, but fine the way it is?

**Comment by Emilgardis** [comment]
Try increasing wsl2 memory limit, it should be dynamic but maybe its not able to be properly fone

Should be numerous articles online how to do it

**Comment by Emilgardis** [comment]
No worries! We now have a gist of the issue at least! Enjoy your time away :)

**Comment by tranzystorek-io** [comment]
I made a little experiment: on the machine where this doesn't reproduce, I forced wsl params to 1GB memory and no swap, and I couldn't get it to OOM with `cross build`, just slows down to a crawl but never crashes.

This leads me to believe the issue here is a bit more subtle, but still confusing...

**Comment by Alexhuszagh** [comment]
Have you been able to create a reproducible test case?

**Comment by tranzystorek-io** [comment]
Not really, I think we can close.
