### ISSUE TITLE
Problem with 0.2.2 and CROSS_DOCKER_IN_DOCKER

### ISSUE THREAD

**Issue by alexet** [cross-rs/cross#893]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Cross no longer seems to work with our project with docker in docker. 

Not using docker or downgrading fixes the issue. Not using a `path` for a dependency also works.

The error is `error: could not find `Cargo.toml` in `/home/runner/work/cross-bug-reduced/cross-bug-reduced` or any parent directory`

### What target(s) are you cross-compiling for?

x86_64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.2

### Example

The example is reduced from an internal case and is therefore pointless.

Inside a docker image do the following steps:
- Clone https://github.com/alexet/cross-bug-reduced
- Set CROSS_DOCKER_IN_DOCKER
- cross build --target x86_64-unknown-linux-gnu

### Additional information / notes

Working run with cross 0.2.1 : https://github.com/alexet/cross-bug-reduced/runs/7151280983
Broken run with 0. 2.2: https://github.com/alexet/cross-bug-reduced/actions/runs/2597098367
Working run with 0.2.2 without docker: https://github.com/alexet/cross-bug-reduced/actions/runs/2597098367
Working run without dependency: https://github.com/alexet/cross-bug-reduced/runs/7149368098

**Comment by Alexhuszagh** [comment]
Interesting, I wonder if this has anything to do with the introduction of `Directories` (I believe introduced with remote docker support).

**Comment by Alexhuszagh** [comment]
After bisecting, it looks like the offending commit with the mount paths was 1aec883. However, it didn't work for me due to inspect issues for 0042a0b, and that issue was introduced in c59aa93. See if it works on 4257c41 for you.

**Comment by Alexhuszagh** [comment]
Ok changing the mount paths for the project, which for some reason seems to "double-up" for the mount paths.

```bash
/usr/bin/docker run --userns host -e 'PKG_CONFIG_ALLOW_CROSS=1' -e 'XARGO_HOME=/xargo' -e 'CARGO_HOME=/cargo' -e 'CARGO_TARGET_DIR=/target' -e 'CROSS_RUNNER=' -e TERM -e 'USER=root' \
    -v /cross-bug-reduced/dependency:/cross-bug-reduced/dependency --rm --user 0:0 \
    -v /var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/root/.xargo:/xargo:Z \
    -v /var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/root/.cargo:/cargo:Z \
    -v /cargo/bin \
    -v /var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/cross-bug-reduced:/var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/cross-bug-reduced:Z \
    -v /var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:/rust:Z,ro \
    -v /var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/cross-bug-reduced/target:/target:Z -w /var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/cross-bug-reduced -i -t centos/devtoolset-7-toolchain-centos7 sh -c 'PATH=$PATH:/rust/bin cargo build --target x86_64-unknown-linux-gnu --verbose'
```

This does work:

```bash
/usr/bin/docker run --userns host -e 'PKG_CONFIG_ALLOW_CROSS=1' -e 'XARGO_HOME=/xargo' -e 'CARGO_HOME=/cargo' -e 'CARGO_TARGET_DIR=/target' -e 'CROSS_RUNNER=' -e TERM -e 'USER=root' \
    -v /cross-bug-reduced/dependency:/cross-bug-reduced/dependency --rm --user 0:0 \
    -v /var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/root/.xargo:/xargo:Z \
    -v /var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/root/.cargo:/cargo:Z \
    -v /cargo/bin \
    -v "/var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/cross-bug-reduced:/project:Z" \
    -v /var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:/rust:Z,ro \
    -v /var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/cross-bug-reduced/target:/target:Z \
    -w /project -i -t centos/devtoolset-7-toolchain-centos7 sh -c 'PATH=$PATH:/rust/bin cargo build --target x86_64-unknown-linux-gnu --verbose'
```

If we set `PREFIX=/var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged`, then the only difference is we have:

```diff
- "$PREFIX/cross-bug-reduced:/project:Z"
+ $PREFIX/cross-bug-reduced:$PREFIX/var/lib/docker/overlay2/ef1b7713a2d64f694cb589f8802b70af301485955850d3a0083ca1fb4817de3e/merged/cross-bug-reduced
```

**Comment by Alexhuszagh** [comment]
It looks like this was the offending commit, and the issue was a weird [rebase](https://github.com/cross-rs/cross/commit/0c1d76dbfd55ee62586504a173fa8a3e40ab4f1c#diff-4cf895b046f53b02266b843eb9440dec88b857e039a624a5310502e3dd7eb858) or something:

A new function was introduced, which exhibits the correct behavior, but

```rust
#[allow(unused_variables)]
pub fn mount(cmd: &mut Command, val: &Path, verbose: bool) -> Result<PathBuf> {
    let host_path =
        file::canonicalize(&val).wrap_err_with(|| format!("when canonicalizing path `{val:?}`"))?;
    let mount_path: PathBuf;
    #[cfg(target_os = "windows")]
    {
        // On Windows, we can not mount the directory name directly. Instead, we use wslpath to convert the path to a linux compatible path.
        mount_path = wslpath(&host_path, verbose)?;
    }
    #[cfg(not(target_os = "windows"))]
    {
        mount_path = host_path.clone();
    }
    cmd.args(&[
        "-v",
        &format!("{}:{}", host_path.display(), mount_path.display()),
    ]);
    Ok(mount_path)
}
```

```diff
     let mount_root: PathBuf;
     #[cfg(target_os = "windows")]
     {
@@ -122,7 +147,17 @@ pub fn run(
     }
     #[cfg(not(target_os = "windows"))]
     {
-        mount_root = host_root.clone();
+        mount_root = mount_finder.find_mount_path(host_root.clone());
+    }
```

This means we didn't notice it until I removed the redundant mount code later, which uncovered the bad rebase or whatever it was here.
