### ISSUE TITLE
Some RUSTFLAGS Force Cargo Use on the Host

### ISSUE THREAD

**Issue by Alexhuszagh** [cross-rs/cross#903]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Attempting to run the following causes `cross` to assume that we do not need docker support, and therefore fallback to the host:

```bash
$ CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS="-Zsanitizer=leak" \
    cross +nightly build --target aarch64-unknown-linux-gnu -Z build-std -vv
+ cargo metadata --format-version 1 --filter-platform aarch64-unknown-linux-gnu                                                                                                                     
Warning: Falling back to `cargo` on the host.                                                                                                                                                       
+ cargo +nightly build --target aarch64-unknown-linux-gnu -Z build-std -vv                                                                                                                          
   Compiling compiler_builtins v0.1.73
```

I believe this affects every image. Not every rustflag however affects this: only unstable `-Z` flags are affected. For example, this works:

```bash
$  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS="-C panic=abort" \
    cross +nightly build --target aarch64-unknown-linux-gnu -Z build-std -vv
```

Note that this does not occur when using `cross rustc` and passing the options: the following works as expected:

```bash
$ cross +nightly rustc --target x86_64-unknown-linux-gnu -- -Zself-profile -Zsanitizer=leak
```

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.2  and latest main

### Additional information / notes

This affected cross prior to #869 being merged, so this is not related to that.

**Comment by Alexhuszagh** [comment]
The issue relates to `cargo_metadata_with_args` not returning, likely because it does not use the current channel. A solution would be to ensure the channel is passed to `cargo`.

**Comment by Emilgardis** [comment]
There's a nice little todo for that here

https://github.com/cross-rs/cross/blob/00c1de2ddf984e892976c7018af8b506575ba59c/src/cargo.rs#L145

`shell::warning` should work well for that, however it would mean two warnings when running `cargo` in current context/path would fail

**Comment by Alexhuszagh** [comment]
I've added this code to replace the TODO, so we have good logging: both the `cargo metadata` error and the cross warning:

```rust
    if !output.status.success() {
        shell::warn("unable to get metadata for package", msg_info)?;
        shell::status(String::from_utf8(output.stderr.clone())?, msg_info)?;
        return Ok(None);
    }
```

**Comment by Emilgardis** [comment]
what about surpressing it when in normal verbosity, but keep it in verbose mode.

Also, should probably pretty format it with section (e.g use indented) to make it more distinct
