### ISSUE TITLE
Support Pre-Build Hooks Remotely or Document Why Not

### ISSUE THREAD

**Issue by Alexhuszagh** [cross-rs/cross#928]
Currently, we only support custom docker images/pre-build hooks when `cross` is used locally. If we can use `DOCKER_HOST` (or similar for podman) to allow remote builds (it would need to send the context to docker remotely, which could take a while), then we should support that. If we cannot, then this should be clearly documented.

**Comment by Alexhuszagh** [comment]
This should be doable on recent docker versions (see [How To Use Docker Buildx in Remote Docker?](https://support.circleci.com/hc/en-us/articles/360058095471-How-To-Use-Docker-Buildx-in-Remote-Docker-)).

**Comment by Emilgardis** [comment]
Oh I've been assuming this just worked, I guess it's because I'm using experimental 😅
