### ISSUE TITLE
Missing rust-std for targets

### ISSUE THREAD

**Issue by Susurrus** [cross-rs/cross#94]
`x86_64-unknown-dragonfly`, `armv7-unknown-linux-musleabihf`, and `arm-unknown-linux-musleabihf` are affected. I think this is because `rustup` doesn't have support for installation on those platforms (see [here](https://github.com/rust-lang-nursery/rustup.rs/#other-installation-methods)).

**Comment by japaric** [comment]
the dragonfly target has no rust-std component available via rustup. The other two do (at least on nightly)

**Comment by japaric** [comment]
> (see here).

that's the list of *hosts* that support rustup; that's totally different.

**Comment by Susurrus** [comment]
Ahh, hosts, got it.

Yeah, the `arm-unknown-linux-musleabihf` doesn't exist, I meant the `arm-unknown-linux-musleabi` target.

I was testing these platforms for japaric/trust#72. I saw these platforms were listed as supported for cross so I filed this ticket. Maybe it can be clarified that support is in-progress for these platforms and they aren't fully supported yet?

**Comment by japaric** [comment]
> Maybe it can be clarified that support is in-progress for these platforms and they aren't fully supported yet?

The README does mention the [level of support of each target](https://github.com/japaric/cross#supported-targets) and that some targets don't have a `std` component through the `[2]` footnote but perhaps it would be better to have a `std` column like the `test` one.

**Comment by Susurrus** [comment]
Yeah, it looks like there multiple uses for that table. For me, as a consumer of this tool, I looked at it to quickly see support. The footnote wasn't obvious enough, I was actually using the `Test` column to indicate full support. Maybe just splitting the table into 2 with headers "Fully Supported" and "In Progress" that contains all the same information and keeping the footnotes just in that second table as details as to *why* it's unsupported? This might better get the point across but still serve as a useful reference for you and other devs.

**Comment by gnzlbg** [comment]
@japaric  `x86_64-unknown-dragonfly` doesn't have a `core` component either, is that correct?
