### ISSUE TITLE
Readme and/or wiki should give increased explanations of how to install/configure container software

### ISSUE THREAD

**Issue by Lokathor** [cross-rs/cross#948]
Hello, lovely tool you've got here. But it all depends on using a container software. Docker, or Podman.

The readme is *very light* on explanations of how to make those tools ready for use by `cross`.

After installing `cross` and realizing that maybe (?) I can't easily get those running on Windows I got on a linux machine and then had a fun 15 minute struggle to get docker to go. Even then, I apparently did it wrong, because i used the docker group, and i guess there's some alternate "rootless mode" thing i should have used instead? I don't know, it's fine.

My point is this: you don't need to write your own full guide on how to install and set up docker (though that would be nice because your readme is nicely written so someone has some skills), but if you don't write such a guide you should please at least find some guide elsewhere that covers all the details and then clearly link to that guide in the readme, right at the top.

Like:

> If you have not used Docker before **Read This Setup Guide First!**

and then that bold part is the words that would be the link.

**Comment by Alexhuszagh** [comment]
You don't need rootless mode, although we support it. What's the host machine? You said Windows first, which actually has full support for [Docker Desktop](https://www.docker.com/products/docker-desktop/) with the WSL2 backend. You can also use Linux with the Docker install, and either use `sudo`, add to the `docker` group, or rootless mode. If you use rootless however with `cross`, you need to specify it since by default we assume rootful mode for Docker.

**Comment by Alexhuszagh** [comment]
We can probably add some documentation on the Wiki though with setup though, since Docker Desktop is the preferred way for Windows/macOS, and Linux Podman is probably the easiest (although Docker is the best tested).

**Comment by Lokathor** [comment]
> What's the host machine?

I usually use Windows, but I also have easy enough access to an x86_64 linux, an aarch64 linux, an an x86_64 mac.

> actually has full support for [Docker Desktop](https://www.docker.com/products/docker-desktop/) with the WSL2 backend.

I've never heard of docker desktop, and actually i also don't remember how to even turn on wsl2, though maybe i installed it once long ago.

> We can probably add some documentation on the Wiki though with setup though

Awesome, yeah.

I don't myself need more setup support, I think I've got it working now. However, I suspect that most people coming to cross for the first time have next to no background with _any_ of the special terms you're using very casually. I'm not saying you've done anything wrong directly, but it's very easy to forget how much you really know, and so how much others don't yet know and will need to be told about.

I read the top few paragraphs of the readme two or three times, gave up on understanding it entirely, just tried to install stuff that sounded right, and googled for answers, and eventually it worked after 15 minutes.  But I bet there's a better way, so the next new user could have a simpler time.

**Comment by Alexhuszagh** [comment]
I've added a more detailed installation guide to the [wiki](https://github.com/cross-rs/cross/wiki/Getting-Started). Let me know if you see any issues with it or something isn't clear.

**Comment by Lokathor** [comment]
That's amazing, I love it!
