### ISSUE TITLE
error: failed to run custom build command for `libc v0.2.126`

### ISSUE THREAD

**Issue by Qark-dev** [cross-rs/cross#988]
[yor@qat]$ cross b --release --target aarch64-unknown-linux-musl
   Compiling libc v0.2.126
   Compiling log v0.4.17
   Compiling memchr v2.5.0
   Compiling typenum v1.15.0
   Compiling futures-core v0.3.21
   Compiling parking_lot_core v0.9.3
   Compiling proc-macro2 v1.0.42
   Compiling quote v1.0.20
   Compiling futures-task v0.3.21
   Compiling futures-util v0.3.21
error: failed to run custom build command for `libc v0.2.126`

Caused by:
  process didn't exit successfully: `/target/release/build/libc-00b66b583e76f388/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/libc-00b66b583e76f388/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /target/release/build/libc-00b66b583e76f388/build-script-build)
  /target/release/build/libc-00b66b583e76f388/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /target/release/build/libc-00b66b583e76f388/build-script-build)
  /target/release/build/libc-00b66b583e76f388/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /target/release/build/libc-00b66b583e76f388/build-script-build)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `libc v0.2.126`

Caused by:
  process didn't exit successfully: `/target/release/build/libc-00b66b583e76f388/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/libc-00b66b583e76f388/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /target/release/build/libc-00b66b583e76f388/build-script-build)
  /target/release/build/libc-00b66b583e76f388/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /target/release/build/libc-00b66b583e76f388/build-script-build)
  /target/release/build/libc-00b66b583e76f388/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /target/release/build/libc-00b66b583e76f388/build-script-build)
error: failed to run custom build command for `memchr v2.5.0`

Caused by:
  process didn't exit successfully: `/target/release/build/memchr-c941eb519ef6ccd9/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/memchr-c941eb519ef6ccd9/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /target/release/build/memchr-c941eb519ef6ccd9/build-script-build)
  /target/release/build/memchr-c941eb519ef6ccd9/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /target/release/build/memchr-c941eb519ef6ccd9/build-script-build)
  /target/release/build/memchr-c941eb519ef6ccd9/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /target/release/build/memchr-c941eb519ef6ccd9/build-script-build)
error: failed to run custom build command for `typenum v1.15.0`

Caused by:
  process didn't exit successfully: `/target/release/build/typenum-22b6f25b4c6d9aea/build-script-main` (exit status: 1)
  --- stderr
  /target/release/build/typenum-22b6f25b4c6d9aea/build-script-main: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /target/release/build/typenum-22b6f25b4c6d9aea/build-script-main)
  /target/release/build/typenum-22b6f25b4c6d9aea/build-script-main: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /target/release/build/typenum-22b6f25b4c6d9aea/build-script-main)
  /target/release/build/typenum-22b6f25b4c6d9aea/build-script-main: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /target/release/build/typenum-22b6f25b4c6d9aea/build-script-main)
error: failed to run custom build command for `log v0.4.17`

Caused by:
  process didn't exit successfully: `/target/release/build/log-6ea8dccf4e5392d7/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/log-6ea8dccf4e5392d7/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /target/release/build/log-6ea8dccf4e5392d7/build-script-build)
  /target/release/build/log-6ea8dccf4e5392d7/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /target/release/build/log-6ea8dccf4e5392d7/build-script-build)
  /target/release/build/log-6ea8dccf4e5392d7/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /target/release/build/log-6ea8dccf4e5392d7/build-script-build)
error: failed to run custom build command for `parking_lot_core v0.9.3`

Caused by:
  process didn't exit successfully: `/target/release/build/parking_lot_core-f54ce720123b8103/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/parking_lot_core-f54ce720123b8103/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /target/release/build/parking_lot_core-f54ce720123b8103/build-script-build)
  /target/release/build/parking_lot_core-f54ce720123b8103/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /target/release/build/parking_lot_core-f54ce720123b8103/build-script-build)
  /target/release/build/parking_lot_core-f54ce720123b8103/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /target/release/build/parking_lot_core-f54ce720123b8103/build-script-build)
error: failed to run custom build command for `futures-core v0.3.21`

Caused by:
  process didn't exit successfully: `/target/release/build/futures-core-6622699a3707b262/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/futures-core-6622699a3707b262/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /target/release/build/futures-core-6622699a3707b262/build-script-build)
  /target/release/build/futures-core-6622699a3707b262/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /target/release/build/futures-core-6622699a3707b262/build-script-build)
  /target/release/build/futures-core-6622699a3707b262/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /target/release/build/futures-core-6622699a3707b262/build-script-build)
error: failed to run custom build command for `proc-macro2 v1.0.42`

Caused by:
  process didn't exit successfully: `/target/release/build/proc-macro2-0885cbb3ab41c682/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/proc-macro2-0885cbb3ab41c682/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /target/release/build/proc-macro2-0885cbb3ab41c682/build-script-build)
  /target/release/build/proc-macro2-0885cbb3ab41c682/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /target/release/build/proc-macro2-0885cbb3ab41c682/build-script-build)
  /target/release/build/proc-macro2-0885cbb3ab41c682/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /target/release/build/proc-macro2-0885cbb3ab41c682/build-script-build)
error: failed to run custom build command for `quote v1.0.20`

Caused by:
  process didn't exit successfully: `/target/release/build/quote-ec438dbc72b3144c/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/quote-ec438dbc72b3144c/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /target/release/build/quote-ec438dbc72b3144c/build-script-build)
  /target/release/build/quote-ec438dbc72b3144c/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /target/release/build/quote-ec438dbc72b3144c/build-script-build)
  /target/release/build/quote-ec438dbc72b3144c/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /target/release/build/quote-ec438dbc72b3144c/build-script-build)
error: failed to run custom build command for `futures-task v0.3.21`

Caused by:
  process didn't exit successfully: `/target/release/build/futures-task-4c347aa9c054f2fe/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/futures-task-4c347aa9c054f2fe/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /target/release/build/futures-task-4c347aa9c054f2fe/build-script-build)
  /target/release/build/futures-task-4c347aa9c054f2fe/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /target/release/build/futures-task-4c347aa9c054f2fe/build-script-build)
  /target/release/build/futures-task-4c347aa9c054f2fe/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /target/release/build/futures-task-4c347aa9c054f2fe/build-script-build)
error: failed to run custom build command for `futures-util v0.3.21`

Caused by:
  process didn't exit successfully: `/target/release/build/futures-util-9211556968d48e0a/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/futures-util-9211556968d48e0a/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /target/release/build/futures-util-9211556968d48e0a/build-script-build)
  /target/release/build/futures-util-9211556968d48e0a/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /target/release/build/futures-util-9211556968d48e0a/build-script-build)
  /target/release/build/futures-util-9211556968d48e0a/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /target/release/build/futures-util-9211556968d48e0a/build-script-build)

**Comment by Alexhuszagh** [comment]
Try running `cargo clean` and redoing your build or using different target directories for each cross-compilation target. This is an upstream issue (see #724), and unfortunately there's not much we can do about it except for recommending you to use custom target directories for each separate target or run `cargo clean` whenever the issue manifests.

**Comment by Qark-dev** [comment]
appreciate it!
