### ISSUE TITLE
get error code 53 when cross build target x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by dlintw** [cross-rs/cross#990]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

$ cross -V
cross 0.2.4 (f5b4671 2022-07-29)
[cross] note: Falling back to `cargo` on the host.
cargo 1.62.1 (a748cf5a3 2022-06-08)
$ cargo new hi
     Created binary (application) `hi` package
$ cd hi
$ cargo r
   Compiling hi v0.1.0 (/home/dlin/prj/trade/prj/rs/hi)
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/hi`
Hello, world!
$ cross build --release --target  x86_64-pc-windows-gnu
$ echo $?
53

### What target(s) are you cross-compiling for?

x86_64-pc-windows-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross  0.2.4 (f5b4671 2022-07-29)

### Example

```sh
cargo new hi
cd hi
cargo r
cross build --release --target  x86_64-pc-windows-gnu
echo $?
```

**Comment by Alexhuszagh** [comment]
Can you add the `-vv` flag to the invocation for the verbose output?

**Comment by dlintw** [comment]
+ cargo metadata --format-version 1 --filter-platform x86_64-pc-windows-gnu
+ rustc --print sysroot
+ /usr/bin/docker
+ /usr/bin/docker version -f '{{ .Server.Os }},,,{{ .Server.Arch }}'
+ rustup toolchain list
+ rustup target list --toolchain stable-x86_64-unknown-linux-gnu
+ rustup component list --toolchain stable-x86_64-unknown-linux-gnu
+ /usr/bin/docker run --userns host -e 'PKG_CONFIG_ALLOW_CROSS=1' -e 'XARGO_HOME=/home/foo/.xargo' -e 'CARGO_HOME=/home/foo/.cargo' -e 'CARGO_TARGET_DIR=/target' -e 'CROSS_RUNNER=' -e TERM -e 'USER=foo' --rm --user 1203:102 -v /home/foo/.xargo:/home/foo/.xargo:z -v /home/foo/.cargo:/home/foo/.cargo:z -v /home/foo/.cargo/bin -v /home/foo/rs/hi:/home/foo/rs/hi:z -v /home/foo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:/home/foo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:z,ro -v /home/foo/rs/hi/target:/target:z -w /home/foo/rs/hi ghcr.io/cross-rs/x86_64-pc-windows-gnu:main sh -c 'PATH="$PATH":"/home/foo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin" cargo build -vv --release --target x86_64-pc-windows-gnu'
+ rustup component list --toolchain stable-x86_64-unknown-linux-gnu

**Comment by Alexhuszagh** [comment]
I've tried installing that exact version and running the build on Windows (not inside WSL2, but using the WSL2 backend), and this doesn't seem like a `cross` issue. Any chance you can try seeing if the following also fails:

```bash
/usr/bin/docker run --userns host -e 'PKG_CONFIG_ALLOW_CROSS=1' -e 'XARGO_HOME=/home/foo/.xargo' -e 'CARGO_HOME=/home/foo/.cargo' -e 'CARGO_TARGET_DIR=/target' -e 'CROSS_RUNNER=' -e TERM -e 'USER=foo' --rm --user 1203:102 -v /home/foo/.xargo:/home/foo/.xargo:z -v /home/foo/.cargo:/home/foo/.cargo:z -v /home/foo/.cargo/bin -v /home/foo/rs/hi:/home/foo/rs/hi:z -v /home/foo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:/home/foo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:z,ro -v /home/foo/rs/hi/target:/target:z -w /home/foo/rs/hi ghcr.io/cross-rs/x86_64-pc-windows-gnu:main sh -c 'echo "Hello World"'
```

**Comment by Emilgardis** [comment]
with the username fixed, I suspect your username is not `foo`

**Comment by dlintw** [comment]
> I've tried installing that exact version and running the build on Windows (not inside WSL2, but using the WSL2 backend), and this doesn't seem like a `cross` issue. Error code 53 on Linux is `EBADR`, which is a [bad request descriptor](https://www.halolinux.us/kernel-reference/request-descriptors.html). Any chance you can try seeing if the following also fails:
> 
> ```shell
> /usr/bin/docker run --userns host -e 'PKG_CONFIG_ALLOW_CROSS=1' -e 'XARGO_HOME=/home/foo/.xargo' -e 'CARGO_HOME=/home/foo/.cargo' -e 'CARGO_TARGET_DIR=/target' -e 'CROSS_RUNNER=' -e TERM -e 'USER=foo' --rm --user 1203:102 -v /home/foo/.xargo:/home/foo/.xargo:z -v /home/foo/.cargo:/home/foo/.cargo:z -v /home/foo/.cargo/bin -v /home/foo/rs/hi:/home/foo/rs/hi:z -v /home/foo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:/home/foo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:z,ro -v /home/foo/rs/hi/target:/target:z -w /home/foo/rs/hi ghcr.io/cross-rs/x86_64-pc-windows-gnu:main sh -c 'echo "Hello World"'
> ```
> 
> This does all the necessary bind mounts but instead of running `cargo`, just prints `"Hello World"`.

the result is error code 53, without any message.

**Comment by dlintw** [comment]
```
$ docker run --rm -it ghcr.io/cross-rs/x86_64-pc-windows-gnu:main /bin/sh
$ echo $?
53
$ docker run --rm -it ghcr.io/cross-rs/x86_64-pc-windows-gnu /bin/sh
#  workable
```
Does that mean main tag docker images is not workable?

**Comment by Emilgardis** [comment]
id docker working at all?

```
$ docker run hello-world
```

**Comment by Alexhuszagh** [comment]
> ```
> $ docker run --rm -it ghcr.io/cross-rs/x86_64-pc-windows-gnu:main /bin/sh
> $ echo $?
> 53
> $ docker run --rm -it ghcr.io/cross-rs/x86_64-pc-windows-gnu /bin/sh
> #  workable
> ```
> 
> Does that mean main tag docker images is not workable? If so, How can I just run cross on the image without 'main' tag?

Can you try `docker pull ghcr.io/cross-rs/x86_64-pc-windows-gnu:main`? I wonder if your `main` image is out-of-date. Without specifying a tag, it uses `latest`, which is an alias for `0.2.4` right now. This v0.2.4 image is the default image you would use if you install cross via `cargo install cross`. But our main images shouldn't be producing this issue.

**Comment by Emilgardis** [comment]
do `docker images | grep ghcr\\.io/cross-rs/x86_64-pc-windows-gnu` and post the output first before pulling

**Comment by dlintw** [comment]
main: Pulling from cross-rs/x86_64-pc-windows-gnu
Digest: sha256:20806216e162aa93d6c4c805bdcf163d8c33b5ad366f053efa78f3a614c26c22
Status: Image is up to date for ghcr.io/cross-rs/x86_64-pc-windows-gnu:main

**Comment by Alexhuszagh** [comment]
Can you post your Docker version, the host operating distro, if SELinux, AppArmour, etc. are enabled, and the output of `docker version`? This is still perplexing me, since I can't replicate it locally.

**Comment by dlintw** [comment]
```
Docker version 18.06.0-ce, build 0ffa825
[dlin@d1dk09 ~]$ more /etc/centos-release
CentOS Linux release 7.5.1804 (Core)

```

> > ```
> > $ docker run --rm -it ghcr.io/cross-rs/x86_64-pc-windows-gnu:main /bin/sh
> > $ echo $?
> > 53
> > $ docker run --rm -it ghcr.io/cross-rs/x86_64-pc-windows-gnu /bin/sh
> > #  workable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does that mean main tag docker images is not workable? If so, How can I just run cross on the image without 'main' tag?
> 
> Can you try `docker pull ghcr.io/cross-rs/x86_64-pc-windows-gnu:main`? I wonder if your `main` image is out-of-date. Without specifying a tag, it uses `latest`, which is an alias for `0.2.4` right now. This v0.2.4 image is the default image you would use if you install cross via `cargo install cross`. But our main images shouldn't be producing this issue. You can also specify a [custom](https://github.com/cross-rs/cross/wiki/Configuration#targettargetimage) image as well.
> 
> ```toml
> [target.aarch64-unknown-linux-gnu]
> image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:0.2.4"
> ```

Where to specify this? Cargo.toml of the simple project?  I've tried, but still get error code 53. seems failed.

**Comment by dlintw** [comment]
My updated Cargo.toml
```
name = "hi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:0.2.4"
[target.x86_64-pc-windows-gnu]
```
And the output of  `cross build -vv --release --target  x86_64-pc-windows-gnu`
```
+ cargo metadata --format-version 1 --filter-platform x86_64-pc-windows-gnu
+ rustc --print sysroot
+ /usr/bin/docker
+ /usr/bin/docker version -f '{{ .Server.Os }},,,{{ .Server.Arch }}'
+ rustup toolchain list
+ rustup target list --toolchain stable-x86_64-unknown-linux-gnu
+ rustup component list --toolchain stable-x86_64-unknown-linux-gnu
+ /usr/bin/docker run --userns host -e 'PKG_CONFIG_ALLOW_CROSS=1' -e 'XARGO_HOME=/home/foo/.xargo' -e 'CARGO_HOME=/home/foo/.cargo' -e 'CARGO_TARGET_DIR=/target' -e 'CROSS_RUNNER=' -e TERM -e 'USER=foo' --rm --user 1203:102 -v /home/foo/
.xargo:/home/foo/.xargo:z -v /home/foo/.cargo:/home/foo/.cargo:z -v /home/foo/.cargo/bin -v /home/foo/prj/rs/hi:/home/foo/prj/rs/hi:z -v /home/foo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:/home/foo/.rustup/toolchains/stable-x86
_64-unknown-linux-gnu:z,ro -v /home/foo/prj/rs/hi/target:/target:z -w /home/foo/prj/rs/hi ghcr.io/cross-rs/x86_64-pc-windows-gnu:main sh -c 'PATH="$PATH":"/home/foo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin" cargo build -vv
--release --target x86_64-pc-windows-gnu'
+ rustup component list --toolchain stable-x86_64-unknown-linux-gnu

```

**Comment by Alexhuszagh** [comment]
I don't think it's the project that has any issue: what I'm looking for is output similar to the following for `docker info` and `docker version`:

**Version**

```bash
$ docker version
Client:
 Cloud integration: v1.0.24
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.10.1 (82475)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Info**

```bash
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.5.1)
  extension: Manages Docker extensions (Docker Inc., v0.2.7)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 160
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 5
 Total Memory: 5.804GiB
 Name: docker-desktop
 ID: ...
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

You can omit the ID lines, any HTTP proxies, insecure registries, etc., but stuff like the commit ID, overlay driver, CPUs, available memory, etc. are very useful. For example output from both a Windows and Linux host, the Docker [documentation](https://docs.docker.com/engine/reference/commandline/info/) has you covered.

At least, we might be able to replicate the issue if I can get a similar config going.

**Comment by Emilgardis** [comment]
the `[target.aarch64-unknown-linux-gnu]` is part of the Cross config, see https://github.com/cross-rs/cross#configuration

so, to fix change to

```
[package.metadata.cross.target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:0.2.4"
[package.metadata.cross.target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:0.2.4"
```

**Comment by dlintw** [comment]
It works now, after assign the workable docker 0.2.4 (=lastest).

**Comment by Alexhuszagh** [comment]
> It works now, after assign the workable docker image 0.2.4 (=lastest). Maybe You just require assign main as 0.2.4.

See, this is why I need the other info: nothing that has changed in the images **should** cause this, but your device is the only example I can see that reproduces this behavior. We're not downgrading the numerous fixes and upgrades we've made since then unless we can isolate what's the cause. The newer images include numerous fixes, new Ubuntu distros, improved support for non-x86 architectures, and more.

**Comment by dlintw** [comment]
docker version
```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:08:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:10:42 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```
docker info
```
Containers: 8
 Running: 5
 Paused: 0
 Stopped: 3
Images: 50
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.9.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.43GiB
Name: d1dk09
ID: DS6M:JRHQ:CQXM:YV2F:4IHG:GTIR:FVYA:LDVP:XQ23:RD4O:BGVL:VK4K
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by Alexhuszagh** [comment]
Thanks for all the info! That's a very old Docker version (currently unsupported), which makes me think that it might be due to the upgrade in the Linux kernel version from 16.04 to 20.04, and this no longer being compatible with the kernel version the host has? Long story short: containers share the host kernel, and so the kernel will stay the same even if the distro version in the container changes. Generally, this is fine, because it's "compatible enough", and so everything just works. But for an old kernel version for the host (3.10) and an expected 5.4 for the image might just be the issue.

Can you test if do `docker run -it --rm ubuntu:$tag bash` where `tag` is either `20.04` or `16.04`? If not, I should be able to get a working test case from this thanks!

**Comment by Alexhuszagh** [comment]
Just adding the following details so anyone can follow along with my work below:

1. Download the minimal ISO for CentOS 7 for [x86_64](https://www.centos.org/download/).
2. Create a VM for it, and the ensure you can install the exact Docker version with the same kernel info:

```bash
$ yum install -y yum-utils
$ yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
# shows all the duplicates, this is just a debugging step
$ yum list docker-ce --showduplicates | sort -r
# get our exact docker version
$ yum install -y docker-ce-18.06.0.ce-3.el7
```

Now, let's get diagnostic info:

```bash
$ uname -a
Linux localhost.localdomain 3.10.0-116071.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ systemctl start docker
$ docker info | grep Kernel
Kernel Version: 3.10.0-116071.1.el7.x86_64
$ docker --version
Docker version 18.06.0-ce, build 0ffa825
````

I'm then able to replicate everything now, and will be trying to triage the cause. I don't think we can fix this (almost certain this is a kernel compatibility issue, and the solution is use a newer host or older image version), but it's pretty easy to triage. Specifically, `ghcr.io/cross-rs/x86_64-pc-windows-gnu:0.2.4` succeeds, but `ghcr.io/cross-rs/x86_64-pc-windows-gnu:main` fails.

**Comment by Alexhuszagh** [comment]
I've been able to find the offending commit for this specific issue, based on the builds [here](https://hub.docker.com/repository/docker/ahuszagh/centos_cross), and it's (as expected) 6dbdac10d8a6dd3715c06b9b5d20ccab996d0fd7, or the update to Ubuntu 20.04. I'll be checking to see that this is a kernel version for the host issue and not a Docker version issue and updating the documentation.
