### ISSUE TITLE
Unable to build with flag `--quiet`.

### ISSUE THREAD

**Issue by ChriFo** [cross-rs/cross#996]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When adding the flag `--quiet` or  `-q` an error appear.

### What target(s) are you cross-compiling for?

x86_64-unknown-linux-musl

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.4 (347730d 2022-08-12)

### Example

```
$ cross build -q                                      
[cross] error: cannot set both --verbose and --quiet
```

```
$ cross build --quiet
[cross] error: cannot set both --verbose and --quiet
```

**Comment by Emilgardis** [comment]
do you have any of `CARGO_TERM_QUIET` / `CARGO_TERM_VERBOSE` defined in your env?

**Comment by ChriFo** [comment]
No.

```
$ env | grep CARGO
CARGO_HOME=/usr/local/cargo
```

```
env | grep CROSS
CROSS_CONTAINER_IN_CONTAINER=1
```

**Comment by Emilgardis** [comment]
ah, I had a old ersion of cross installed, can replicate, need to figure out why this happens, it's most likely due to #968

**Comment by ChriFo** [comment]
Building cross from #997 fixed it for me. 🎉  Merci @Emilgardis
